=== 設定

==== 権限設定
AppConsoleは、`AppAdmin` ロールに属するユーザーのみが利用できるようにあらかじめ設定されています。

.ロール
`AppAdmin` としてロールが定義されています。 +
`AppAdmin` ロールは、 `AppAdmin` グループに所属するユーザーが条件になっています。

.Action権限
AppConsoleは以下のAction権限により実行可否を制御します。
----
appcon/index
----
Tenantが作成された段階であらかじめ `appcon/index` Actionに対して権限が設定されています。

エンドユーザーに対してAppConsoleの利用を許可する場合は、以下のどちらかの方法を実施してください。

* ユーザーの所属グループに `AppAdmin` を設定する
* 独自のロールに対して、 `appcon/index` Actionへの権限を付与する

==== メニュー設定
AppConsole画面を起動するには、 `appcon/index` Actionを実行します。 +
MenuItem定義にこのActionを実行するメニューを追加するか、 あらかじめとUrlMenuItemとして定義されている
`appcon/template/top` メニューを利用してMenuに設定ください。
標準では別タブで開くよう設定するため、UrlMenuItemで定義しています。

==== Preference設定
AppConsoleのカスタマイズは<<../customizing/index.adoc#Preference, Preference機能>>で行います。
----
appcon/appconPreference
----

以下はデフォルトで提供しているAppConsoleのPreferenceです。
必要に応じて変更してください。

[cols="1,3a,1", options="header"]
|===
|項目|説明|初期値
|entity/customPrefix|ユーザーが作成するEntity定義の名前につける接頭辞。 +
ユーザーが作成したEntityはこの配下に作成します。また画面の「カスタムEntity」に表示されるEntityもこの配下のもののみです。
|_custom.
|entity/includeSystemPrefix|Entity設定画面で「システム Entity」として表示するEntity名の正規表現。 +
いくつかに分けて複数定義することも可能です。複数の場合はORとして判定します。
|(mtp\.Information)\|(mtp\.auth\.Group)\|(mtp\.auth\.Rank)\|(mtp\.auth\.User)
|===
