== データ管理について
リレーショナルデータベース(RDB)などに代表されるデータの構造定義や永続化を実現する仕組みとして、
iPLAssではEntityメタデータを利用します。
RDBにおけるテーブルはEntityとして定義し、テーブルのカラムはPropertyとして定義します。

Entityには以下の機能・特徴があります。

* 動的な定義 +
Entityは管理画面上から動的に作成することができます。
RDBのように物理的にテーブルを追加・修正する必要はありません。
またEntityに定義可能なPropertyにはタイプ（StringやInteger、Binaryなど）ごとに
特化したProperty型があらかじめ用意されています。
格納したいデータタイプに合わせてProperty型を選択していきます。

* データ操作画面の自動生成（Generic Entity Manager） +
Entityを定義するだけで、汎用的な検索画面、登録・編集画面が実行可能になります。
汎用画面は、表示項目や表示レイアウトなど、独自にカスタマイズすることもできます。また、カレンダービュー、ツリービューなどいくつかの表示形式を標準で提供しています。 +
詳細は<<../genericentitymanager/index.adoc#, GEM（Generic Entity Manager）>>を参照してください。 +
また、 [.eeonly]#マテリアルデザインに準拠したデータ操作画面（Material Design Components、通称：MDC）# を提供します。
MDCはレスポンシブなデザインを特徴としています。 +
詳細は<<../materialdesigncomponents/index.adoc#, [.eeonly]#MDC（Material Design Components）# >>を参照してください。

* データ検証 +
Propertyごとに必須チェックやLengthチェックなどのValidatorを設定することができます。

* EventListener +
EntityのCRUD操作（登録、参照、更新、削除など）時の前後に独自処理を組み込むことができます。

* データのバージョン管理 +
Entityの1レコードに対して、複数のバージョンを保持することができます。
バージョン管理を利用することで、修正履歴を保持できたり、先日付データを事前に登録することが可能になります。

* Entityの権限制御 +
EntityのCRUD操作（登録、参照、更新、削除など）に対する権限をロールを利用して制御することができます。 +
詳細は<<../authorization/index.adoc#, 認可>>を参照してください。

* クエリ言語(EQL) +
データ操作はiPLAss独自のEQLというSQLライクなクエリ言語を利用します。
Entityデータの永続化にはバックエンドでRDBを利用しますが、
開発者はバックエンドのRDB差異を意識する必要はほとんどありません。 +
詳細は<<../../eqlreference/index.adoc#, EQLリファレンス>>を参照してください。

* WebApi操作 +
EntityのCRUD操作（登録、参照、更新、削除など）を実行するWebApiを標準で提供しています。 +
詳細は<<../webapi/index.adoc#_entity_crud_api, EntityCRUD API>>を参照してください。

* 全文検索 +
Entityデータに対して、全文検索エンジンを利用したIndexの生成、検索機能を標準でサポートしています。 +
詳細は<<ref_fulltext_search, 全文検索>>を参照してください。

* [.eeonly]#データ監査ログ# +
EntityのCRUD操作（登録、参照、更新、削除など）に対するログを記録することができます。
記録されたログはデータ操作画面上で表示したり、管理コンソール上で参照することができます。

* [.eeonly]#データ暗号化# +
Entityのデータ内容をデータベースに保存する際に暗号化することができます。
データベースの暗号化オプションを利用可能な場合は、そちらを利用することを推奨しますが、
データベースの暗号化オプションの利用が難しい場合の次善のソリューションとして利用可能です。
