
== ロールの管理
iPLAssでは、ロールは `mtp.auth.Role` エンティティとしてデフォルトで定義されています。 +
ロールの管理は、ユーザー毎に付与するのではなく、ロール側で付与された割り当て条件によってユーザーに割り当てられます。 +
ロールに対して権限を付与することで、個々のユーザーに対してではなく、ある範囲のユーザーに対してまとめて権限を制御する事が可能です。

ロールの管理は、GEM画面の「権限情報」のメニューに表示される各設定画面から行うことが出来ます。 +
管理者(admin)であれば、AdminConsoleの「Tools」に表示されている「PermissionExplorer」から行うことも可能です。 +
PermissionExplorerの詳細は <<../support/index.adoc#tools_permissionexplorer, PermissionExplorer>>を参照してください。

=== ロールのプロパティ

.ロールのプロパティ設定
[cols="1,3a", options="header"]
|===
|項目名|内容
|ロールコード|任意のロールコードを指定します。テナント単位で一意である必要があります。
|名前|ロールの表示名を指定します。
|優先順位|優先順位を設定します。Action権限等にロールを複数設定した場合に適用させるロールの優先順位となります。設定値が大きい方が優先されます。
|説明|本ロールの説明を設定します。
|<<en_rolecondition,ロール条件>>|本ロールの割り当て条件を設定します。
|<<en_actionperm,Action権限>>|ロールに付与されたAction権限の参照情報となります。
|<<en_entityperm,Entity権限>>|ロールに付与されたEntity権限の参照情報となります。
|<<en_webapiperm,WebApi権限>>|ロールに付与されたWebApi権限の参照情報となります。
|<<en_workflowperm,Workflow権限>>|ロールに付与されたWorkflow権限の参照情報となります。
|<<en_usertaskperm,UserTask権限>>|ロールに付与されたUserTask権限の参照情報となります。
|<<en_cubeperm,Cube権限>>|ロールに付与されたCube権限の参照情報となります。
|===

NOTE: 各権限の情報編集は直接行えません。権限の各設定においてロールの指定と条件を設定します。
GEMの画面ではリンクで表示され、リンクをクリックすることで権限の設定画面に遷移します。


[[en_rolecondition]]
==== ロール条件
ロール条件はGroovyScript形式で定義します。
ユーザー情報などチェック対象の属性がバインド変数として渡されるので、判定結果を `true/false` で返すように実装します。

ロール条件は複数設定することができます。複数設定した場合はORとして判定します。
どれか１つでも `true` であればロールに該当すると判断されます。

いくつか例を示します。

* `User` エンティティの所属グループで判定 +
所属グループ( `groups` )を条件としたい場合、以下のようにグループコードを指定することで、そのグループに属しているメンバーを条件とすることができます。
グループは階層構造を持っているため、 `memberOf` 関数が提供されています。
+
[source,groovy]
----
user.memberOf("TEST001")
----

* `User` エンティティのランクで判定 +
所属ランク( `rank` )も条件に指定可能です。「ユーザーのランクのレベル属性が5以上」といった定義になります。
+
[source,groovy]
----
user.rank.level > 5
----

* 未ログインユーザーの判定 +
未ログインユーザーを条件とする場合はanonymousフラグを利用します。
anonymousフラグはユーザー情報のプロパティではありませんが、ログイン状態に応じてuserに付与されています。
+
[source,groovy]
----
user.anonymous==true
----

バインド変数などの詳細は<<condition_format, 各種条件の書式>>を参照してください。


== 権限管理
iPLAssでは、機能ごとの権限（Entity、Action、WebAPI、Workflow、UserTask、Cube）をEntityとして管理しています。 +
ロールに対して、機能ごとの権限を利用目的に応じて設定し、ロールに権限を付与することでアプリケーションの利用範囲や権限が異なるロールを作成することができます。 +
Entity権限では、Entityの各操作（登録、参照、更新、削除）に対して許可／不許可及び、許可範囲を設定し、その他権限（Action、WebAPI、Workflow、UserTask、Cube）では、アクションの実行を許可／不許可及び、許可範囲を設定し、アクセス制御を行います。

[[en_entityperm]]
=== Entity権限
Entityの各操作（登録、参照、更新、削除）の許可／不許可及び、許可範囲の設定を行います。
また、プロパティ単位で許可するプロパティを指定できます。

Entityレベルでの許可範囲はあくまでEntity単位に対してのものであり、プロパティに対してのものではありません。
対象Entity内のプロパティに対して、自ユーザーのデータは参照可能、他ユーザーのデータは参照不可、といった指定はできません。
そのような制御をしたい場合は、参照可能範囲を変えたい属性類を別Entityに定義してEntityレベルで参照範囲を絞って下さい。
尚、参照プロパティについては、参照先エンティティの権限も設定する必要があります。

Entityに対する権限が未設定の場合の挙動は以下の形です。

- いずれのロールに対しても権限が未設定の場合 +
ログインユーザーのみEntityの各操作（登録、参照、更新、削除）は**許可**

- いずれかのロールに対して権限が設定されている場合 +
権限が設定されていないロールのユーザーの各操作は**不許可**

.Entity権限のプロパティ設定
[cols="1,3a", options="header"]
|===
|項目名|内容
|名前|Entity権限の表示名を設定します。
|対象Entity|対象とするEntityを設定します。
|ロール|対象とするロールを設定します。
|参照権限の設定|[cols="1,3a", options="header"]
!===
!項目名!内容
!参照!参照操作に対する、「許可」、「不許可」を設定します。
!<<range_condition, 参照可能範囲条件>>!参照可能範囲を設定します。
!参照プロパティの制御!「参照プロパティのリスト」プロパティに対して、「参照可」、「参照不可」を設定します。
!参照プロパティのリスト!対象とするプロパティを設定します。カンマ区切り、もしくはスペース区切りで複数指定が可能です。
!===
|登録権限の設定|[cols="1,3a", options="header"]
!===
!項目名!内容
!登録!登録操作に対する、「許可」、「不許可」を設定します。
!登録可能範囲条件!<<range_condition, 参照可能範囲条件>>と同じ書式で設定します。
!登録プロパティの制御!「登録プロパティのリスト」プロパティに対して、「登録可」、「登録不可」を設定します。
!登録プロパティのリスト!対象とするプロパティを設定します。カンマ区切り、もしくはスペース区切りで複数指定が可能です。
!===
|更新権限の設定|[cols="1,3a", options="header"]
!===
!項目名!内容
!更新!更新操作に対する、「許可」、「不許可」を設定します。
!更新可能範囲条件!<<range_condition, 参照可能範囲条件>>と同じ書式で設定します。
!更新プロパティの制御!「更新プロパティのリスト」プロパティに対して、「更新可」、「更新不可」を設定します。
!更新プロパティのリスト!対象とするプロパティを設定します。カンマ区切り、もしくはスペース区切りで複数指定が可能です。
!===
|削除権限の設定|[cols="1,3a", options="header"]
!===
!項目名!内容
!削除!削除操作に対する、「許可」、「不許可」を設定します。
!削除可能範囲条件!<<range_condition, 参照可能範囲条件>>と同じ書式で設定します。
!===
|===

[[range_condition]]
==== 参照可能範囲条件
参照可能範囲条件は、 PreparedQuery（GroovyTemplate）形式で定義します。
対象のエンティティに対するWHERE条件を設定します。

ユーザー情報等がバインド変数として用意されており、条件として利用することができます。

NOTE: バインド変数を利用する場合は$で括る必要があります。

いくつか例を示します。

* 直接文字列で指定 +
`col01` プロパティの値が `01` のもののみを対象とする場合は以下のように記述します。
+
[source,groovy]
----
col01='01'
----

* バインド変数 `user` を利用 +
バインド変数を利用する場合は以下のように記述します。
+
[source,groovy]
----
oid = '${user.oid}'
----

* inの指定 +
下記のように `toIn` を利用し、プロパティの型に対応する値のCollection、配列、単一オブジェクトを指定する事も可能です。
ただし、参照型に対してEntityを直接指定することは出来ません。
+
[source,groovy]
----
group.oid in (${toIn(user.groupOid)})
group.oid in (${toIn(user.groupOidWithChildren)})
groupCode in (${toIn(user.groupCode)})
groupCode in (${toIn(user.groupCodeWithChildren)})
customPropertyCode in (${toIn(user.customPropertyCode)})
----

* 副問い合わせでの注意点 +
Oracleを利用している場合に、条件式に以下のような形で副問い合わせで定義した場合、OracleでORA-01799エラーが発生します。
（refer句にて、oid=(Select ～)を記述するとエラーとなる）
+
[source]
----
oid=(select groups.oid from mtp.auth.User where oid='${user.oid}')
----
+
oidに対して副問い合わせを限定条件として記述したい場合、下記のように定義してください。
+
[source]
----
oid in (select groups.oid from mtp.auth.User where oid='${user.oid}')
----

==== Entity権限のエンティティ
Entityに対する権限は、`EntityPermission` エンティティとして管理します。
----
mtp.auth.EntityPermission
----


[[en_actionperm]]
=== Action権限
特定のActionに対してのアクセス制御が可能です。

Action権限は対象Actionの階層（「/」の区切り）毎に権限が評価されます。対象Actionの階層に権限が未設定だった場合、上位の階層の権限をチェックし、権限が見つかるまで確認します。権限が未設定の場合の挙動は以下の形です。

- いずれのロールに対しても権限が未設定の場合 +
ログインユーザーのみActionの実行は**許可**

- いずれかのロールに対して権限が設定されている場合 +
権限が設定されていないロールのユーザーの実行は**不許可** +
詳細は、<<multi_role_permit_target,複数ロールの場合のAction権限>>を参照。

.Action権限の設定
[cols="1,3a", options="header"]
|===
|項目名|内容
|名前|Action権限の表示名を設定します。
|<<permit_target,対象Action>>|対象とするAction名を指定します。
|ロール|対象とするロールを設定します。
|<<permit_condition,許可条件>>|許可する条件を記述します。
|===

[[permit_target]]
==== 対象Actionの指定
Action名を個別に指定する以外に、ワイルドカード（*を指定可能）を利用する事もできます。
設定するのはコンテキスト、テナント名を除くアクション名のみとなります。

例）下記URLのサービスに対して制御する場合（mtpがコンテキスト、demoがテナント名）
====
http://localhost:8080/mtp/demo/site/hogehoge
====
* hogehogeアクションのみを制御したい場合 +
+
----
site/hogehoge
----

* site配下を制御したい場合 +
+
----
site/*
----

[[multi_role_permit_target]]
==== 複数ロールの場合のAction権限評価について
[cols="2,1,1", options="header"]
|===
|対象Action|ロールA|ロールB
|site/*|設定|設定
|site/path/*|未設定|設定
|site/another/*　※説明のために記載。実際には設定しない定義|未設定|未設定
|===

上記のような階層で定義された対象Actionの場合、パスの深い階層からチェックして対象Actionが存在すれば、その階層の権限チェックをする仕様となります。

例えば、ロールAのユーザーが以下のURLにアクセスした場合
====
http://localhost:8080/mtp/demo/site/path/search
====

`/site/path/*` にロールBに紐づく権限が設定されているので、その階層でチェックし、ロールAの権限は未設定のため、**権限なし**と判断され、``**Action実行不可**``となります。

また、ロールAのユーザーが以下のURLにアクセスした場合
====
http://localhost:8080/mtp/demo/site/another/search
====

`/site/another/\*` の権限は、どのロールにも設定されていないので、上位の `/site/*` の階層でチェックし、**権限あり**と判断され、``/site/*`` の権限通り制御されます。

[[permit_condition]]
==== 許可条件
許可条件はGroovyScript形式で定義します。
ユーザー情報やリクエストパラメータなどチェック対象の属性がバインド変数として渡されるので、判定結果を `true/false` で返すように実装します。

いくつか例を示します。

* 全てを許可 +
設定したロールを保持するユーザー全てに対して許可したい場合は `true` と設定して下さい。
+
[source,groovy]
----
true
----

* リクエストパラメータで制限 +
リクエストパラメータを条件に指定する事も可能です。
+
.defNameがHogeEntityの場合に許可 +
+
[source,groovy]
----
parameter.defName == 'HogeEntity'
----

* リクエストパラメータで複数の値をチェック(in) +
`in` 句を利用して第一引数にパラメータ名、第二引数以降に条件としたい値を指定することも出来ます。
+
.defNameがHogeEntityもしくFugaEntityの場合に許可 +
+
[source,groovy]
----
parameter.in('defName', 'HogeEntity', 'FugaEntity')
----

* 複数のリクエストパラメータで制限 +
+
.defNameがHogeEntityかつaaaが1の場合に許可 +
+
[source,groovy]
----
parameter.defName == 'HogeEntity' && parameter.aaa == '1'
----

バインド変数などの詳細は<<condition_format, 各種条件の書式>>を参照してください。

==== Action権限のエンティティ
Actionに対する権限は、`ActionPermission` エンティティとして管理します。
----
mtp.auth.ActionPermission
----


[[en_webapiperm]]
=== WebApi権限
特定のWebApiに対してのアクセス制御が可能です。

WebApi権限もAction権限同様、対象の階層（「/」の区切り）毎に権限が評価されます。実行するWebApiの階層に権限が未設定だった場合、上位の階層の権限をチェックし、権限が見つかるまで確認します。権限が未設定の場合の挙動は以下の形です。

- いずれのロールに対しても権限が未設定の場合 +
ログインユーザーのみWebApiの実行は**許可**

- いずれかのロールに対して権限が設定されている場合 +
権限が設定されていないロールのユーザーの実行は**不許可** +
Action権限と同様となります。詳細は、<<multi_role_permit_target,複数ロールの場合のAction権限>>を参照。

.WebApi権限の設定
[cols="1,3a", options="header"]
|===
|項目名|内容
|名前|WebApi権限の表示名を設定します。
|対象WebApi|対象とするWebApi名を指定します。指定方法はAction権限の<<permit_target,対象Action>>と同様です。
|ロール|対象とするロールを設定します。
|許可条件|許可する条件を記述します。指定方法はAction権限の<<permit_condition,許可条件>>と同様です。
|===

==== WebApi権限のエンティティ
WebApiに対する権限は、`WebApiPermission` エンティティとして管理します。
----
mtp.auth.WebApiPermission
----


[[en_workflowperm]]
=== [.eeonly]#Workflow権限#
Workflow権限はあくまでワークフローを起動する為の権限であり、承認タスクなどはワークフロー内の設定に従います。

ここで設定された許可条件に該当するユーザーがWorkflowを開始することができます。

権限が未設定の場合の挙動は以下の形です。

- いずれのロールに対しても権限が未設定の場合 +
ログインユーザーのみWorkflowの開始は**許可**

- いずれかのロールに対して権限が設定されている場合 +
権限が設定されていないロールのユーザーのWorkflowの開始は**不許可**

.Workflow権限の設定
[cols="1,3a", options="header"]
|===
|項目名|内容
|名前|Workflow権限の表示名を設定します。
|対象Workflow|対象とするWorkflow名を指定します。
|ロール|対象とするロールを設定します。
|許可条件|許可する条件を記述します。指定方法はAction権限の<<permit_condition,許可条件>>と同様です。 +
ただし、パラメータ<<../workflow/index.adoc#workflow_start_parametor, Workflow起動時に設定>>したものとなります。
バインドされている変数等の詳細は<<condition_format, 各種条件の書式>>を参照してください。
|===

==== Workflow権限のエンティティ
Workflowに対する権限は、`WorkflowPermission` エンティティとして管理します。
----
mtp.auth.WorkflowPermission
----


[[en_usertaskperm]]
=== [.eeonly]#UserTask権限#
UserTask権限は割り当て済みのタスクを割り当てられてないユーザーが各操作（タスクの操作、ユーザーの割当変更）を実行するための権限です。

権限が未設定の場合の挙動は以下の形です。

- いずれのロールに対しても権限が未設定の場合 +
全てのユーザーの各操作は**不許可**

- いずれかのロールに対して権限が設定されている場合 +
権限が設定されていないロールのユーザーの各操作は**不許可**

.UserTask権限の設定
[cols="1,3a", options="header"]
|===
|項目名|内容
|名前|UserTask権限の名称を設定します。
|対象Workflow|対象Workflowを設定します。
|対象UserTask|対象UserTaskを設定します。
|ロール|対象とするロールを設定します。
|管理|管理操作に対する、「許可」、「不許可」を設定します。
|管理可能範囲条件|管理可能範囲を設定します。
指定方法はEntity権限の<<range_condition,参照可能範囲条件>>と同様です。
`UserTask` エンティティに対する条件を設定します。
管理可能範囲条件が未設定の場合は、当該のユーザータスクすべてが対象となります。
|===

==== UserTask権限のエンティティ
UserTaskに対する権限は、`UserTaskPermission` エンティティとして管理します。
----
mtp.auth.UserTaskPermission
----


[[en_cubeperm]]
=== [.eeonly]#Cube権限#
特定のCubeに対してのアクセス制御が可能です。

Cubeに対する権限が未設定の場合の挙動は以下の形です。

- いずれのロールに対しても権限が未設定の場合 +
ログインユーザーのみCubeの参照は**許可**

- いずれかのロールに対して権限が設定されている場合 +
権限が設定されていないロールのユーザーの参照は**不許可**

.Cube権限の設定
[cols="1,3a", options="header"]
|===
|項目名|内容
|名前|Cube権限の名称を設定します。
|対象Cube|対象Cubeを設定します。
|ロール|対象とするロールを設定します。
|参照|参照操作に対する、「許可」、「不許可」を設定します。
|参照可能範囲条件|参照可能範囲を設定します。指定方法はEntity権限の<<range_condition,参照可能範囲条件>>と同様です。
|参照項目の制御|「参照項目のリスト」プロパティに対して、「参照可」、「参照不可」を設定します。
|参照項目のリスト|対象とするプロパティを設定します。カンマ区切り、もしくはスペース区切りで複数指定が可能です。
|===

==== Cube権限のエンティティ
Cubeに対する権限は、`CubePermission` エンティティとして管理します。
----
mtp.auth.CubePermission
----
