[[aggregation_management]]
== 集計の管理

[[create_aggregation]]
=== Aggregationの作成
Aggregationアイコンを右クリックして `集計情報を作成する` を選択してください。
集計タイプ（Simple/Crosstab）とエンティティ定義名を選択してください。

[[aggregation_setting]]
=== 設定

[[aggregation_common_setting]]
==== 共通項目
設定可能な項目は下記となります。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|集計タイプ
|集計タイプを選択します。

Simple:: 定型集計、エンティティのデータを集計、一覧表示する
Crosstab:: 定型集計、エンティティのデータをクロス集計、表示する

Cubeについては<<../simplebi/index.adoc#, 簡易BI>>を参照してください。

|Entity定義名
|集計タイプがSimple、Crosstabの場合に集計対象となるエンティティを選択します。

|集計を特権で行う
|権限設定に関わらず集計を行いたい場合にチェックします。
集計対象エンティティの参照権限がないユーザーにも集計結果の閲覧を許可したい場合等に利用します。

|初期表示時にグラフと集計表を表示しない
|初期表示時ではなく、検索ボタン押下時に初めてグラフと集計表を表示するようにしたい場合にチェックします。
ただし、フィルタ項目が1件以上設定されている必要があります。

|集計結果を表示する
|集計結果の表を表示したい場合にチェックします。
グラフは表示したいが、結果表は表示したくない、またはその逆の場合に利用します。

|グラフを表示する
|グラフを表示したい場合にチェックします。
グラフは表示したいが、結果表は表示したくない、またはその逆の場合に利用します。

|集計表の上にグラフを表示する
|集計表の上部にグラフを表示したい場合にチェックします。
デフォルト（未チェック状態）では集計表の下にグラフを表示します。
集計結果、グラフともに表示設定されている事が前提です。

|グラフと集計表を並べて表示
|集計表とグラフを横に並べて表示したい場合にチェックします。
集計結果、グラフともに表示設定されている事が前提です。
`集計表の上にグラフを表示する` がチェックされている場合は、 `右：グラフ、左：集計表` になります。

|ファイルダウンロードを許可する
|集計画面でファイルダウンロードボタンが表示したい場合にチェックします。

|File type
|ダウンロードで利用するファイル形式を指定します。

CSV::
CSVファイルを利用します。

EXCEL::
EXCELファイルを利用します。

SPECIFY::
CSVファイルかEXCELファイルのどちらを利用するかを画面で選択します。

未指定の場合は、<<../../serviceconfig/index.adoc#EnterpriseGemConfigService,EnterpriseGemConfigService>> の `aggregationFileSupportType` によって動作します。

|File name format
|ファイルダウンロード時のファイル名をGroovyTemplate書式を利用して指定します。
詳細は<<ag_filenameformat, File name format>>を参照してください。

|保存リストを使用する
|未選択の場合、フィルター条件と結果の絞り込みの「保存リストから」を選択不可になります。
編集画面に「保存」ボタンとローデータメニューの「リストに保存」は表示されません。

|フィルタ項目|
集計画面で利用可能なフィルタ項目を設定します。
詳細は<<ag_filter, フィルタ項目>>を参照してください。

|Edit default filter
|フィルターの初期条件を設定するスクリプトを記述できます。
詳細は<<ag_editdefaultfilter, Edit default filter>>を参照してください。

|Edit Custom ViewScript
|集計画面内に埋め込むカスタムコード(HTML)を設定できます。GroovyTemplateとして定義します。

|Edit JavaScript Code
|集計画面内で実行するJavaScriptを設定できます。 +
コードは<script>タグ内に出力されます。GroovyTemplate形式ではないためバインド変数などは利用できません。
|===

[[ag_filenameformat]]
.File name format
ファイルダウンロード時のファイル名をGroovyTemplate書式を利用して指定します。
フォーマットが指定されている場合、ボタンに `(*)` が表示されます。
/とスペースについては、_（アンダースコア）に変換します。

利用可能なバインド変数は、編集ダイアログの `Notes` を参照してください。

.（例）ファイル名の後ろに出力時の時間を付加する。
[source,groovy]
----
${csvName}_${yyyy}${MM}${dd}${HH}${mm}${ss}
----

.（例）保存リストの場合は保存名を先頭に付加する。
[source,groovy]
----
<%
def fileName = defDisplayName;
if (savedListName != null) {
    fileName = savedListName + "_" + defDisplayName;
}
%>
${fileName}_${yyyy}${MM}${dd}${HH}${mm}${ss}
----

[[ag_filter]]
.フィルタ項目
集計画面で利用可能なフィルタ項目を設定します。
画面右側にある `Properties` より、フィルタ項目としたいプロパティをフィルタ項目表内部にドラッグ&ドロップします。
フィルタ項目のドラッグ&ドロップ後、対象フィルタ項目の右の鉛筆マークをクリックする事で下記設定が可能になります。

[cols="1,2a", options="header"]
|===
|項目
|設定値

|プロパティ表示名
|フィルタ項目としての表示名を指定します。

|表示タイプ
|プルダウン選択時は下部にある `追加` ボタンをクリックし、選択値を設定する必要があります。
プルダウンはプロパティの型によって設定できる項目が変化します。

|選択値
|表示タイプでプルダウンを選択した場合に、値と表示名をそれぞれ設定します。
|===

また、必須列にある鉛筆マークをクリックすると、フィルタ条件を必須項目にするかを指定できます。
必須項目にした場合、さらに利用可能な比較演算子を指定できます。
なお、フィルタ条件の型により、予め利用可能な比較演算子は決まっています。
利用できない比較演算子を選択した場合、集計画面では表示されません。

[[ag_editdefaultfilter]]
.Edit default filter
フィルターの初期条件を設定するスクリプトを記述できます。
設定内容については<<viewaggregation, 表示方法>>を参考にしてください。

以下はスクリプトの記述例になります。
バインドされているマップにキーと値を設定します。

[source,groovy]
----
initCondMap.put("doFilterAggregation", "true");
initCondMap.put("point_ope_0", "LE");
initCondMap.put("point_0", "50");
----

[[aggregation_simple_setting]]
==== 単純集計

===== 集計表設定
単純集計の集計表に関する設定です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|集計用EQL
|集計用のEQLを記述します。

.設定例
[source,sql]
----
select string001,sum(integer001),sum(integer002) from sample.aggregation.AggregationEntity001 group by string001 order by sum(integer001) desc
----

定義されたEQLはPreparedQueryとして処理されます。
次の変数がバインドされます。

filter:: 集計画面からエンドユーザーが入力したフィルター条件。
`org.iplass.mtp.entity.query.condition.Condition` のインスタンス。フィルター条件未指定の場合はnull

|1ページにおける最大件数
|表示項目の最大件数を指定します。
上記の例を利用した場合、集計項目となるstring001が対象となります。

|合計行の表示有無
|各集計項目の合計を表示したい場合にチェックします。
この設定を有効にしたい場合は `集計用EQL` にてグループ化が必要となります。

|同じ値のセルをまとめる
|列内の同じ値のセルをまとめ、一つのセルにします。
複数列ある場合は左から順にまとめますが、同じ値でも左側の列がまとまっていない場合はセルはまとまりません。

|ページングを非表示
|ページング部品(前を表示、次を表示)を非表示にする場合にチェックします。
非表示にした際は、1ページにおける最大件数を利用せず、全データを取得します。
データ件数が多い場合、処理に時間がかかる場合があります。

|ページング表示位置
|ページング部品の表示位置を設定します。

BOTH:: 検索結果の上下に表示
TOP:: 検索結果の上部に表示
BOTTOM:: 検索結果の下部に表示

|Interrupter Class
|集計結果をカスタマイズしたい場合に、カスタマイズ処理を実装したJavaクラスまたはUtilityClassを指定します。
指定するClassは `org.iplass.mtp.aggregation.unit.simple.SimpleAggregationViewInterrupter` を実装する必要があります。
詳細は<<aggregation_simple_customize, カスタム処理の組み込み>>を参照してください。

CAUTION: Interrupterクラスを指定した場合、ページングやローデータ出力は無効になります。 +
1ページにおける最大件数を利用せず全データを取得するため、利用する際は対象となるデータ件数を考慮してください。

|集計項目
|集計用EQLに記述した各集計項目のラベルを指定します。
詳細は<<aggregation_simple_item, 集計項目>>を参照してください。
|===

[[aggregation_simple_item]]
.集計項目
集計用EQLに記述した各集計項目のラベルを指定します。
上記の例を利用した場合、sum(integer001)、 sum(integer002)の順に適用されます。
`追加` ボタンをクリックすると下記ウィンドウが表示されます。

[cols="1,4a", options="header"]
|===
|項目
|設定値

|表示ラベル
|集計項目の表示ラベルを指定します。

|小計行の非表示
|合計行を表示する場合に設定可能な項目です。
指定した項目の小計行を非表示にする場合にチェックします。
group by句で指定したプロパティに対してのみ有効です。
なお、select句とgroup by句で指定したプロパティが一致しない場合、正しい動作にならないため、注意してください。

|グループ化項目
|ローデータを扱う場合に必要な項目です。
集計用EQLで指定したEQLのgroup by 句を指定します。
設定例を利用した場合、string001を指定します。

|フォーマッタ
|集計表に表示する際の数値のフォーマッタを指定します。
未指定、整数、小数の中から選択します。

|配置
|集計表に表示する際の数値の配置を指定します。
未指定、左寄せ、中央寄せ、右寄せの中から選択します。

|列幅
|集計表の列幅を指定します。
|===

===== グラフ設定
軸1の設定のグラフタイプにより設定項目が変わります。

[[line_bar_chart]]
.折れ線/棒グラフ
折れ線グラフと棒グラフの設定項目です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|グラフ高さ
|グラフ表示時の高さを指定します。
単位はpx固定です。
数値のみの入力となります。

|グラフ幅
|グラフ表示時の幅を指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。

（入力例： `800`、 `800px` または `50%`）

|第1軸の設定：グラフタイプ
|第1軸のグラフタイプを以下の8パターンから選択します。
各グラフタイプにより入力項目が変化します。

`線グラフ` 、 `棒グラフ` 、 `円グラフ` 、 `ドーナツグラフ` 、 `バブルチャート` 、 `散布図` 、 `レーダーチャート` 、`ピラミッド`

|横軸列
|集計用EQLで指定したEQLのgroup by句を指定します。
group by句が複数指定されている場合、グラフは正しく表示できない場合があります。

|積み上げグラフ
|グラフを積み上げグラフする場合にチェックします。
2軸設定している場合は無効となります。

|割合グラフで表示
|積み上げグラフを各項目の値ではなく、項目の合計値に対する割合で表示します。

|トレンドラインを表示
|トレンドラインを表示する場合にチェックします

|値表示方法
|集計項目の値の表示方法を以下の3パターンから選択します。

非表示:: グラフ上に値を表示しない
常に表示:: グラフ上に値を表示する
マウスオーバー時:: マウスオーバーした箇所の値を表示する

|棒グラフの幅
|グラフ表示時の棒グラフの幅を指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。数値のみの入力となります。

|棒グラフのパディング
|グラフ表示時の棒グラフのパディングを指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。
数値のみの入力となります。

|棒グラフのマージン
|グラフ表示時の棒グラフのマージンを指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。
数値のみの入力となります。

|項目のラベルを非表示
|軸に表示しているラベルを非表示にする場合にチェックします。

|各バーに異なる色を使用
|棒グラフで同じ色を使わず、異なる色を使うようにします。

|色の設定
|グラフの各要素に使われる色を設定します。
未指定時はデフォルトの色が適用されます。

|nullを0に変換
|軸1、軸2に指定された項目の値で、データがnullのものを0として扱います。
nullのままの場合、グラフ上には表示されません。

|凡例を非表示
|凡例を非表示にする場合にチェックします。

|凡例の表示位置(Placement)
|凡例の表示位置を以下の2パターンから選択します。

`内側` 、 `外側`

|凡例の表示位置(location)
|凡例の表示位置を以下の8パターンから選択します。

`左上` 、 `上` 、 `右上` 、 `右` 、 `右下` 、 `下` 、 `左下` 、 `左`

|凡例の行数
|凡例の行数を指定します。

|凡例の列数
|凡例の列数を指定します。

|X軸のラベルの傾き
|X軸のラベルの傾きを指定します。
単位は角度です。
数値のみの入力となります。

|X軸のラベルの表示位置
|X軸のラベルの表示位置を以下の3パターンから選択します。
目盛りの中心に選択したラベルの位置が調整されます。

`ラベルの先頭` 、 `ラベルの中央` 、 `ラベルの末尾`

|目盛りの数
|目盛りの数を指定します。
数値を入力します。
線グラフの種類が `数値` の場合に入力可能です。

|線グラフの種類
|軸1の設定のグラフタイプが棒グラフの場合のみ設定可能です。
以下の2パターンから選択します。

`カテゴリ` 、 `数値`

|数値フォーマット
|集計項目の数値の表示方法を以下の3パターンから選択します。

`未指定` 、 `整数` 、 `小数`

|小数の桁数
|数値フォーマットで `小数` を選択した場合の必須項目です。

|X軸の最大値
|X軸の最大値を指定します。
数値を入力します。
線グラフの種類が `数値` の場合に入力可能です。

|X軸の最小値
|X軸の最小値を指定します。
数値を入力します。
線グラフの種類が `数値` の場合に入力可能です。

|グリッド線を非表示
|グリッド上に表示されている線を非表示にする場合にチェックします

|グラフ対象アイテム
|プルダウンからグラフ対象アイテムを選択します。
必須ではありませんが、設定しないと正しく表示されません。
プルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。

|Y軸の最大値
|Y軸の最大値を指定します。
数値を入力します。

|Y軸の最小値
|Y軸の最小値を指定します。
数値を入力します。

|刻み幅
|Y軸の刻み幅を指定します。
数値を入力します。
2軸設定をした場合には有効になりません。

|曲線で表示
|線を曲線する場合にチェックします。
グラフタイプが `線グラフ` の場合のみ指定できます。

|基準線を表示
|基準線の設定で設定した内容をグラフ上に表示する場合にチェックします
|===

軸2の設定方法は軸1と同様となります。
軸2を設定した場合、軸1のY軸はグラフ左側に、軸2のY軸はグラフ右側に表示されます。

.円/ドーナツグラフ
円グラフ、ドーナツグラフの設定項目です。
下記以外については、<<line_bar_chart,折れ線/棒グラフ>>を参照してください。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|円に表示するラベル
|円グラフでデータを表示する際の表示方法を設定します。
|===

.バブルチャート/散布図
バブルチャートと散布図の設定項目です。
下記以外については、<<line_bar_chart,折れ線/棒グラフ>>を参照してください。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|トレンドラインを表示
|棒グラフと同様です。
グラフタイプが `散布図` の場合のみ設定できます。

|nullを0に変換
|軸1、軸2に指定された項目の値で、データがnullのものを0として扱います。
nullのままの場合、グラフ上には表示されません。

|X軸列
|プルダウンからX軸列を選択します。
プルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。

|Y軸列
|プルダウンからY軸列を選択します。
プルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。

|Z軸列
|プルダウンからZ軸列を選択します。
本項目がバブルの大きさと対応します。
バブルチャートのみプルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。

|ラベル列
|プルダウンからラベル列を選択します。
バブル内にラベルを表示します。
プルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。

|系列
|プルダウンから系列を選択します。
プルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。

|倍率(バブルチャートのみ)
|Ｚ軸の大きさの倍率を入力します。
未指定の場合は1となります。

|マーカーサイズ(散布図のみ)
|散布図の円のサイズを制定します。
|===

.ピラミッド
ピラミッドの設定項目です。
下記以外については、<<line_bar_chart,折れ線/棒グラフ>>を参照してください。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|集計軸
|プルダウンから集計軸を選択します。
プルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。

|集計項目
|プルダウンから集計項目選択します。
プルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。

|対比項目
|プルダウンから対比項目を選択します。
プルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。

|系列
|プルダウンから系列項目を選択します。
プルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。

|2目盛り毎に色分け
|集計軸を2目盛り毎に色を分けるかを選択します。
|===

.レーダーチャート
レーダーチャートの設定項目です。
下記以外については、<<line_bar_chart,折れ線/棒グラフ>>を参照してください。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|項目
|プルダウンから項目を選択します。
プルダウンには集計表設定の集計項目で指定した表示ラベルが選択可能な状態になっています。
|===

.基準線
基準線の設定項目です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|線の種類
|線の種類を選択します。
以下が選択可能です。

`Line` 、 `Horizontal` 、 `DashedHorizontal` 、 `Vertical` 、 `DashedVertical`

|名前
|線の名前を設定します。

|表示
|グリッドに線を表示するかを設定します。

|幅
|線の幅を設定します。

|色
|線の色を設定します。

|開始(X/Y)
|線の種類で `Line` を選択した場合のみ設定可能な必須項目です。
線の開始位置のX座標とY座標を設定します。

|終了(X/Y)
|線の種類で `Line` を選択した場合のみ設定可能な必須項目です。
線の終了位置のX座標とY座標を設定します。

|Y
|線の種類で `Horizontal` または `DashedHorizontal` を選択した場合のみ設定可能な必須項目です。
線のY座標を設定します。

|X最小値
|線の種類で `Horizontal` または `DashedHorizontal` を選択した場合のみ設定可能な項目です。
線のX座標の最小値を設定します。

|X最大値
|線の種類で `Horizontal` または `DashedHorizontal` を選択した場合のみ設定可能な項目です。
線のX座標の最大値を設定します。

|Xオフセット
|線の種類で `Horizontal` または `DashedHorizontal` を選択した場合のみ設定可能な項目です。
線のX座標のオフセットを設定します。

|X
|線の種類で `Vertical` または `DashedVertical` を選択した場合のみ設定可能な必須項目です。
線のX座標を設定します。

|Y最小値
|線の種類で `Vertical` または `DashedVertical` を選択した場合のみ設定可能な項目です。
線のY座標の最小値を設定します。

|Y最大値
|線の種類で `Vertical` または `DashedVertical` を選択した場合のみ設定可能な項目です。
線のY座標の最大値を設定します。

|Yオフセット
|線の種類で `Vertical` または `DashedVertical` を選択した場合のみ設定可能な項目です。
線のY座標のオフセットを設定します。

|ダッシュパターン
|線の種類で `DashedHorizontal` または `DashedVertical` を選択した場合のみ設定可能な項目です。
破線のパターンを設定します。
それぞれ線の長さ(px)とスペースの長さ(px)で、未指定時は `8、8` となります。
|===

.色
グラフの色の設定項目です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|色
|グラフの色を設定します。
|===

===== ローデータ設定
ローデータ出力時の項目などの設定です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|allow the output of raw data
|ローデータの出力許可。集計表やグラフからローデータの取得が可能となります。
集計表で出力したい行を選択（複数選択可）し、右クリックでコンテキストメニューを開きます。
グラフの場合は対象のデータをクリックして選択し、右クリックでコンテキストメニューから出力します。

本項目にチェックをした場合のみ、コンテキストメニューにローデータが表示されます。

|File type
|ダウンロードで利用するファイル形式を指定します。

CSV::
CSVファイルを利用します。

EXCEL::
EXCELファイルを利用します。

SPECIFY::
CSVファイルかEXCELファイルのどちらを利用するかを画面で選択します。

未指定の場合は、<<../../serviceconfig/index.adoc#EnterpriseGemConfigService,EnterpriseGemConfigService>> の `aggregationRawdataFileSupportType` によって動作します。


|File name format
|ファイルダウンロード時のファイル名をGroovyTemplate書式を利用して指定します。
詳細は<<ag_filenameformat, File name format>>を参照してください。

|File multiple format
|ファイルダウンロード時の多重度が複数のプロパティの出力形式を指定します。

Each Column::
多重度の数分別々の列に出力します。

One Column::
１つの列にカンマ区切りでまとめて出力します。

One Column Fill Null::
１つの列にカンマ区切りでまとめて出力します。
登録データが多重度分保存されていない場合にも多重度分空を補完します。

|raw data Query
|ローデータ取得用Query。 +
例）集計用EQLに以下が設定されている場合

[source,sql]
----
select string001,sum(integer001),sum(integer002) from sample.aggregation.AggregationEntity001 group by string001 order by sum(integer001) desc
----

ローデータ取得用Queryに下記を設定します。

[source,sql]
----
select integer001,integer002 from sample.aggregation.AggregationEntity001
----

定義されたEQLはPreparedQueryとして処理されます。
次の変数がバインドされます。

filter:: 集計画面からエンドユーザーが入力したフィルター条件。
`org.iplass.mtp.entity.query.condition.Condition` のインスタンス。フィルター条件未指定の場合はnull

|raw data item
|ローデータ出力項目のラベル、多重度を指定します。
上記の例を利用した場合、integer001, integer002に対応します。
Referenceプロパティに対する多重度は１を指定してください(行が分かれるため)。
|===

[[aggregation_simple_customize]]
===== カスタム処理の組み込み
カスタム処理を実装することで集計結果のカスタマイズが可能になります。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを `Interrupter Class` に指定します。

====
org.iplass.mtp.aggregation.unit.simple.SimpleAggregationViewInterrupter
====

.処理一覧
[cols="1,1,1,3a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

.2+|afterAggregate
|condition : SimpleAggregationCondition
.2+|List<Object[]>
.2+|集計結果を元にデータを編集します。
編集した結果を返します。
|data :List<Object[]>
|===

.SimpleAggregationViewInterrupterの例

[source,java]
----
package sample.aggregation.simple;

import org.iplass.mtp.aggregation.unit.simple.SimpleAggregationCondition;
import org.iplass.mtp.aggregation.unit.simple.SimpleAggregationViewInterrupter;

public class SampleSimpleInterrupter implements SimpleAggregationViewInterrupter {

	@Override
	public List<Object[]> afterAggregate(
		final SimpleAggregationCondition condition, final List<Object[]> data) {

		//最終行に行を追加(列は列定義にあわせる)
		Object[] row = new Object[3];
		row[0] = "test1";
		row[1] = "test2";
		row[2] = "test3";
		data.add(row);

		return data;
	}
}
----


[[aggregation_crosstab_setting]]
==== クロス集計
===== 集計表設定
クロス集計の集計表に関する設定です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|デフォルトフィルタ条件
|EQLのWhere句を指定することで、一律に指定した検索条件を有効にする事が可能です。

定義されたEQLはPreparedQueryとして処理されます。
次の変数がバインドされます。

filter:: 集計画面からエンドユーザーが入力したフィルター条件。
`org.iplass.mtp.entity.query.condition.Condition` のインスタンス。フィルター条件未指定の場合はnull

|合計行を表示
|集計表に各列の合計値を表示します。

|合計列を表示
|集計表に各行の合計値を表示します。

|Interrupter Class
|集計結果をカスタマイズしたい場合に、カスタマイズ処理を実装したJavaクラスまたはUtilityClassを指定します。
指定するClassは `org.iplass.mtp.aggregation.unit.crosstab.CrosstabAggregationViewInterrupter` を実装する必要があります。
詳細は<<aggregation_crosstab_customize, カスタム処理の組み込み>>を参照してください。

CAUTION: Interrupterクラスを指定した場合、ローデータ出力は無効になります。

|表側、表頭の集計対象のプロパティ
|表頭/表側となるプロパティを指定します。詳細は<<crosstab_fronthead_frontside, 表頭/表側>>を参照してください。

|集計結果の集計対象のプロパティ
|集計結果の集計対象となるプロパティを指定します。詳細は<<crosstab_aggregate_results, 集計結果>>を参照してください。
|===

[[crosstab_fronthead_frontside]]
.表頭/表側
緑のエリアには画面右側のPropertiesよりドラッグ&ドロップすることで、表頭/表側となる項目を指定できます。
集計項目の種類により設定する項目が変わります。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|集計項目の種類
|下記2パターンから集計項目を選択します。

`カテゴリカルデータ` 、 `数量データ`

|表示名
|集計結果項目の表示名を指定します。
表頭の場合のみグラフのラベルとして表示されます。

|合計カテゴリのラベル
|集計項目合計値のラベルを指定します。

|列幅
|集計表の列幅を指定します。
表側の集計項目のみ設定可能で、表頭の設定時には表示されません。
ここで設定した値は表側のヘッダ部分にのみ適用されます。
表頭部分及びデータ部分は集計結果の列幅が適用されます。

カスタムアイテムを利用して複数項目指定した場合、親項目列(子項目以外を組合せ)と子項目列の2列に別れます。
親項目列の幅は各親項目に指定された列幅の合計が適用され、子項目列の幅は子項目に指定された列幅が適用されます。

|プロパティ名
|集計対象のプロパティ名を指定します。
プロパティ名だけでなく数式（PreparedQuery）も指定可能です。

|ソート順
|集計結果のソート順を指定します。
集計項目の種類がカテゴリカルデータの場合のみ有効となります。

|カテゴリ
|集計したデータの表示名になり、表頭/表側に表示するラベルになります。
プロパティの値に対応するカテゴリを設定します。
集計項目の種類が数量データの場合は必須項目になります。
|===

[[crosstab_aggregate_results]]
.集計結果
画面右側のPropertiesよりドラッグ&ドロップすることで、集計結果の対象となる項目を指定できます。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|表示名
|本項目は汎用画面のどこにも出力されることはありません。
管理上必要となる項目です。

|数式
|表側、表頭の各合計値を集計する為の項目です。
プロパティをドラッグ&ドロップすることで `count(プロパティ名)` が設定されます。
その他数式も設定可能です。

|フォーマッタ
|集計表に表示する際の数値のフォーマッタを指定します。
未指定、整数、小数の中から選択します。

|配置
|集計表に表示する際の数値の配置を指定します。
未指定、左寄せ、中央寄せ、右寄せの中から選択します。

|列幅
|集計表に表示する際の列の幅を指定します。
|===

.カスタム項目
デフォルトでプロパティ名が入ってない項目です。
プロパティを組み合わせた数式を指定する事が可能です。

===== グラフ設定
クロス集計のグラフに関する設定です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|グラフタイプ
|グラフタイプを以下の3パターンから選択します。

`棒グラフ` 、 `線グラフ` 、 `円グラフ`

|主軸
|主軸を指定します。
表頭、表側のいずれかを選択可能です。

|グラフ高さ
|グラフ表示時の高さを指定します。
単位はpx固定です。
数値のみの入力となります。

|グラフ幅
|グラフ表示時の幅を指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。

（入力例： `800`、 `800px` または `50%`）

|Y軸の最大値
|Y軸の最大値を指定します。
数値を入力します。

|Y軸の最小値
|Y軸の最小値を指定します。
数値を入力します。

|積み上げグラフ
|棒グラフ表示時に指定可能です。

|割合グラフで表示
|積み上げグラフを各項目の値ではなく、項目の合計値に対する割合で表示します。

|トレンドラインを表示
|トレンドラインを表示する場合にチェックします。

|刻み幅
|Y軸の刻み幅を指定します。
数値を入力します。

|値表示方法
|集計項目の値の表示方法を以下の3パターンから選択します。

`非表示` 、 `常に表示` 、 `マウスオーバー時`

|X軸のラベルの傾き
|X軸のラベルの傾きを指定します。
単位は角度です。
数値のみの入力となります。

|X軸のラベルの表示位置
|X軸のラベルの表示位置を以下の3パターンから選択します。
目盛りの中心に選択したラベルの位置が調整されます。

`ラベルの先頭` 、 `ラベルの中央` 、 `ラベルの末尾`

|数値のフォーマット
|集計項目の数値の表示方法を以下の3パターンから選択します。

`未指定` 、 `整数` 、 `小数`

|小数の桁数
|数値フォーマットで `小数` を選択した場合の必須項目です。

|棒グラフの幅
|グラフ表示時の棒グラフの幅を指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。
数値のみの入力となります。

|棒グラフのパディング
|グラフ表示時の棒グラフのパディングを指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。
数値のみの入力となります。

|棒グラフのマージン
|グラフ表示時の棒グラフのマージンを指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。
数値のみの入力となります。

|X軸のグリッド線を非表示
|グリッド上に表示されているX軸の線を非表示にする場合にチェックします

|Y軸のグリッド線を非表示
|グリッド上に表示されているY軸の線を非表示にする場合にチェックします

|項目のラベルを非表示
|軸に表示しているラベルを非表示にする場合にチェックします。

|曲線で表示
|線を曲線にする場合にチェックします。
グラフタイプが `線グラフ` の場合のみ指定できます。

|各バーに異なる色を使用
|棒グラフで同じ色を使わず、異なる色を使うようにします。

|色の設定
|グラフの各要素に使われる色を設定します。
未指定時はデフォルトの色が適用されます。

|nullを0に変換
|軸1、軸2に指定された項目の値で、データがnullのものを0として扱います。
nullのままの場合、グラフ上には表示されません。

|凡例を非表示
|凡例を非表示にする場合にチェックします。

|凡例の表示位置(Placement)
|凡例の表示位置を以下の2パターンから選択します。

`内側` 、 `外側`

|凡例の表示位置(location)
|凡例の表示位置を以下の8パターンから選択します。

`左上` 、 `上` 、 `右上` 、 `右` 、 `右下` 、 `下` 、 `左下` 、 `左`

|凡例の行数
|凡例の行数を指定します。

|凡例の列数
|凡例の列数を指定します。

|基準線を表示
|基準線の設定で設定した内容をグラフ上に表示する場合にチェックします
|===


===== ローデータ設定
ローデータ出力時の項目などの設定です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|allow the output of raw data
|ローデータの出力許可。集計表からローデータの取得が可能となります。
集計表で出力したいセルや行を選択（複数選択可）し、右クリックでコンテキストメニューを開きます。
グラフの場合は対象のデータをクリックして選択し、右クリックでコンテキストメニューから出力します。

本項目にチェックをした場合のみ、コンテキストメニューにローデータが表示されます。

|File type
|ダウンロードで利用するファイル形式を指定します。

CSV::
CSVファイルを利用します。

EXCEL::
EXCELファイルを利用します。

SPECIFY::
CSVファイルかEXCELファイルのどちらを利用するかを画面で選択します。

未指定の場合は、<<../../serviceconfig/index.adoc#EnterpriseGemConfigService,EnterpriseGemConfigService>> の `aggregationRawdataFileSupportType` によって動作します。


|File name format
|ファイルダウンロード時のファイル名をGroovyTemplate書式を利用して指定します。
詳細は<<ag_filenameformat, File name format>>を参照してください。

|File multiple format
|ファイルダウンロード時の多重度が複数のプロパティの出力形式を指定します。

Each Column::
多重度の数分別々の列に出力します。

One Column::
１つの列にカンマ区切りでまとめて出力します。

One Column Fill Null::
１つの列にカンマ区切りでまとめて出力します。
登録データが多重度分保存されていない場合にも多重度分空を補完します。

|distinct raw data
|重複データを１つにまとめて出力します。

|raw data item
|ローデータの対象となる項目を設定します。
ローデータ表示時のラベルと、出力項目の値式、多重度を指定してください。
値式にはプロパティ名だけでなく数式（PreparedQuery）が指定可能です。
Referenceプロパティに対する多重度は１を指定してください(行が分かれるため)。
|===

[[aggregation_crosstab_customize]]
===== カスタム処理の組み込み
カスタム処理を実装することで集計結果のカスタマイズが可能になります。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを `Interrupter Class` に指定します。

====
org.iplass.mtp.aggregation.unit.crosstab.CrosstabAggregationViewInterrupter
====

.処理一覧
[cols="1,1,1,3a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

.2+|afterAggregate
|condition : CrosstabAggregationCondition
.2+|CrosstabResultSet
.2+|集計結果を元にデータを編集します。
編集した結果を返します。
|data :CrosstabResultSet
|===

.CrosstabAggregationViewInterrupterの例

[source,java]
----
package sample.aggregation.crosstab;

import org.iplass.mtp.aggregation.unit.crosstab.CrosstabAggregationViewInterrupter;
import org.iplass.mtp.aggregation.unit.crosstab.CrosstabAggregationCondition;
import org.iplass.mtp.aggregation.unit.crosstab.CrosstabResultSet;

import org.iplass.mtp.aggregation.unit.crosstab.Category;

public class SampleCrosstabInterrupter implements CrosstabAggregationViewInterrupter {

	@Override
	public CrosstabResultSet afterAggregate(
		final CrosstabAggregationCondition condition, final CrosstabResultSet data) {

		//最終行に「test」行追加
		Category row = new Category("test", "test");
		data.getRowCategory().add(row);

		//集計結果を取得
		Object[][] originData = data.getData();

		int colSize = data.getColumnCategory().size();
		int rowSize = data.getRowCategory().size();

		//最終行までコピー
		Object[][] editData = new Object[rowSize][colSize];
		System.arraycopy(originData, 0, editData, 0, originData.length);

		//最終行に値を設定
		Object lastRow = editData[rowSize - 1];
		for (int i = 0; i < colSize; i++) {
			lastRow[i] = "test_" + rowSize + "_" + (i + 1);
		}
		data.setData(editData);

		return data;
	}

}
----

[[viewaggregation]]
=== 表示方法
Aggregationはメニューとして登録する方法と、TopViewへ表示させる方法の2パターンが存在します。

==== メニューへの登録
集計画面を表示するにはメニューにActionMenuItemを登録します。
ActionMenuItemには雛型として `gem/template/aggregation/ViewAggregationAction` というメニューアイテムがあります。
このActionMenuItemをコピーしてメニューアイテムを編集してください。

[cols="2,9a", options="header"]
|===
|項目
|設定値
|Name|管理しやすいように設定してください。
|DisplayName|メニューの表示名になります。
|Execute Action| `gem/aggregation/unit/viewAggregation` を指定してください。
|Parameter| 集計定義名(必須)とデフォルト検索条件を設定することができます。 +
`defName=XXX&doFilterAggregation=true&xxxConditionCount=2&xxx_ope_0=GT&xxx_0=999`
|===

.デフォルト検索条件のパラメータ
デフォルト検索条件は必要に応じて設定してください。

[cols="2,9a", options="header"]
|===
|項目
|設定値
|doFilterAggregation
|trueの場合表示時にフィルタ条件を適用、falseまたは未指定の場合はフィルタ条件を適用せず集計します。

|xxxConditionCount
|同一の項目で複数の条件を指定する場合の件数を指定、未指定の場合は1

.18+|xxx_ope_y
|フィルタ時の比較演算子、指定できるのは以下となります。

|EQ: 等しい
|NE: 等しくない
|SW: 前方一致
|LW: 後方一致
|IC: 含む
|NIC: 含まない
|IN: いずれかと等しい
|LT: より小さい
|GT: より大きい
|LE: 以下
|GE: 以上
|RG: 範囲指定範囲指定の場合のみ下記のようにtoパラメータが必要となります。
|RD: 相対範囲(日付)
|RDT: 相対範囲(日時)
|NNL: 値が設定されている
|NL: 値が設定されていない
|SL: 保存リストから

|xxx_y
|フィルタ時の値、型によって指定の際の制約あり

Boolean型:: trueまたはfalse
Date型:: yyyyMMdd形式
Datetime型:: yyyyMMddHHmmss形式
Reference型:: エンティティのOID
Select型:: SelectValueのvalue値
Time型:: HHmmss形式
|===

xxxはプロパティ名、集計定義のフィルタ設定のプロパティ定義名をそのまま設定(参照先の項目等は.付きで)
yはインデックス（同一項目で複数指定の場合に注意）、0から指定して下さい。

例）2000～6000の範囲内という条件の場合
====
integer001_ope_0=RG&integer001_0=2000&integer001_to_0=6000
====

[[viewaggregationparts]]
==== Top画面での表示
TopView定義に単一集計パーツを配置することでTop画面に表示することができます。
[cols="1,2a", options="header"]
|===
|設定項目
|設定内容

|Icon Tag
|Font Awesomeによるアイコンタグを設定します。

|Class
|スタイルシートのクラス名を指定します。複数指定する場合は半角スペースで区切って下さい。

|Max Height
|コンテンツ部分の最大高さを指定します。
指定した高さを超える場合はスクロールバーが表示されます。未指定の場合は高さ制限はありません。

|show Link for aggregation detail view
|集計画面へのリンクを表示したい場合にチェックします。

|override Aggregation setting
|以下の4項目についてAggregationでの設定を上書きした状態でTOP画面に表示したい場合にチェックします。
Aggregation定義の設定が更新されるわけではありません。

|show Grid
|集計表の表示、非表示を設定します。

|show Graph
|グラフの表示、非表示を設定します。

|show Graph on the first
|グラフを集計表の上に表示するか設定します。

|show horizontal tables and Graphs
|集計表とグラフを横に並べて表示するかを設定します。
|===
