plugins {
	id "org.asciidoctor.jvm.convert" version '4.0.5' apply false
}
apply plugin: 'base'

defaultTasks = ['clean', 'asciidoctor']

def asciidocLangValue = providers.gradleProperty("asciidoc_lang").get()

allprojects {
	repositories {
		mavenCentral()
	}

	apply plugin: "project-report"
	apply plugin: "org.asciidoctor.jvm.convert"

	asciidoctorj {
		version = '2.5.11'
	}

	asciidoctor {
		sources {
			include "**/index.adoc"
		}
		resources {
			from(sourceDir) {
				include "**/images/**"
				include "NOTICE"
			}
		}

		parallelMode = false
		outputOptions {
			separateOutputDirs = false
			backends = ["html5"]
		}
		logDocuments = true
		baseDirFollowsSourceFile()
		attributes "_buildLang": asciidocLangValue
	}

	build {
		dependsOn tasks.named('asciidoctor')
	}
}

subprojects {
	asciidoctor {
		//サブプロジェクトはサブプロジェクトフォルダ配下に生成
		outputDir = file("${rootDir}/build/asciidoc/${asciidocLangValue}/${project.name}")
		attributes "_relative-root-path": "../@"
	}
}

asciidoctor {
	outputDir = file("${rootDir}/build/asciidoc/${asciidocLangValue}")
	attributes "_relative-root-path": "./@"
}
