[[aggregation_management]]
== 集計の管理

[[create_aggregation]]
=== Aggregationの作成
Aggregationアイコンを右クリックして `集計情報を作成する` を選択してください。
集計タイプ（Cube）を選択してください。

[[aggregation_setting]]
=== 設定

[[aggregation_common_setting]]
==== 共通項目
設定可能な項目は下記となります。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|集計タイプ
|集計タイプを選択します。

Cube:: 動的集計、Entityのデータを集計、表やグラフを表示する

Simple及びCrosstabについては<<../aggregation/index.adoc#, 定型集計>>を参照してください。

|Cube定義名
|集計対象のCubeを選択します。

|集計を特権で行う
|権限設定に関わらず集計を行いたい場合にチェックします。
集計対象エンティティの参照権限がないユーザーにも集計結果の閲覧を許可したい場合等に利用します。

|初期表示時にグラフと集計表を表示しない
|初期表示時ではなく、検索ボタン押下時に初めてグラフと集計表を表示するようにしたい場合にチェックします。
ただし、フィルタ項目が1件以上設定されている必要があります。

|集計結果を表示する
|集計結果の表を表示したい場合にチェックします。
グラフは表示したいが、結果表は表示したくない、また逆の場合に利用します。

|グラフと集計表を並べて表示
|集計表とグラフを横に並べて表示したい場合にチェックします。
集計結果、グラフともに表示設定されている事が前提です。
`集計表の上にグラフを表示する` がチェックされている場合は、 `右：グラフ、左：集計表` になります。

|ファイルダウンロードを許可する
|この設定にチェックを入れると、集計画面でファイルダウンロードボタンが表示されます。

|File type
|ダウンロードで利用するファイル形式を指定します。

CSV::
CSVファイルを利用します。

EXCEL::
EXCELファイルを利用します。

SPECIFY::
CSVファイルかEXCELファイルのどちらを利用するかを画面で選択します。

未指定の場合は、<<../../serviceconfig/index.adoc#EnterpriseGemConfigService,EnterpriseGemConfigService>> の `aggregationFileSupportType` によって動作します。


|File name format
|ファイルダウンロード時のファイル名をGroovyTemplate書式を利用して指定します。
詳細は<<ag_filenameformat, File name format>>を参照してください。

|保存リストを使用する
|未選択の場合、フィルター条件と結果の絞り込みの「保存リストから」を選択不可になります。
編集画面に「保存」ボタンとローデータメニューの「リストに保存」は表示されません。

|フィルタ項目|
集計画面で利用可能なフィルタ項目を設定します。
詳細は<<ag_filter, フィルタ項目>>を参照してください。

|Edit default filter
|フィルターの初期条件を設定するスクリプトを記述できます。
詳細は<<ag_editdefaultfilter, Edit default filter>>を参照してください。

|Edit JavaScript Code
|集計画面内で実行するJavaScriptを設定できます。
|===

[[ag_filenameformat]]
.File name format
ファイルダウンロード時のファイル名をGroovyTemplate書式を利用して指定します。
フォーマットが指定されている場合、ボタンに `(*)` が表示されます。
/とスペースについては、_（アンダースコア）に変換します。

利用可能なバインド変数は、編集ダイアログの `Notes` を参照してください。

.（例）ファイル名の後ろに出力時の時間を付加する。
[source,groovy]
----
${csvName}_${yyyy}${MM}${dd}${HH}${mm}${ss}
----

.（例）保存リストの場合は保存名を先頭に付加する。
[source,groovy]
----
<%
def fileName = defDisplayName;
if (savedListName != null) {
    fileName = savedListName + "_" + defDisplayName;
}
%>
${fileName}_${yyyy}${MM}${dd}${HH}${mm}${ss}
----

[[ag_filter]]
.フィルタ項目
集計画面で利用可能なフィルタ項目を設定します。
画面右側にある `Properties` より、フィルタ項目としたいPropertyをフィルタ項目表内部にドラッグ&ドロップします。
フィルタ項目のドラッグ&ドロップ後、対象フィルタ項目の右の鉛筆マークをクリックする事で下記設定が可能になります。

[cols="1,2a", options="header"]
|===
|項目
|設定値

|プロパティ表示名
|フィルタ項目としての表示名を指定します。

|表示タイプ
|プルダウン選択時は下部にある `追加` ボタンをクリックし、選択値を設定する必要があります。
プルダウンはプロパティの型によって設定できる項目が変化します。

|選択値
|表示タイプでプルダウンを選択した場合に、表示名値をそれぞれ設定します。
|===

また、必須列にある鉛筆マークをクリックすると、フィルタ条件を必須項目にするかを指定できます。
必須項目にした場合、さらに利用可能な比較演算子演算子を指定できます。
なお、フィルタ条件の型により、予め利用可能な比較演算子は決まっています。
利用できない比較演算子を選択した場合、集計画面では表示されません。

[[ag_editdefaultfilter]]
.Edit default filter
フィルターの初期条件を設定するスクリプトを記述できます。
設定内容については<<viewaggregation, 表示方法>>を参考にしてください。

以下はスクリプトの記述例になります。
バインドされているマップにキーと値を設定します。

[source,groovy]
----
initCondMap.put("doFilterAggregation", "true");
initCondMap.put("point_ope_0", "LE");
initCondMap.put("point_0", "50");
----

[[aggregation_cube_setting]]
==== キューブ集計
.CubeItem設定
Cube集計で使用するItemに関する設定です。
Cube集計の設定画面右上に利用可能なItemがツリー形式で表示されています。
編集アイコンをクリックすることで、ツリーの内容及び各Item（ノード）の設定を編集することができます。

[cols="1,5a", options="header"]
|===
|設定項目
|設定値

|子ノードを追加
|選択したノードをフォルダ化し、子ノードを追加します。

|ノードを編集
|ノードの編集ダイアログを表示します。
詳細は<<edit_cubeitem, ノードを編集>>を参照してください。

|ノードを削除
|ツリーからノードを削除します。
ダイアログ左側の一覧からドラッグすることでツリーに再設定できます。
独自に追加した子ノードやフォルダについては手動で再設定してください。

|フォルダ追加
|選択したノードをフォルダ化し、子フォルダを追加します。

|フォルダ化
|ノードをフォルダ化します。
|===

[[edit_cubeitem]]
.ノードを編集
ノードの編集ダイアログを表示します。

[cols="1,5a", options="header"]
|===
|設定項目
|設定値

|表示名
|集計画面に表示する際の名前を設定します。
未指定時はキューブアイテムの表示名を利用します。

|値式
|対象アイテムの物理名（エンティティのプロパティ名）を指定します。

|フォーマッタ
|集計表に表示する際の数値のフォーマッタを指定します。
未指定、整数、小数の中から選択します。

|配置
|集計表に表示する際の数値の配置を指定します。
未指定、左寄せ、中央寄せ、右寄せの中から選択します。

|列幅
|集計表に表示する際の列の幅を指定します。
|===

以下の項目はCube設定でディメンションタイプを `EntityReference` にした場合のみ表示される項目です。

[cols="1,5a", options="header"]
|===
|設定項目
|設定値

|表示タイプ
|表示タイプを指定します。

|リストのフィルタ条件
|EQLのWhere句のみ記述してください。
Whereは不要です。
表示タイプがプルダウンの場合のみ有効です。

|ソート種別
|昇順か降順を選択してください。
表示タイプがプルダウンの場合のみ有効です。

|ソートアイテム
|ソート対象とするアイテムを選択してください。
表示タイプがプルダウンの場合のみ有効です。

|ビュー名
|リンククリック後に表示する画面のビュー名を指定してください。
表示タイプがリンクの場合のみ有効です。

|選択アクション
|リンククリック時に実行するアクションを選択してください。
表示タイプがリンクの場合のみ有効です。

|URLパラメータ
|リンククリック時に実行するアクションに渡すパラメータを指定してください。
表示タイプがリンクの場合のみ有効です。
|===

.Custom Mesure設定
既存のCubeItemを関数と組み合わせて、独自の集計項目を作成することが出来ます。
作成した集計項目は集計表設定の集計項目にドラッグ&ドロップで設定することが出来ます。

また、式内にCubeItem名ではなく置換用文字列 `{1}` を指定すると、独自の関数を作成することが出来ます。
この関数は集計項目の設定画面で集計関数として選択することが出来ます。

[cols="1,5a", options="header"]
|===
|設定項目
|設定値

|表示名
|Custom Measureの名前を設定します。

|式
|CubeItemや関数を組み合わせた数式を設定します。
詳細については下部にあるヘルプを参照してください。

|フォーマッタ
|集計表に表示する際の数値のフォーマッタを指定します。
未指定、整数、小数の中から選択します。

|配置
|集計表に表示する際の数値の配置を指定します。
未指定、左寄せ、中央寄せ、右寄せの中から選択します。
|===


.集計表設定、表示設定
集計表設定では左側の一覧に集計軸（ディメンション）を、右側の一覧に集計項目（メジャー）を設定します。
表示設定では表やグラフの表示に関する設定を行います。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|表示タイプ
|表示タイプを選択します。
ここで設定した内容が汎用画面での集計表示時にデフォルト表示となります。

単純集計、クロス集計、折れ線グラフ、棒グラフ、円グラフ、ドーナツグラフ、バブルチャート、散布図、ピラミッド、レーダーチャート、ローデータが選択できます。

単純集計、クロス集計、ローデータはグラフ表示されません。

|デフォルトフィルタ条件
|集計実行時に画面上のフィルタ条件とは別に付与される条件です。
EQL形式で設定します。
|===

===== 単純集計
.集計表設定
単純集計の集計表設定で設定可能な項目です。

[cols="1,1,3a", options="header"]
|===
|設定項目
|タイプ
|設定値

|集計軸
|ディメンション
|集計する軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|集計項目
|メジャー
|集計する項目を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|ソート項目
|
|表示タイプ切り替え時のデフォルトソート項目を設定します。
集計軸、集計項目に設定されたアイテムが選択できます。

|ソート種別
|
|表示タイプ切り替え時のデフォルトソート種別(ASC、DESC)を設定します。
|===

.表示設定
単純集計の表示設定で設定可能な項目です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|同じ値のセルをまとめる
|列内の同じ値のセルをまとめ、一つのセルにします。
複数列ある場合は左から順にまとめますが、同じ値でも左側の列がまとまっていない場合はセルはまとめません。

|合計を表示する
|集計項目の合計値を表示します。
|===

===== クロス集計
.集計表設定
クロス集計の集計表設定で設定可能な項目です。

[cols="1,1,3a", options="header"]
|===
|設定項目
|タイプ
|設定値

|表頭
|ディメンション
|表頭を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|表側
|ディメンション
|表側を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|系列1
|ディメンション
|系列1を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
系列1を設定すると、系列毎のクロス集計表が作成されます。

|集計項目
|メジャー
|集計項目を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|ソート項目
|
|表示タイプ切り替え時のデフォルトソート項目を設定します。
表頭、表側、系列1、集計項目に設定されたアイテムが選択できます。

|ソート種別
|
|表示タイプ切り替え時のデフォルトソート種別(ASC、DESC)を設定します。
|===

.表示設定
クロス集計の表示設定で設定可能な項目です。
[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|フォーマッタ
|集計表に表示する際の数値のフォーマッタを指定します。
未指定、整数、小数の中から選択します。

|配置
|集計表に表示する際の数値の配置を指定します。
未指定、左寄せ、中央寄せ、右寄せの中から選択します。

|列幅
|集計表に表示する際の列の幅を指定します。

|項目のラベルを非表示
|表頭及び表側に集計項目のラベルを表示するかを設定します。
|===

===== 折れ線/棒グラフ
.表設定
折れ線/棒グラフの集計表設定で設定可能な項目です。

[cols="1,1,3a", options="header"]
|===
|設定項目
|タイプ
|設定値

|X軸
|ディメンション
|X軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|系列1
|ディメンション
|系列1を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
系列1を設定すると、グラフ内のデータを系列化して表示します。

|系列2
|ディメンション
|系列2を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
系列2を設定すると、系列毎のグラフが作成されます。

|Y軸1
|メジャー
|Y軸1を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|Y軸2
|メジャー
|Y軸2を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|ソート項目
|
|表示タイプ切り替え時のデフォルトソート項目を設定します。
X軸、系列1、系列2、Y軸1、Y軸2に設定されたアイテムが選択できます。

|ソート種別
|
|表示タイプ切り替え時のデフォルトソート種別(ASC、DESC)を設定します。
|===

.表示設定
折れ線/棒グラフの表示設定で設定可能な項目です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|同じ値のセルをまとめる
|列内の同じ値のセルをまとめ、一つのセルにします。
複数列ある場合は左から順にまとめますが、同じ値でも左側の列がまとまっていない場合はセルはまとめません。

|グラフ高さ
|グラフ表示時の高さを指定します。
単位はpx固定です。
数値のみの入力となります。

|グラフ幅
|グラフ表示時の幅を指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。

（入力例： `800`、 `800px` または `50%`）

|値表示方法
|集計項目の値の表示方法を以下の3パターンから選択します。

`非表示` 、 `常に表示` 、 `マウスオーバー時`

|積み上げグラフ
|棒グラフの時のみ有効です。

|割合グラフで表示
|積み上げグラフを各項目の値ではなく、項目の合計値に対する割合で表示します。

|トレンドラインを表示
|棒グラフの時のみ有効です。

|系列を分けるか
|系列ごとにグラフを表示可能になります。

|棒グラフの幅
|グラフ表示時の棒グラフの幅を指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。
数値のみの入力となります。

|棒グラフのパディング
|グラフ表示時の棒グラフのパディングを指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。
数値のみの入力となります。

|棒グラフのマージン
|グラフ表示時の棒グラフのマージンを指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。
数値のみの入力となります。

|項目のラベルを非表示
|軸に表示しているラベルを表示しない場合にチェックします。

|各バーに異なる色を使用
|棒グラフで同じ色を使わず、異なる色を使うようにします。

|色の設定
|グラフの各要素に使われる色を設定します。
未指定時はデフォルトの色が適用されます。

|nullを0に変換
|軸1、軸2に指定された項目の値で、データがnullのものを0として扱います。
nullのままの場合、グラフ上には表示されません。

|凡例を非表示
|凡例を表示しない場合にチェックします。


|凡例の表示位置(Placement)
|凡例の表示位置を以下の2パターンから選択します。

`内側` 、 `外側`

|凡例の表示位置(location)
|凡例の表示位置を以下の8パターンから選択します。

`左上` 、 `上` 、 `右上` 、 `右` 、 `右下` 、 `下` 、 `左下` 、 `左`

|凡例の行数
|凡例の行数を指定します。

|凡例の列数
|凡例の列数を指定します。

|X軸のラベルの傾き
|X軸のラベルの傾きを指定します。
単位は角度です。
数値のみの入力となります。

|X軸のラベルの表示位置
|X軸のラベルの表示位置を以下の3パターンから選択します。
目盛りの中心に選択したラベルの位置が調整されます。

`ラベルの先頭` 、 `ラベルの中央` 、 `ラベルの末尾`

|線グラフの種類
|軸1の設定のグラフタイプが棒グラフの場合のみ設定可能です。
以下の2パターンから選択します。

`カテゴリ` 、 `数値`

|数値フォーマット
|集計項目の数値の表示方法を以下の3パターンから選択します。

`未指定` 、 `整数` 、 `小数`

|小数の桁数
|数値フォーマットで `小数` を選択した場合の必須項目です。

|X軸の最大値|X軸の最大値を指定します。
数値を入力します。
線グラフの種類が `数値` の場合に入力可能です。

|X軸の最小値|X軸の最小値を指定します。
数値を入力します。線グラフの種類が `数値` の場合に入力可能です。

|目盛りの数
|目盛りの数を指定します。
数値を入力します。
線グラフの種類が `数値` の場合に入力可能です。

|グリッド線を非表示
|グリッド上に表示されている線を表示しない場合にチェックします

|Y軸1の最大値
|Y軸1の最大値を指定します。数値を入力します。

|Y軸1の最小値
|Y軸1の最小値を指定します。数値を入力します。

|Y軸1の刻み幅
|Y軸1の刻み幅を指定します。
数値を入力します。
2軸設定をした場合には有効になりません。

|曲線で表示
|線を曲線する場合にチェックします。
グラフタイプが `線グラフ` の場合のみ指定できます。

|Y軸2の最大値
|Y軸2の最大値を指定します。
数値を入力します。

|Y軸2の最小値
|Y軸2の最小値を指定します。
数値を入力します。

|グラフタイプ
|Y軸2のグラフタイプを選択します。

|基準線を表示
|基準線の設定で設定した内容をグラフ上に表示する場合にチェックします
|===

Y軸2を設定した場合、軸1のY軸はグラフ左側に、軸2のY軸はグラフ右側に表示されます。

===== 円
.集計表設定
円グラフの集計表設定で設定可能な項目です。

[cols="1,1,3a", options="header"]
|===
|設定項目
|タイプ
|設定値

|X軸
|ディメンション
|X軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|系列1
|ディメンション
|系列1を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
系列1を設定すると、系列毎のクロス集計表が作成されます。

|集計項目
|メジャー
|集計項目を設定します。CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|ソート項目
|
|表示タイプ切り替え時のデフォルトソート項目を設定します。
X軸、系列1、集計項目に設定されたアイテムが選択できます。

|ソート種別
|
|表示タイプ切り替え時のデフォルトソート種別(ASC、DESC)を設定します。
|===

.表示設定
円グラフの表示設定で設定可能な項目です。
下記以外については折れ線/棒グラフを参照してください。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|円に表示するラベル
|円グラフでデータを表示する際の表示方法を設定します。
|===

===== ドーナツグラフ
.集計表設定
ドーナツグラフの集計表設定で設定可能な項目です。

[cols="1,1,3a", options="header"]
|===
|設定項目
|タイプ
|設定値

|X軸
|ディメンション
|X軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|系列1
|ディメンション
|系列1を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
系列1を設定すると、グラフ内のデータを系列化して表示します。

|系列2
|ディメンション
|系列2を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
系列2を設定すると、系列毎のグラフが作成されます。

|集計項目
|メジャー
|集計項目を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|ソート項目
|
|表示タイプ切り替え時のデフォルトソート項目を設定します。
X軸、系列1、系列2、集計項目に設定されたアイテムが選択できます。

|ソート種別
|
|表示タイプ切り替え時のデフォルトソート種別(ASC、DESC)を設定します。
|===

.表示設定
ドーナツグラフの表示設定で設定可能な項目です。
下記以外については折れ線/棒グラフを参照してください。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|円に表示するラベル
|円グラフでデータを表示する際の表示方法を設定します。
|===

===== バブルチャート
.集計表設定
バブルチャートの集計表設定で設定可能な項目です。

[cols="1,1,3a", options="header"]
|===
|設定項目
|タイプ
|設定値

|X軸
|メジャー
|X軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|Y軸
|メジャー
|Y軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|Z軸
|メジャー
|Z軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|ラベル
|ディメンション
|ラベルを設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|系列
|ディメンション
|系列を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|ソート項目
|
|表示タイプ切り替え時のデフォルトソート項目を設定します。
ラベル、系列、X軸、Y軸、Z軸に設定されたアイテムが選択できます。

|ソート種別
|
|表示タイプ切り替え時のデフォルトソート種別(ASC、DESC)を設定します。
|===

.表示設定
バブルチャートの表示設定で設定可能な項目です。
下記以外については折れ線/棒グラフを参照してください。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|ラベルを非表示
|バブルのラベルを非表示にするかを設定します。

|倍率
|Ｚ軸の大きさの倍率を入力します。
未指定の場合は1となります。
|===

===== 散布図
.集計表設定
散布図の集計表設定で設定可能な項目です。
[cols="1,1,3a", options="header"]
|===
|設定項目
|タイプ
|設定値

|X軸
|メジャー
|X軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|Y軸
|メジャー
|Y軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|ラベル
|ディメンション
|ラベルを設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|系列
|ディメンション
|系列を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|ソート項目
|
|表示タイプ切り替え時のデフォルトソート項目を設定します。
ラベル、系列、X軸、Y軸に設定されたアイテムが選択できます。

|ソート種別
|
|表示タイプ切り替え時のデフォルトソート種別(ASC、DESC)を設定します。
|===

.表示設定
散布図の表示設定で設定可能な項目については折れ線/棒グラフを参照してください。

===== ピラミッド
.集計表設定
ピラミッドの集計表設定で設定可能な項目です。

[cols="1,1,3a", options="header"]
|===
|設定項目
|タイプ
|設定値

|集計軸
|ディメンション
|集計軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|対比項目
|ディメンション
|対比項目を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|系列
|ディメンション
|系列を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|集計項目
|メジャー
|集計項目を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|ソート項目
|
|表示タイプ切り替え時のデフォルトソート項目を設定します。
集計軸、対比項目、系列、集計項目に設定されたアイテムが選択できます。

|ソート種別
|
|表示タイプ切り替え時のデフォルトソート種別(ASC、DESC)を設定します。
|===

.表示設定
ピラミッドの表示設定で設定可能な項目です。
下記以外については折れ線/棒グラフを参照してください。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|棒グラフの幅
|グラフ表示時の棒グラフの幅を指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。
数値のみの入力となります。

|棒グラフのパディング
|グラフ表示時の棒グラフのパディングを指定します。
単位はpxか%です。
省略した場合の単位はpxとなります。
数値のみの入力となります。

|2目盛り毎に色分け
|ピラミッドの背景を2目盛り毎に色分けするかを設定します。

|刻み幅
|刻み幅を指定します。数値を入力します。
|===

===== レーダーチャート
.集計表設定
レーダーチャートの集計表設定で設定可能な項目です。

[cols="1,1,3a", options="header"]
|===
|設定項目
|タイプ
|設定値

|項目
|ディメンション
|項目を設定します。
CubeItemからドラッグ&ドロップで設定可能です。

|数値軸
|メジャー
|数値軸を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
鉛筆マークをクリックする事で関数の利用が可能です。

|系列1
|ディメンション
|系列1を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
系列1を設定すると、グラフ内のデータを系列化して表示します。

|系列2
|ディメンション
|系列2を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
系列2を設定すると、系列毎のグラフが作成されます。

|ソート項目
|
|表示タイプ切り替え時のデフォルトソート項目を設定します。
項目、数値軸、系列1、系列2に設定されたアイテムが選択できます。

|ソート種別
|
|表示タイプ切り替え時のデフォルトソート種別(ASC、DESC)を設定します。
|===

.表示設定
レーダーチャートの表示設定で設定可能な項目については折れ線/棒グラフを参照してください。

===== ローデータ
.集計表設定
ローデータの集計表設定で設定可能な項目です。
[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|項目
|項目を設定します。
CubeItemからドラッグ&ドロップで設定可能です。
|===

.表示設定
ローデータの表示設定で設定可能な項目はありません。

.ローデータ設定
全表示タイプで共通です。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|raw data get limit
|ローデータ取得上限。表示タイプがローデータの際の取得件数の上限です。

|distinct raw data
|重複データを１つにまとめて出力します。

|raw data with name
|Selectプロパティの出力を名称で出力するかコードで出力するかを指定します。

|allow the select of [show with name]
|Selectプロパティの出力を名称で出力するかコードで出力するかをユーザーが指定可能にします。

|allow the output of raw data
|ローデータの出力許可。集計表やグラフからローデータの取得が可能となります。 集計表で出力したい行やセルを選択（複数選択可）し、右クリックでコンテキストメニューを開きます。
グラフの場合は対象のデータをクリックして選択し、右クリックでコンテキストメニューから出力します。

|File type
|ダウンロードで利用するファイル形式を指定します。

CSV::
CSVファイルを利用します。

EXCEL::
EXCELファイルを利用します。

SPECIFY::
CSVファイルかEXCELファイルのどちらを利用するかを画面で選択します。

未指定の場合は、<<../../serviceconfig/index.adoc#EnterpriseGemConfigService,EnterpriseGemConfigService>> の `aggregationRawdataFileSupportType` によって動作します。


|File name format
|ファイルダウンロード時のファイル名をGroovyTemplate書式を利用して指定します。
詳細は<<ag_filenameformat, File name format>>を参照してください。

|File multiple format
|ファイルダウンロード時の多重度が複数のプロパティの出力形式を指定します。

Each Column::
多重度の数分別々の列に出力します。

One Column::
１つの列にカンマ区切りでまとめて出力します。

One Column Fill Null::
１つの列にカンマ区切りでまとめて出力します。
登録データが多重度分保存されていない場合にも多重度分空を補完します。

|raw data item
|操作可能な項目。CubeItemからローデータ出力したいものをドラッグ&ドロップして下さい。
出力項目のラベル、多重度についてはCubeItemの設定が参照されます。
|===

[[viewaggregation]]
=== 表示方法
Aggregationはメニューとして登録する方法と、TopViewへ表示させる方法の2パターンが存在します。

詳細については定型集計の<<../aggregation/index.adoc#viewaggregation, 表示方法>>を参照してください。