:cubeservice: ../../serviceconfig/index.html#CubeService

[[cube]]
== Cubeの管理
集計表やグラフに利用する各項目を設定する機能です。
作成したCubeはAggregationから利用します。

[[create_cube]]
=== Cubeの作成
Cubeアイコンを右クリックして `キューブを作成する` を選択してください。
作成時にCubeで利用する集計元データのタイプを選択してください。


[[cube_setting]]
=== 設定

[[cube_commonsetting]]
==== 共通項目
設定可能な項目は下記となります。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|キューブタイプ
|CSV、Entity、JDBC、Derivedから選択します。
CSV、JDBCについては<<{cubeservice}, CubeService>>の `enablePhysicalResourceLoading` をtrueに設定する必要があります。

|パーティションタイプ
|Cubeでの集計対象データをメモリに展開する際の取得条件となります。

Hash:: ハッシュ値を利用してパーティショニングします。
Mod:: パーティショニングアイテムが数値型の場合のみ利用可能です。
List:: 複数のパーティションにそれぞれ対応する値を設定します。

|パーティショニングアイテム名
|Cubeでの集計対象データをメモリに展開する際の取得条件となります。
画面下部のCubeItemが選択可能となります。

|スケール
|Cubeでの集計対象データをメモリに展開する際の取得条件となります。
Modの時のみ必須項目です。
剰余をするスケールを設定します。

-1:: 10の位でMOD
0:: 1の位でMOD
1:: 小数第一位でMOD

|サイズ
|Cubeでの集計対象データをメモリに展開する際の取得条件となります。
パーティションの総数を指定します。
1以上を指定して下さい。

|Cube(Reference)
|既に登録済のCubeのアイテムを各集計タイプのCubeItemとして利用します。
`EntityとCSVをくっつけたCubeを作りたい` 、 `関連のないEntity同士をくっつけてCubeを作りたい` と言った場合を想定しています。

CubeReferenceを利用する場合は、アプリ側で事前に参照先のCubeがロードされていることが前提となります。

|自動ロードするか
a|Cube表示時に最新データを自動的にロードする場合はチェックを入れます。

実際に利用する際は、なるべく自動ロードは使わず、アプリ側でロードする時間（毎朝5:00など）を決め、バッチ等で事前にロードするような運用を推奨します。
アプリによるロード運用ができない場合に、本項目にチェックを入れることで自動的にデータを読み込みます。

<<cube_entitysetting,Entityタイプの設定>> 「対象データをメモリにロード」にチェックがある場合は、データをメモリへのロードが必要となります。

|リロード間隔(秒)
|Cubeのデータを自動リロードする間隔（秒）を指定します。
デフォルトは0（自動リロードしない）です。

Cubeデータをメモリにロードしている場合に有効になります。
(メモリロードをサポートしているキューブタイプの場合のみ対象になります。)

|===

[[cube_csvsetting]]
==== Csv
キューブタイプでCSVを選択した際の設定です。
指定されたパスにあるCSVファイル内のデータを利用します。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|CSV格納先
|FILEかLOBを選択します。
FILEの場合は設置場所のパスを、LOBの場合は対象エンティティのプロパティ及び検索条件を指定する必要があります。

|CSVヘッダー有
|対象CSVファイルにヘッダ行がある場合にチェックします。

|Date Format
|日付型データのフォーマットパターンを指定します。
java.time.format.DateTimeFormatter形式で指定します。

指定例： uuuu-MM-dd

未指定でも日付データの読み込みは可能ですが、指定したほうが読み込み速度は向上します。

|Time Format
|時刻型データのフォーマットパターンを指定します。
java.time.format.DateTimeFormatter形式で指定します。

指定例： HH:mm:ss

未指定でも時刻データの読み込みは可能ですが、指定したほうが読み込み速度は向上します。

|DateTime Format
|日時型データのフォーマットパターンを指定します。
java.time.format.DateTimeFormatter形式で指定します。

指定例： uuuu-MM-dd[ HH:mm:ss][XXXXX]

未指定でも日時データの読み込みは可能ですが、指定したほうが読み込み速度は向上します。

|格納先パス
|CSV格納先がFILEの場合に指定します。
CSVファイルの配置場所を指定します。

====
D:\data\test.csv
====

|再帰検索有
|CSV格納先がFILEの場合に指定します。
フォルダ内を再帰的に検索します

|Entity名
|CSV格納先がLOBの場合に指定します。
CSVファイルを格納しているエンティティを選択します。

|Property名
|CSV格納先がLOBの場合に指定します。
CSVファイルを格納しているプロパティを選択します。

|検索条件
|CSV格納先がLOBの場合に指定します。
CSVファイルが格納されているデータが一意になる検索条件を指定します。

|パーティション項目値を格納しているプロパティ名
|プロパティ名を選択した場合、当該のプロパティにパーティション対象の項目値が格納されているものとして、データのロード処理を最適化します。

|Cube Items
|Addボタンをクリックし、CSVファイルの項目に対応する名前を設定します。
ここに追加したプロパティがAggregation設定時に利用可能となり、最終的に集計画面で集計可能項目となります。
|===

.Cube Item設定
[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|名前
|CubeItemの名前を指定します。

|表示ラベル
|画面に表示するラベルを指定します。

|データタイプ
|データの型を指定します。
|===

[[cube_entitysetting]]
==== Entity
キューブタイプでEntityを選択した際の設定です。
指定されたEntityのデータを利用します。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|対象Entity名
|Cube対象Entityを選択します。
ここで選択したEntityのプロパティが画面右側の `Properties` に表示されます。
表示されたプロパティは画面下部のCube Itemsテーブルにドラッグ可能となります。

|参照節
|取得条件の参照節をEQLにて記述します。
参照節とは参照時の結合条件となります。QueryのJavaDocを参照下さい。

|Where条件
|取得条件のWhere句をEQLにて記述します。

|GroupBy
|取得条件のGroupBy句をEQLにて記述します。

|Having条件
|取得条件のHaving句をEQLにて記述します。

|重複行をまとめる
|重複行が存在した場合に1行にまとめます。

|対象データをメモリにロード
a|集計に使用するデータをメモリにロードする場合に設定します。 +
<<cube_commonsetting,共通項目>>「自動ロードするか」も参照してください。

|Cube Items
|画面右側のPropertiesからプロパティをドラッグします。
ここに追加したプロパティがAggregation設定時に利用可能となり、最終的に集計画面で集計可能項目となります。
|===

.Cube Item設定
[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|名前
|CubeItemの名前を指定します。

|表示ラベル
|画面に表示するラベルを指定します。

|値式
|エンティティのプロパティ名や数式を利用した値式を設定します。

|データタイプ
|データの型を指定します。

|多重度
|アイテムの多重度を設定します。
ドロップ時に対象のProperty設定から初期値が自動的に設定されます。

多重度が1以外の場合、Aggregationで表示タイプが `ローデータ` 以外の場合に、集計項目として設定できなくなります。

|カーディナリティ
|プロパティの値の種類の度合いを設定します。
種類が少ない程低く（Low）、多いほど高く（High）なります。

|ディメンション
|軸の要素としての種類を設定します。

データの型に併せて以下から選択します。

Generic:: 汎用的に使用できるディメンション
DateTime:: 日時や日付で使用できるディメンション
EntityReference:: 参照型で使用できるディメンション
Select:: 選択型で使用できるディメンション

|ギャップを埋める
|このディメンジョンのギャップを補完するかを指定します。

例えば、「1,3,5」というディメンジョン値があった場合、「1,2,3,4,5」というように補完します。

|ラベル値で補間
|ギャップ補間をラベルにセットされている値を利用して行うかを指定します。

|最小値
|ギャップ補間時の最小値を設定します。

|最大値
|ギャップ補間時の最大値を設定します。

|インターバル
|ギャップ補間時の間隔を設定します。

|ラベル
|このディメンションの値に対してラベルを設定します。
|===

[[cube_jdbcsetting]]
==== JDBC
キューブタイプでJdbcを選択した際の設定です。
SQLで直接データベースからデータを取得します。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|SQL
|Cubeとして利用したデータの検索用SQLを設定します。
EQLではなくSQLとなります。

|接続ファクトリ名
|ServiceConfigに設定してあるRdb Connection Settingsのinterfaceを指定します。

|重複行をまとめる
|重複行が存在した場合に1行にまとめます。

|対象データをメモリにロード
|集計に使用するデータをメモリにロードする場合に設定します。

|Cube Items
|Addボタンをクリックし、SQLのSELECT項目に対応する名前を設定します。
ここに追加したプロパティがAggregation設定時に利用可能となり、最終的に集計画面で集計可能項目となります。
|===

.Cube Item設定
[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|名前
|CubeItemの名前を指定します。

|表示ラベル
|画面に表示するラベルを指定します。

|テーブルのカラム名(またはその値式)
|SQLに指定したSELECT句のカラム名、または値式を指定します。

|データタイプ
|データの型を指定します。
|===

[[cube_derivedsetting]]
==== Derived
キューブタイプでDerivedを選択した際の設定です。
他のキューブをデータソースとして利用します。

[cols="1,4a", options="header"]
|===
|設定項目
|設定値

|対象Cube名
|対象のCubeを選択します。
ここで選択したCubeのCubeItemが画面右側の `CubeItem` に表示されます。
表示されたCubeItemは画面下部のCube Itemsテーブルにドラッグ可能となります。

|参照節
|取得条件の参照節をEQLにて記述します。
参照節とは参照時の結合条件となります。
詳細は<<../../eqlreference/index.adoc#, EQL Reference>>を参照してください。

|Where条件
|取得条件のWhere句をEQLにて記述します。

|GroupBy
|取得条件のGroupBy句をEQLにて記述します。

|Having条件
|取得条件のHaving句をEQLにて記述します。

|重複行をまとめる
|重複行が存在した場合に1行にまとめます。

|対象データをメモリにロード
|集計に使用するデータをメモリにロードする場合に設定します。

|Cube Items
|画面右側のCubeItemからプロパティをドラッグします。
ここに追加したCubeItemがAggregation設定時に利用可能となり、最終的に集計画面で集計可能項目となります。
|===

=== データのロード
Cubeデータを手動でロードする場合は、TOPにある「Reload」ボタンを実行してください。
また手動でアンロードする場合は、TOPにある「Unload」ボタンを実行してください。