[[CubeTemplateService]]
=== [.eeonly]#CubeTemplateService#
This service manages custom measure templates for Cube aggregation.

==== Interface Name
----
org.iplass.mtp.impl.aggregation.unit.cube.CubeTemplateService
----

==== Implementing Class
----
org.iplass.mtp.impl.aggregation.unit.cube.CubeTemplateService
----

==== The settings of CubeTemplateService
CubeTemplateService can be configured with the following items.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| templateSettings | <<CubeTemplateSetting>>, Multiple | The settings of template using the custom measures.
|===

[[CubeTemplateSetting]]
.CubeTemplateSetting
Please specify org.iplass.mtp.impl.aggregation.unit.cube.CubeTemplateSetting to the class.

For the templates of custom measure, the following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| displayLabel | String | Display Label.
| valueExpressionTemplate | String | The Expression of the custom measure. The ${1} embedded in the expression will be replaced with the cube item name.
| locale | String | Locale
|===

===== Example
[source, xml]
----
<service>
	<interface>org.iplass.mtp.impl.aggregation.unit.cube.CubeTemplateService</interface>
	<class>org.iplass.mtp.impl.aggregation.unit.cube.CubeTemplateService</class>
	<property name="templateSettings" class="org.iplass.mtp.impl.aggregation.unit.cube.CubeTemplateSetting">
		<property name="displayLabel" value="10刻み" />
		<property name="valueExpressionTemplate" value="CASE WHEN ${1} &lt; 10 THEN '0' WHEN ${1} &lt; 20 THEN '10' WHEN ${1} &lt; 30 THEN '20' WHEN ${1} &lt; 40 THEN '30' WHEN ${1} &lt; 50 THEN '40' WHEN ${1} &lt; 60 THEN '50' WHEN ${1} &lt; 70 THEN '60' ELSE '70' END" />
		<property name="locale" value="ja" />
	</property>
	<property name="templateSettings" class="org.iplass.mtp.impl.aggregation.unit.cube.CubeTemplateSetting">
		<property name="displayLabel" value="10 increments" />
		<property name="valueExpressionTemplate" value="CASE WHEN ${1} &lt; 10 THEN '0' WHEN ${1} &lt; 20 THEN '10' WHEN ${1} &lt; 30 THEN '20' WHEN ${1} &lt; 40 THEN '30' WHEN ${1} &lt; 50 THEN '40' WHEN ${1} &lt; 60 THEN '50' WHEN ${1} &lt; 70 THEN '60' ELSE '70' END" />
		<property name="locale" value="en" />
	</property>
<!--
	<property name="templateSettings" class="org.iplass.mtp.impl.aggregation.unit.cube.CubeTemplateSetting">
		<property name="displayLabel" value="" />
		<property name="valueExpressionTemplate" value="" />
		<property name="locale" value="ja" />
	</property>
	<property name="templateSettings" class="org.iplass.mtp.impl.aggregation.unit.cube.CubeTemplateSetting">
		<property name="displayLabel" value="" />
		<property name="valueExpressionTemplate" value="" />
		<property name="locale" value="en" />
	</property>
-->
</service>
----
