[[GemConfigService]]
=== GemConfigService
This service manage the settings of the overall performance of the general pages(GEM).

==== Interface Name
----
org.iplass.gem.GemConfigService
----


==== Implementing Class
.For Community Edition
----
org.iplass.gem.GemConfigService
----
.[.eeonly]#For Enterprise Edition#
----
org.iplass.gem.EnterpriseGemConfigService
----


==== The settings of GemConfigService
The performance of the community edition can be configured with the following items.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| mustLoadWithReference | boolean a| Specifies whether to load reference property data if the target contains reference data when updating.
If false, only `oid` and `version` property values are retained. The default value is true.

CAUTION: Setting it to false improves performance when updating, but should be set to true if the reference is assumed to be loaded by an existing Interrupter or other process.
 In future versions, this setting will be removed and the behavior will be the same as false.
| loadWithReference | boolean | If mustLoadWithReference is true, specifies whether to load the reference property along with the referenced data when loading the referenced data. Default value is false.
| formatNumberWithComma | boolean | Whether to format numeric property values ​​with commas in the detail display screen. The default value is true.
| fileSupportType | FileSupportType | File format to be used for download and upload. Specify from `CSV` `EXCEL` `SPECIFY`. The default value is `CSV`.
| csvDownloadMaxCount | int | Maximum number of file downloads. The default value is 65535.
| uploadableCsvDownloadLoadSize | int | Size of Entity batch loads containing multiplicity multiple references when downloading file in Upload format. The default value is 1.
| csvDownloadCharacterCode | String, Multiple | CSV download character code. The default value is `UTF-8`.
| csvDownloadQuoteAll | boolean | Set whether to output double quotes when downloading CSV file. The default value is true.
| csvDownloadReferenceVersion | boolean | Whether to output the reference items' version in file downloads. The default value is true.
| uploadableCsvDownloadWithMappedByReference | boolean | Whether to output mapped by reference properties when downloading file in Upload format. Default value is false.
| csvUploadCommitCount | int | Set the file upload commit batch size. The default value is 1000.
| csvUploadAsync | boolean | Whether to upload file asynchronously. The default value is false.
When asynchronous is selected, please set `useQueue` of <<RdbQueueService>> to true.
| csvUploadStatusPollingInterval | int | Status polling interval for file upload. The default value is 10000 (10 seconds).
| searchResultCacheLimit | int | Search internal cache size for obtaining User name when downloading file. The default value is 300.
| confirmEditSave | boolean | Whether to display a confirmation dialog when saving on the edit screen and bulk update screen. The default value is false.In the case of bulk update that does not use the BulkLayout, a confirmation dialog will be displayed unconditionally.
| confirmEditCancel | boolean | Whether to display a confirmation dialog when canceling on the edit screen. The default value is true.
| topViewEditCancelBackToTop | boolean a| Whether to back to TopView when canceling when transitioning from detail screen to edit screen. The default value is false.(back to the details screen)

NOTE: Compatible setting up to 3.0.20. In the future, we plan to unify the operation to back to the detail screen.
| showSeachCondResetButton | boolean | Whether to show the reset button on the search screen. The default value is true.
| searchResultDispRowCount | int | Number of search results to be displayed on the search screen. The default value is 10.
It can be overwritten by <<../developerguide/genericentitymanager/entityview/index#searchresult_setting, search results The settings of>> of individual EntityView definitions.
| maxOfDetailSearchItems | int | Maximum number of search items in detail search screen. The default value is 100.
| searchInterval | int | Set the search interval to prevent redundant requests. If 0 is set, it will be infinite.(cannot click the search button until the result was retrieved and presented) The default value is 60000 (1 minute).
| csvDownloadInterval | int | Set the file download interval to prevent redundant requests. If 0 is set, it will be infinite.(cannot click the download button until the result was retrieved and presented) The default value is 60000 (1 minute).
| csvDownloadWithFooter | boolean | Whether to output a footer in s of general search. The default value is false.
| csvDownloadFooter | String | Set CSV download footer wording for general search.
| useDisplayLabelItemInSearch | boolean a| Whether to use a display label item in search. Use the item that specified as `Property used as display label` in `ReferencePropertyEditor Setting` as a search condition in common search or detail search when useDisplayLabelItemInSearch is true.

CAUTION: Setting flag for backward compatibility. This setting flag will be deleted in a future version.
| useDisplayLabelItemInCsvDownload | boolean a| Whether to use a display label item in file download. Use the item that specified as `Property used as display label` in `ReferencePropertyEditor Setting` as a file item when useDisplayLabelItemInCsvDownload is true.

CAUTION: Setting flag for backward compatibility. This setting flag will be deleted in a future version.
| showPulldownPleaseSelectLabel | boolean | Whether to display the label "Please select" when the pull-down menu is not selected. The default value is true.
| binaryUploadAsync | boolean | Whether to perform the binary file upload asynchronously. The default value is true.
| datePickerDefaultOption | String | Datepicker default options. The default value is. +
 `changeMonth:true,changeYear:true,yearRange:"c-10:c+10"`
| recycleBinMaxCount | int | Maximum number of trash cans displayed. If not specified, the default value is 100. If -1 is specified, there is no limit.
| deleteAllCommandBatchSize | int | Batch size when committing bulk deletion. If not specified, the default value is 100. Applicable when the bulk delete commit type is DIVISION.
| bulkUpdateAllCommandBatchSize | int | Batch size when committing bulk update. If not specified, the default value is 100. Applicable when the mass update commit type is DIVISION.
| binaryDownloadLoggingTargetProperty | <<BinaryDownloadLoggingTargetProperty>>, Multiple | Properties to be output as a binary download log.
| binaryUploadAcceptMimeTypesPattern | String a| Specifies the MIME Type pattern of the files that can be uploaded in the binary properties of the entity. The set value specifies a regular expression pattern. +
If not set, the MIME Type of the file will not be checked during upload. +
The settings are reflected in the binary properties of all entities.

Configuration example

* Accept CSV files `^(text/csv)$`
* Accept PDFs and images `^(application/pdf\|image/.*)$`

See <<WebFrontendService, WebFrontendService uploadFileTypeDetector>>, <<FileTypeDetector, FileTypeDetector>> for information on how to determine the MIME Type to be validated.

| richTextLibrary | String | Default rich text library to be used with StringPropertyEditor's `RichText` type. Specifies `QUILL` or `CKEDITOR`. The default value is `QUILL`.
| ImageColors | <<ImageColorSetting>>, Multiple | Change the image colors on the search screen, detail screen, menu, etc.
| skins | <<Skin>>, Multiple | Skins.
| themes | <<Theme>>, Multiple | Themes.
| entityViewHelper | <<EntityViewHelper>> | Helper class for displaying search screen and detail screen.
| shallowCopyLobData | boolean | Whether to shallow copy lob data when copying entity. If not specified, the default value is false.
| autoGenerateShowSystemProperty | boolean | Whether to display the system information section in the automatic generation process of EntityView screen. +
The property specified in `autoGenerateSystemProperties` is output as a read-only item as "System Information" Seciton on the detail/edit screen and search screen. It is not displayed on the new creation screen. The default value is `false`.
| autoGenerateSystemProperties | String | Properties to be displayed in "System Information" section of automatic generation process of EntityView screen.
Comma separated. Only the following properties are available. +
`oid` , `version` , `createBy` , `createDate` , `updateBy` , `updateDate` , `lockedBy`
| autoGenerateSystemPropertyDisplayPosition | String | "System information" display position for automatic generation processing of EntityView screens.
`TOP` or `BOTTOM`. The default is `TOP`.
| autoGenerateExcludeOidWhenCustomOid | boolean | In the "System information" of the automatic generation process of EntityView screen,
if OID property of Entity is customized, OID should not be displayed. The default value is `true`.
| autoGenerateUseUserPropertyEditor | boolean | Is UserPropertyEditor used for `createBy` , `updateBy` , and `lockedBy` ?
The default value is `true` .
| permitRolesToGem | String, Multiple | Gem permit roles in GemAuth.
The default value is `GemUser` and `AppAdmin` .
| permitRolesToNoView | String, Multiple | Permit roles in GemAuth when EntityView is undefined.
The default value is `AppAdmin` .
|===

[[EnterpriseGemConfigService]]
==== [.eeonly]#The settings of EnterpriseGemConfigService#
The performance of the enterprise edition can be configured with the following items.
Please configure these items along with the settings from community editions.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| savedListFileDownloadInterval | int | Set the file download interval of the SavedList list overviews to prevent redundant download requests. If 0 is set, the interval will be infinite. The default value is 60000 (1 minute).
| savedListFileSupportType | SavedListFileSupportType | The file format for downloading SavedList can be specified as CSV, EXCEL, or SPECIFY. The default value is CSV.
| entitylistingSearchInterval | int | EntityListing search  interval to prevent redundant search requests. If 0 is set, it will be infinite. The default value is 60000 (1 minute).
| entitylistingFileDownloadInterval | int | EntityListing file download interval to prevent redundant download requests. If 0 is set, it will be infinite. The default value is 60000 (1 minute).
| entityListingFileSupportType | EntityListingFileSupportType | The file format for downloading EntityListing can be specified as CSV, EXCEL, or SPECIFY. The default value is CSV.
| aggregationFileDownloadInterval | int | Aggregation file download interval. If 0 is set, it will be indefinite. The default value is 60000 (1 minute).
| aggregationRawdataFileDownloadInterval | int | Aggregation raw data file download interval. If 0 is set, it will be infinite. The default value is 60000 (1 minute).
| aggregationFileSupportType | AggregationFileSupportType | The file format for downloading aggregation can be specified as CSV, EXCEL, or SPECIFY. The default value is CSV.
| aggregationRawdataFileSupportType | AggregationFileSupportType | The file format for downloading raw data for aggregation can be specified as CSV, EXCEL, or SPECIFY. The default value is CSV.
| showBothAggregationFileDownloadButton | boolean | Whether to display the Aggregation file download button both above and below the summary table. The default value is false.
| dividingTableSideAtCrosstabFileDownload | boolean | Whether to divide and output the table side by file download of Aggregation (Crosstab). The default value is false.
| dividingTableHeadAtCrosstabFileDownload | boolean | Whether to output by dividing the header of the table with file download of Aggregation (Crosstab). The default value is false.
| outputItemLabelCrosstabFileDownload | boolean | Whether to display header/table-side item names in file download of Aggregation (Crosstab). The default value is false.
| entitylistingSearchLimit | int | EntityListing's search limit. The default value is 10.
| entitylistingFileDownloadWithFooter | boolean | Set whether to output footer in file download of EntityListing. The default value is false.
| entitylistingFileDownloadFooter | String | Footer wording for file of EntityListing.
| aggregationFileDownloadWithFooter | boolean | Whether to output a footer for aggregate file downloads. The default value is false.
| aggregationFileDownloadFooter | String | footer wording of the aggregate file downloads.
| aggregationRawdataFileDownloadWithFooter | boolean | Whether to output a footer when downloading raw file data for aggregation. The default value is false.
| aggregationRawdataFileDownloadFooter | String | Footer wording of raw data aggregate file downloads.
| confirmUserTaskSubmit | boolean | Whether to display the task confirmation dialog on the workflow task edit screen. The default value is true.
| confirmUserTaskCancel | boolean | Whether to display a cancellation confirmation dialog on the workflow task edit screen. The default value is true.
|===

[[BinaryDownloadLoggingTargetProperty]]
.BinaryDownloadLoggingTargetProperty
Please specify org.iplass.gem.BinaryDownloadLoggingTargetProperty to the class.

This property is the output target of the binary download log. The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| entityName | String | Entity name
| propertyName | String | Property Name
|===

[[ImageColorSetting]]
.ImageColorSetting
Please specify org.iplass.gem.ImageColorSetting to the class.

Image color and corresponding CSS of search screen, detail screen, menu, etc. can be configured with the following items.
When adding image color, please create corresponding CSS.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| colorName | String | Image color name.
| cssSettings | <<CssSetting>>, Multiple | The settings of the CSS corresponding to the skin.
|===

[[CssSetting]]
.CssSetting
Please specify org.iplass.gem.CssSetting to the class.

The path of the CSS corresponding to the skin can be configured with the following items.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| skinName | String | Skin name.
| cssPath | String | CSS file path.
|===

[[Skin]]
.Skin
Please specify org.iplass.mtp.tenant.Skin to the class.
The following items can be configured.
[cols="1,1,3", options="header"]
|====================
| Item | Value | Description
| displayName | String | The display name.
| skinName | String | Skin name.
| pageSkinName | String | The name of the skin for the whole page.
| menuSkinName | String | The name of the skin for the menu.
|====================

[[Theme]]
.Theme
Please specify org.iplass.mtp.tenant.Theme to the class.
The following items can be configured.
[cols="1,1,3", options="header"]
|====================
| Item | Value | Description
| displayName | String | The display name.
| themeName | String | Theme name.
|====================

[[EntityViewHelper]]
.EntityViewHelper
the helper class for displaying search screen and detail screen can be configured.

Please specify the implementing class of org.iplass.gem.EntityViewHelper to the class.

As standard implementation, the following EntityViewHelper are provided.

* <<EntityViewHelperImpl>>
* <<EnterpriseEntityViewHelperImpl>>

[[EntityViewHelperImpl]]
.EntityViewHelperImpl
EntityViewHepler for community edition.

Please specify org.iplass.gem.EntityViewHelperImpl to the class.
There is no configurable items.

[[EnterpriseEntityViewHelperImpl]]
.[.eeonly]#EnterpriseEntityViewHelperImpl#
EntityViewHelper for enterprise edition.

Please specify org.iplass.gem.EnterpriseEntityViewHelperImpl to the class.
There is no configurable items.

===== Example
[source,xml]
----
<service>
	<interface>org.iplass.gem.GemConfigService</interface>
	<class>org.iplass.gem.EnterpriseGemConfigService</class>

	<!-- File format to be used for download and upload. Specify from `CSV` `EXCEL` `SPECIFY` -->
	<property name="fileSupportType" value="CSV" />

	<!-- Maximum number of file downloads -->
	<property name="csvDownloadMaxCount" value="65535" />

	<!-- CSV download character code -->
	<!--
	UTF8 is set in gem-service-config.xml.
	If you want to add it, please specify any character code in the value referring to the following and make it valid.

	<property name="csvDownloadCharacterCode" value="windows-31j" additional="true" />
	<property name="csvDownloadCharacterCode" value="EUC-JP" additional="true" />
	 -->
	<property name="csvDownloadCharacterCode" value="UTF-8"/>

	<!-- Settings about the double quote of CSV downloads
		It is set to true by default. Set to false if you do not want to output double quotes.
		(If line break, [,], ["] and [ ] is included, double quotes are output regardless of the setting)
	 -->
	<property name="csvDownloadQuoteAll" value="true"/>

	<!-- File download reference item version output -->
	<property name="csvDownloadReferenceVersion" value="true"/>

	<!-- File upload batch commit size -->
	<property name="csvUploadCommitCount" value="1000"/>

	<!-- Internal cache size of searches for user name acquisition when downloading file -->
	<property name="searchResultCacheLimit" value="300" />

	<!-- Whether to display a confirmation dialog when saving the edit on edit page
	It is set to hide by default. Set to true if you want to display it.
	-->
	<property name="confirmEditSave" value="false"/>

	<!-- Whether to display a confirmation dialog when canceling the edit on edit page
	It is set to display by default. Set to false if you want to hide it.
	-->
	<property name="confirmEditCancel" value="true"/>

	<!-- Whether to show the reset button on the search screen
	It is set to true by default. Set to false if you want to hide it.
	-->
	<property name="showSeachCondResetButton" value="true"/>

	<!-- Number of search results to be displayed on the search screen -->
	<property name="searchResultDispRowCount" value="10"/>

	<!-- Maximum number of search items in detail search screen -->
	<property name="maxOfDetailSearchItems" value="100"/>

	<!-- Search processing interval, infinite (0) / specified milliseconds (1 or more) -->
	<property name="searchInterval" value="60000"/>

	<!-- File download interval, infinite (0) / specified milliseconds (1 or more) -->
	<property name="csvDownloadInterval" value="60000"/>
	
	<!-- Supported file types for SavedList: CSV, EXCEL, SPECIFY. -->
	<property name="savedListFileSupportType" value="CSV" />

	<!-- EntityListing search processing interval, indefinite (0) / specified milliseconds (1 or more) -->
	<property name="entitylistingSearchInterval" value="60000"/>

	<!-- Supported file types for EntityListing: CSV, EXCEL, SPECIFY. -->
	<property name="entityListingFileSupportType" value="CSV" />
	
	<!-- EntityListing file download interval, infinite (0) / specified milliseconds (1 or more) -->
	<property name="entitylistingFileDownloadInterval" value="60000"/>

	<!-- Aggregation file download interval, infinite (0) / specified milliseconds (1 or more) -->
	<property name="aggregationFileDownloadInterval" value="60000"/>

	<!-- Aggregation raw data file download interval, infinite (0) / specified milliseconds (1 or more) -->
	<property name="aggregationRawdataFileDownloadInterval" value="60000"/>
	
	<!-- Supported file types for Aggregation: CSV, EXCEL, SPECIFY. -->
	<property name="aggregationFileSupportType" value="CSV" />
		
	<!-- Supported file types for Aggregation raw data: CSV, EXCEL, SPECIFY. -->
	<property name="aggregationRawdataFileSupportType" value="CSV" />

	<!-- Whether to display the Aggregation file download above and below the summary table -->
	<property name="showBothAggregationFileDownloadButton" value="false"/>

	<!-- Whether the table side is divided for the outputs by file download of Aggregation (Crosstab) -->
	<property name="dividingTableSideAtCrosstabFileDownload" value="false"/>

	<!-- Whether the header side is divided for the outputs by file download of Aggregation (Crosstab) -->
	<property name="dividingTableHeadAtCrosstabFileDownload" value="false"/>

	<!-- Whether to display table side / header side item names in file download of Aggregation (Crosstab) -->
	<property name="outputItemLabelCrosstabFileDownload" value="false"/>

	<!-- Whether to output footer in CSV download for general search -->
	<property name="csvDownloadWithFooter" value="false"/>

	<!-- Wording for the footer of the CSV of general search -->
	<property name="csvDownloadFooter" value=""/>

	<!-- Whether to use a display label item in search -->
	<property name="useDisplayLabelItemInSearch" value="true"/>

	<!-- Whether to use a display label item in file download -->
	<property name="useDisplayLabelItemInCsvDownload" value="true"/>

	<!-- EntityListing's search limit -->
	<property name="entitylistingSearchLimit" value="10"/>

	<!-- Whether to output footer in file download of EntityListing -->
	<property name="entitylistingFileDownloadWithFooter" value="false"/>

	<!-- Wording for the footer of the file of EntityListing -->
	<property name="entitylistingFileDownloadFooter" value=""/>

	<!-- Whether to output footer in aggregation file downloads-->
	<property name="aggregationFileDownloadWithFooter" value="false"/>

	<!-- Wording for the footer of the file of aggregation -->
	<property name="aggregationFileDownloadFooter" value=""/>

	<!-- Whether to output footer in aggregation's raw data file downloads -->
	<property name="aggregationRawdataFileDownloadWithFooter" value="false"/>

	<!-- Wording for the footer of the file of aggregation's raw data -->
	<property name="aggregationRawdataFileDownloadFooter" value=""/>

	<!-- Whether to display the task confirmation dialog on the workflow task edit screen
	It is set to display by default. Set to false if you want to hide it.
	-->
	<property name="confirmUserTaskSubmit" value="true"/>

	<!-- Whether to display a cancellation confirmation dialog on the workflow task details screen
	It is set to display by default. Set to false if you want to hide it.
	-->
	<property name="confirmUserTaskCancel" value="true"/>

	<!-- Settings on asynchronous file upload  -->
	<!-- If true(asynchronous) was selected, please also set the useQueue property in RdbQueueService to true. -->
	<property name="csvUploadAsync" value="false"/>

	<!-- File upload status polling interval, specified in milliseconds -->
	<property name="csvUploadStatusPollingInterval" value="10000"/>

	<!-- Whether to display the "Please select" pull-down box-->
	<property name="showPulldownPleaseSelectLabel" value="true" />

	<!-- Binary file upload asynchronous setting -->
	<property name="binaryUploadAsync" value="true" />

	<property name="binaryDownloadLoggingTargetProperty">
		<property name="entityName" value="mtp.maintenance.Package" />
		<property name="propertyName" value="archive" />
	</property>
	<property name="binaryDownloadLoggingTargetProperty">
		<property name="entityName" value="mtp.listing.SavedList" />
		<property name="propertyName" value="listedData" />
	</property>

	<!-- Binary file upload acceptable MIME Type pattern. Specify a regular expression. -->
	<!-- Configuration example
	<property name="binaryUploadAcceptMimeTypesPattern" value="^(image/.*|application/pdf|text/csv)$" />
	-->

	<!-- Image color for GEM general pages and menu. -->
	<property name="imageColors">
		<property name="colorName" value="blue" />
		<property name="cssSettings">
			<property name="skinName" value="flat" />
			<property name="cssPath" value="/styles/gem/skin/flat/imagecolor/blue.css" />
		</property>
		<property name="cssSettings">
			<property name="skinName" value="horizontal" />
			<property name="cssPath" value="/styles/gem/skin/horizontal/imagecolor/blue.css" />
		</property>
		<property name="cssSettings">
			<property name="skinName" value="vertical" />
			<property name="cssPath" value="/styles/gem/skin/vertical/imagecolor/blue.css" />
		</property>
	</property>
	<property name="imageColors">
		<property name="colorName" value="green" />
		<property name="cssSettings">
			<property name="skinName" value="flat" />
			<property name="cssPath" value="/styles/gem/skin/flat/imagecolor/green.css" />
		</property>
		<property name="cssSettings">
			<property name="skinName" value="horizontal" />
			<property name="cssPath" value="/styles/gem/skin/horizontal/imagecolor/green.css" />
		</property>
		<property name="cssSettings">
			<property name="skinName" value="vertical" />
			<property name="cssPath" value="/styles/gem/skin/vertical/imagecolor/green.css" />
		</property>
	</property>
	<property name="imageColors">
		<property name="colorName" value="red" />
		<property name="cssSettings">
			<property name="skinName" value="flat" />
			<property name="cssPath" value="/styles/gem/skin/flat/imagecolor/red.css" />
		</property>
		<property name="cssSettings">
			<property name="skinName" value="horizontal" />
			<property name="cssPath" value="/styles/gem/skin/horizontal/imagecolor/red.css" />
		</property>
		<property name="cssSettings">
			<property name="skinName" value="vertical" />
			<property name="cssPath" value="/styles/gem/skin/vertical/imagecolor/red.css" />
		</property>
	</property>
	<property name="imageColors">
		<property name="colorName" value="yellow" />
		<property name="cssSettings">
			<property name="skinName" value="flat" />
			<property name="cssPath" value="/styles/gem/skin/flat/imagecolor/yellow.css" />
		</property>
		<property name="cssSettings">
			<property name="skinName" value="horizontal" />
			<property name="cssPath" value="/styles/gem/skin/horizontal/imagecolor/yellow.css" />
		</property>
		<property name="cssSettings">
			<property name="skinName" value="vertical" />
			<property name="cssPath" value="/styles/gem/skin/vertical/imagecolor/yellow.css" />
		</property>
	</property>

	<!-- Skin definition -->
	<property name="skins" class="org.iplass.gem.Skin">
		<property name="skinName" value="flat" />
		<property name="displayName" value="Flat" />
		<property name="pageSkinName" value="flat" />
		<property name="menuSkinName" value="sub-popup" />
	</property>
	<property name="skins" class="org.iplass.gem.Skin">
		<property name="skinName" value="vertical" />
		<property name="displayName" value="Vertical Menu" />
		<property name="pageSkinName" value="vertical" />
		<property name="menuSkinName" value="sub-popup" />
	</property>
	<property name="skins" class="org.iplass.gem.Skin">
		<property name="skinName" value="horizontal" />
		<property name="displayName" value="Horizontal Menu" />
		<property name="pageSkinName" value="horizontal" />
		<property name="menuSkinName" value="sub-popup" />
	</property>
	<property name="skins" class="org.iplass.gem.Skin">
		<property name="skinName" value="horizontal_droplist" />
		<property name="displayName" value="Horizontal Menu (Drop Down)" />
		<property name="pageSkinName" value="horizontal" />
		<property name="menuSkinName" value="sub-droplist" />
	</property>

	<!-- Theme definition -->
	<property name="themes" class="org.iplass.gem.Theme">
		<property name="themeName" value="black" />
		<property name="displayName" value="Black" />
	</property>
	<property name="themes" class="org.iplass.gem.Theme">
		<property name="themeName" value="red" />
		<property name="displayName" value="Red" />
	</property>
	<property name="themes" class="org.iplass.gem.Theme">
		<property name="themeName" value="green" />
		<property name="displayName" value="Green" />
	</property>
	<property name="themes" class="org.iplass.gem.Theme">
		<property name="themeName" value="blue" />
		<property name="displayName" value="Blue" />
	</property>
	<property name="themes" class="org.iplass.gem.Theme">
		<property name="themeName" value="lightred" />
		<property name="displayName" value="Light Red" />
	</property>
	<property name="themes" class="org.iplass.gem.Theme">
		<property name="themeName" value="lightgreen" />
		<property name="displayName" value="Light Green" />
	</property>
	<property name="themes" class="org.iplass.gem.Theme">
		<property name="themeName" value="lightblue" />
		<property name="displayName" value="Light Blue" />
	</property>
	<property name="themes" class="org.iplass.gem.Theme">
		<property name="themeName" value="orange" />
		<property name="displayName" value="Orange" />
	</property>
	<property name="entityViewHelper" class="org.iplass.gem.EnterpriseEntityViewHelperImpl" />
</service>
----