[[MdcConfigService]]
=== [.eeonly]#MdcConfigService#
This service manage the settings of the overall performance of the MDC version of the general pages.

==== Interface Name
----
org.iplass.mtp.mdc.MdcConfigService
----


==== Implementing Class
----
org.iplass.mtp.mdc.MdcConfigService
----


==== The settings of MdcConfigService

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| formatNumberWithComma | boolean | Whether to format numeric property values ​​with commas in the detail display screen. The default value is true.
| searchResultType | MdcSearchResultType | Specify the search result display format from CARD, TABLE, or SWITCH. The default value is CARD.
| searchResultDetailViewType | MdcDetailViewTypeInSearchResult | Detail view type in search result. Specify from `DIALOG` , `TWO_PANE` . The default value is `DIALOG` .
| searchResultDispRowCount | int |  Number of search results to be displayed on the search screen. The default value is 10.
| searchInterval | int | Set the search interval to prevent redundant requests. If 0 is set, it will be infinite.(cannot click the search button until the result was retrieved and presented) The default value is 60000 (1 minute).
| useDisplayLabelItemInFileDownload | boolean a| Whether to use a display label item in file download. Use the item that specified as `Property used as display label` in `ReferencePropertyEditor Setting` as a file item when useDisplayLabelItemInFileDownload is true.

CAUTION: Setting flag for backward compatibility. This setting flag will be deleted in a future version.
| fileSupportType | FileSupportType | File format to be used for download. Specify from `CSV` `EXCEL` `SPECIFY`. The default value is `CSV`.
| fileSupportTypeForUpload | FileSupportTypeForUpload | The file format used for upload. Choose from `CSV` `EXCEL` `SPECIFY`. The default value is `CSV`.
| fileDownloadMaxCount | int | Maximum number of file downloads. The default value is 65535.
| uploadableFileDownloadLoadSize | int | Size of Entity batch loads containing multiplicity multiple references when downloading file in Upload format. The default value is 1.
| searchUserResultCacheLimitForFileDownload | int | Search internal cache size for obtaining User name when downloading file. The default value is 300.
| fileDownloadReferenceVersion | boolean | Whether to output the reference items' version in file downloads. The default value is true.
| showDownloadButtonInSearchConditionDialog | boolean | Whether to display the download button in the SearchConditionDialog. The default value is false.
| csvDownloadCharacterCode | String, Multiple | CSV download character code. The default value is `UTF-8`.
| csvDownloadQuoteAll | boolean | Set whether to output double quotes when downloading CSV file. The default value is true.
| csvDownloadWithFooter | boolean | Whether to output a footer in CSV downloads of general search. The default value is false.
| csvDownloadFooter | String | Set CSV download footer wording for general search.
| fileUploadCommitCount | int | File upload commit unit. The default value is 1000.
| fileUploadAsync | boolean | Whether to upload file asynchronously. The default value is false.
When asynchronous is selected, please set `useQueue` of <<RdbQueueService>> to true.
| fileUploadStatusPollingInterval | int | The interval for requesting the asynchronous upload execution results from the view. The default value is 10000 (10 seconds).
| recycleBinMaxCount | int | Maximum number of trash cans displayed. If not specified, the default value is 100. If -1 is specified, there is no limit.
| deleteAllCommandBatchSize | int | Batch size when committing bulk deletion. If not specified, the default value is 100. Applicable when the bulk delete commit type is DIVISION.
| shallowCopyLobData | boolean | Shallow copy Lob data.
If `true`, it refers to the same data as the copy source without copying the entity.
If `false`, copy the entity and refer to the data after copying.
| displayBreakpoint | <<DisplayBreakpoint>> | Display breakpoint. Set the width for each device size.
| permitRolesToMdc | String, Multiple | Mdc permit roles in MdcAuth.
The default value is `MdcUser` and `AppAdmin` .
| permitRolesToNoView | String, Multiple | Permit roles in MdcAuth when EntityView is undefined.
The default value is `AppAdmin` .
| binaryDownloadLoggingTargetProperty | <<Mdc_BinaryDownloadLoggingTargetProperty>>, Multiple | Properties to be output as a binary download log.
| binaryUploadAcceptMimeTypesPattern | String a| Specifies the MIME Type pattern of the files that can be uploaded in the binary properties of the entity. The set value specifies a regular expression pattern. +
If not set, the MIME Type of the file will not be checked during upload. +
The settings are reflected in the binary properties of all entities.

Configuration example

* Accept CSV files `^(text/csv)$`
* Accept PDFs and images `^(application/pdf\|image/.*)$`

See <<WebFrontendService, WebFrontendService uploadFileTypeDetector>>, <<FileTypeDetector, FileTypeDetector>> for information on how to determine the MIME Type to be validated.

|===

[[DisplayBreakpoint]]
.DisplayBreakpoint
Please specify org.iplass.mtp.mdc.DisplayBreakpoint to the class.The following items can be configured. +
Sends a request header (`X-Mdc-Display-Breakpoint`) to identify the display breakpoint when calling WebAPI. This can be used in display determination scripts, etc.

[cols="1,1,3", options="header"]
|====================
|  Item | Value | Description
| mobileBreakpoint | String | Mobile breakpoint. Set the item name of the threshold for judging mobile.
| thresholds | <<BreakpointThresholds>> | threshold.
|====================

[[BreakpointThresholds]]
.BreakpointThresholds
Please specify org.iplass.mtp.mdc.BreakpointThresholds to the class.
The following items can be configured.
[cols="1,1,3", options="header"]
|====================
|  Item | Value | Description
| xs | int | xs threshold (px).
| sm | int | sm threshold (px).
| md | int | md threshold (px).
| lg | int | lg threshold (px).
| xl | int | xl threshold (px).
|====================

[[Mdc_BinaryDownloadLoggingTargetProperty]]
.BinaryDownloadLoggingTargetProperty
Please specify org.iplass.mtp.mdc.BinaryDownloadLoggingTargetProperty to the class.

This property is the output target of the binary download log. The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| entityName | String | Entity name
| propertyName | String | Property Name
|===

===== 設定例
[source,xml]
----
<service>
	<interface>org.iplass.mtp.mdc.MdcConfigService</interface>
	<!--  Whether to format numeric property values ​​with commas in the detail display screen -->
	<property name="formatNumberWithComma" value="true" />

	<!-- Search result display format: CARD, TABLE, SWITCH -->
	<property name="searchResultType" value="CARD" />

	<!-- Detail view type in search result. Specify from `DIALOG` , `TWO_PANE` -->
	<property name="searchResultDetailViewType" value="DIALOG" />

	<!-- Number of search results to be displayed on the search screen. -->
	<property name="searchResultDispRowCount" value="10"/>

	<!-- Search processing interval, infinite (0) / specified milliseconds (1 or more) -->
	<property name="searchInterval" value="60000"/>
	
	<!-- Whether to output the property used as a display label in file download processing -->
    <property name="useDisplayLabelItemInFileDownload" value="false"/>

    <!-- Supported file types for file download: CSV, EXCEL, SPECIFY -->
    <property name="fileSupportType" value="CSV" />
    
    <!-- Supported file types for file upload: CSV, EXCEL, SPECIFY --> 
    <property name="fileSupportTypeForUpload" value="CSV" />

    <!-- Maximum number of records for file download -->
    <property name="fileDownloadMaxCount" value="65535" />

    <!-- Batch load size when including multiple references with multiplicity in upload-type CSV download -->
    <property name="uploadableFileDownloadLoadSize" value="1" />

    <!-- Internal cache size for retrieving user names during file download -->
    <property name="searchUserResultCacheLimitForFileDownload" value="300" />

    <!-- Output reference item version in file download -->
    <property name="fileDownloadReferenceVersion" value="true"/>

    <!-- Whether to display the download button in SearchConditionDialog -->
    <property name="showDownloadButtonInSearchConditionDialog" value="false"/>

    <!-- CSV download character encoding -->
    <property name="csvDownloadCharacterCode" value="UTF-8" additional="true" />

    <!-- Always output double quotes in CSV download -->
    <property name="csvDownloadQuoteAll" value="true"/>

    <!-- Whether to output footer in CSV download for generic search -->
    <property name="csvDownloadWithFooter" value="false"/>

    <!-- Footer text for CSV download in generic search -->
    <property name="csvDownloadFooter" value=""/>

    <!-- File upload commit unit -->
    <property name="fileUploadCommitCount" value="1000"/>

    <!-- Settings on asynchronous file upload  -->
    <!-- If true(asynchronous) was selected, please also set the useQueue property in RdbQueueService to true. -->
    <property name="fileUploadAsync" value="false"/>

    <!-- The interval for requesting the asynchronous upload execution results from the view, specified in milliseconds -->
    <property name="fileUploadStatusPollingInterval" value="10000"/>

	<!-- Maximum number of trash cans displayed -->
	<property name="recycleBinMaxCount" value="100" />

	<!-- Batch size when committing bulk deletion. -->
	<property name="deleteAllCommandBatchSize" value="100" />

	<!-- Shallow copy Lob data when copying entity data on detail view -->
	<property name="shallowCopyLobData" value="false" />

	<!-- Display Setting  -->
	<property name="displayBreakpoint" class="org.iplass.mtp.mdc.DisplayBreakpoint">
		<property name="mobileBreakpoint" value="md" />
		<property name="thresholds" class="org.iplass.mtp.mdc.BreakpointThresholds" >
			<property name="xs" value="0" />
			<property name="sm" value="600" />
			<property name="md" value="960" />
			<property name="lg" value="1264" />
			<property name="xl" value="1904" />
		</property>
	</property>

	<!-- MdcAuth Mdc permission role -->
	<property name="permitRolesToMdc" value="MdcUser" />
	<property name="permitRolesToMdc" value="AppAdmin" />

	<!-- MdcAuth Permitted roles when EntityView is undefined -->
	<property name="permitRolesToNoView" value="AppAdmin" />

	<!-- Log output setting for Binary download -->
	<property name="binaryDownloadLoggingTargetProperty">
		<property name="entityName" value="mtp.maintenance.Package" />
		<property name="propertyName" value="archive" />
	</property>

	<!-- Binary file upload acceptable MIME Type pattern. Specify a regular expression. -->
	<!-- Configuration example
	<property name="binaryUploadAcceptMimeTypesPattern" value="^(image/.*|application/pdf|text/csv)$" />
	-->
</service>
----
