[[MdcConfigService]]
=== [.eeonly]#MdcConfigService#
モバイル版汎用画面全般の動作の設定を行うサービスです。

==== インタフェース名
----
org.iplass.mtp.mdc.MdcConfigService
----


==== 実装クラス名
----
org.iplass.mtp.mdc.MdcConfigService
----


==== MdcConfigServiceの設定

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| formatNumberWithComma | boolean | 詳細表示画面で数値プロパティの値をカンマでフォーマットするか。デフォルト値はtrueです。
| searchResultDispRowCount | int | 検索結果画面で表示する検索結果の件数。デフォルト値は10です。
| searchInterval | int | 検索処理のインターバル。0を設定した場合は無期限となります。デフォルト値は60000（1分）です。
| recycleBinMaxCount | int | ゴミ箱の表示件数上限値。未指定の場合のデフォルト値は100です。-1を指定した場合は無制限となります。
| deleteAllCommandBatchSize | int | 一括削除のコミットバッチサイズ件数。未指定の場合のデフォルト値は100です。一括削除コミットタイプがDIVISIONの場合適用されます。
| themes | <<MdcTheme>>、複数指定可 | テーマ。
| themeColorSchemes | <<ThemeColorScheme>>、Map形式 | テーマ配色。keyにテーマ名を指定し、Map形式で各テーマの配色を設定します。
| displayBreakpoint | <<DisplayBreakpoint>> | ディスプレイブレイクポイント。各デバイスサイズの幅を設定します。
| permitRolesToMdc | String、複数指定可 | MdcAuthでのMdc許可ロール。
デフォルト値は `MdcUser` と `AppAdmin` です。
| permitRolesToNoView | String、複数指定可 | MdcAuthでのEntityViewが未定義の場合の許可ロール。
デフォルト値は `AppAdmin` です。
| binaryDownloadLoggingTargetProperty | <<Mdc_BinaryDownloadLoggingTargetProperty>>、複数指定可 | バイナリダウンロード用ログの出力対象のプロパティ。
| binaryUploadAcceptMimeTypesPattern | String a| エンティティのバイナリプロパティでアップロード可能なファイルのMIME Typeパターンを指定します。設定値は正規表現パターンを指定します。 +
設定が無い場合はアップロード時のファイルの MIME Type の確認は実施しません。 +

設定例

* CSVファイルのアップロード許可 `^(text/csv)$`
* PDFと画像のアップロード許可 `^(application/pdf\|image/.*)$`

検証対象となる MIME Type の決定方法については、<<WebFrontendService, WebFrontendService uploadFileTypeDetector>>, <<FileTypeDetector, FileTypeDetector>> を参照してください。

|===

[[MdcTheme]]
.Theme
classはorg.iplass.mtp.mdc.tenant.Themeを指定します。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|====================
| 項目 | 値 | 説明
| themeName | String | テーマ名。
| displayName | String | 表示名。
|====================

[[ThemeColorScheme]]
.ThemeColorScheme
classはorg.iplass.mtp.mdc.tenant.ThemeColorSchemeを指定します。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|====================
| 項目 | 値 | 説明
| primary | String | プライマリカラー
| secondary | String | セカンダリカラー
| neutral | String | ニュートラルカラー。デフォルト値は `#D4D4D4` です。
| success | String | 成功カラー。デフォルト値は `#4CAF50` です。
| info | String | 情報カラー。デフォルト値は `#2196F3` です。
| warning | String | 警告カラー。デフォルト値は `#FF7D07` です。
| error | String | エラーカラー。デフォルト値は `#FF5252` です。
| background | String | バックグラウンドカラー。デフォルト値は `#F7F7F7` です。
| surface | String | サーフェスカラー。デフォルト値は `#FFFFFF` です。
|====================

[[DisplayBreakpoint]]
.DisplayBreakpoint
classはorg.iplass.mtp.mdc.DisplayBreakpointを指定します。以下の項目を設定可能です。 +
WebAPI呼び出し時、ディスプレイブレイクポイントを特定するためのリクエストヘッダー（`X-Mdc-Display-Breakpoint`）を送信します。表示判定スクリプトなどで利用可能です。

[cols="1,1,3", options="header"]
|====================
| 項目 | 値 | 説明
| mobileBreakpoint | String | モバイルブレイクポイント。モバイルと判断する閾値の項目名を設定します。
| thresholds | <<BreakpointThresholds>> | 閾値。
|====================

[[BreakpointThresholds]]
.BreakpointThresholds
classはorg.iplass.mtp.mdc.BreakpointThresholdsを指定します。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|====================
| 項目 | 値 | 説明
| xs | int | xsの閾値(px)。
| sm | int | smの閾値(px)。
| md | int | mdの閾値(px)。
| lg | int | lgの閾値(px)。
| xl | int | xlの閾値(px)。
|====================

[[Mdc_BinaryDownloadLoggingTargetProperty]]
.BinaryDownloadLoggingTargetProperty
classはorg.iplass.mtp.mdc.BinaryDownloadLoggingTargetPropertyを指定します。

バイナリダウンロード用ログの出力対象のプロパティです。以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| entityName | String | エンティティ名。
| propertyName | String | プロパティ名。
|===

===== 設定例
[source, xml]
----
<service>
	<interface>org.iplass.mtp.mdc.MdcConfigService</interface>

	<!-- 詳細画面で数値プロパティの値をカンマでフォーマットするか -->
	<property name="formatNumberWithComma" value="true" />

	<!-- 検索画面で表示する検索結果の件数 -->
	<property name="searchResultDispRowCount" value="10"/>

	<!-- 検索処理のインターバル、無期限(0)/指定ミリ秒(1以上) -->
	<property name="searchInterval" value="60000"/>

	<!-- ゴミ箱の表示件数上限値 (-1は無制限) -->
	<property name="recycleBinMaxCount" value="100" />

	<!-- 一括削除のコミット件数 -->
	<property name="deleteAllCommandBatchSize" value="100" />

	<!-- テーマ定義 -->
	<property name="themes" class="org.iplass.mtp.mdc.tenant.Theme">
		<property name="themeName" value="green" />
		<property name="displayName" value="Green" />
	</property>
	<property name="themes" class="org.iplass.mtp.mdc.tenant.Theme">
		<property name="themeName" value="red" />
		<property name="displayName" value="Red" />
	</property>
	<property name="themes" class="org.iplass.mtp.mdc.tenant.Theme">
		<property name="themeName" value="blue" />
		<property name="displayName" value="Blue" />
	</property>
	<property name="themes" class="org.iplass.mtp.mdc.tenant.Theme">
		<property name="themeName" value="orange" />
		<property name="displayName" value="Orange" />
	</property>

	<!-- テーマのカラー配色定義 -->
	<property name="themeColorSchemes">
		<property name="green" class="org.iplass.mtp.mdc.tenant.ThemeColorScheme" >
			<property name="primary" value="#4CAF50" />
			<property name="secondary" value="#0D909B" />
		</property>
		<property name="red" class="org.iplass.mtp.mdc.tenant.ThemeColorScheme" >
			<property name="primary" value="#F44336" />
			<property name="secondary" value="#0D909B" />
		</property>
		<property name="blue" class="org.iplass.mtp.mdc.tenant.ThemeColorScheme" >
			<property name="primary" value="#2196F3" />
			<property name="secondary" value="#0D909B" />
		</property>
		<property name="orange" class="org.iplass.mtp.mdc.tenant.ThemeColorScheme" >
			<property name="primary" value="#FF5722" />
			<property name="secondary" value="#0D909B" />
		</property>
	</property>

	<!-- ディスプレイ設定  -->
	<property name="displayBreakpoint" class="org.iplass.mtp.mdc.DisplayBreakpoint">
		<property name="mobileBreakpoint" value="md" />
		<property name="thresholds" class="org.iplass.mtp.mdc.BreakpointThresholds" >
			<property name="xs" value="0" />
			<property name="sm" value="600" />
			<property name="md" value="960" />
			<property name="lg" value="1264" />
			<property name="xl" value="1904" />
		</property>
	</property>

	<!-- MdcAuth Mdc許可ロール -->
	<property name="permitRolesToMdc" value="MdcUser" />
	<property name="permitRolesToMdc" value="AppAdmin" />

	<!-- MdcAuth EntityViewが未定義の場合の許可ロール -->
	<property name="permitRolesToNoView" value="AppAdmin" />

	<!-- Binaryダウンロード時のログ出力設定 -->
	<property name="binaryDownloadLoggingTargetProperty">
		<property name="entityName" value="mtp.maintenance.Package" />
		<property name="propertyName" value="archive" />
	</property>

	<!-- バイナリファイルアップロード受け入れ可能な MIME Type パターン。正規表現を指定する。 -->
	<!-- 設定例
	<property name="binaryUploadAcceptMimeTypesPattern" value="^(image/.*|application/pdf|text/csv)$" />
	-->
</service>
----
