[[MdcConfigService]]
=== [.eeonly]#MdcConfigService#
MDC版汎用画面全般の動作の設定を行うサービスです。

==== インタフェース名
----
org.iplass.mtp.mdc.MdcConfigService
----


==== 実装クラス名
----
org.iplass.mtp.mdc.MdcConfigService
----


==== MdcConfigServiceの設定

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| formatNumberWithComma | boolean | 詳細表示画面で数値プロパティの値をカンマでフォーマットするか。デフォルト値はtrueです。
| searchResultDetailViewType | MdcDetailViewTypeInSearchResult | 検索結果画面での詳細画面の表示タイプ。 `DIALOG` 、 `TWO_PANE` から指定します。デフォルト値は `DIALOG` です。
| searchResultDispRowCount | int | 検索結果画面で表示する検索結果の件数。デフォルト値は10です。
| searchInterval | int | 検索処理のインターバル。0を設定した場合は無期限となります。デフォルト値は60000（1分）です。
| useDisplayLabelItemInFileDownload | boolean a| ダウンロード処理で表示ラベルとして扱うプロパティを出力するか。trueの場合、ReferencePropertyEditorで「表示ラベルとして扱うプロパティ」として設定された項目をファイル項目として出力します。

CAUTION: 後方互換性のための設定フラグです。将来のバージョンでは本設定項目は削除されます。
| fileSupportType | FileSupportType | ダウンロードで利用するファイル形式。`CSV` `EXCEL` `SPECIFY` から指定します。デフォルト値は `CSV` です。
| fileSupportTypeForUpload | FileSupportTypeForUpload | アップロードで利用するファイル形式。`CSV` `EXCEL` `SPECIFY` から指定します。デフォルト値は `CSV` です。
| fileDownloadMaxCount | int | ダウンロード件数の上限値。デフォルト値は65535です。
| uploadableFileDownloadLoadSize | int | Upload形式のダウンロード時に多重度複数の参照を含むEntityの一括ロード件数。デフォルト値は1です。
| searchUserResultCacheLimitForFileDownload | int | ダウンロード時User名取得のための検索内部キャッシュサイズ。デフォルト値は300です。
| fileDownloadReferenceVersion | boolean | ダウンロードで参照項目のバージョンを出力するか。デフォルト値はtrueです。
| showDownloadButtonInSearchConditionDialog | boolean | SearchConditionDialog内でダウンロードボタンを表示するか。デフォルト値はfalseです。
| csvDownloadCharacterCode | String、複数指定可 | CSVダウンロードの文字コード。デフォルト値は `UTF-8` です。
| csvDownloadQuoteAll | boolean | CSVダウンロードで常時ダブルクォートの出力を行うか。デフォルト値はtrueです。
| csvDownloadWithFooter | boolean | 汎用検索のCSVダウンロードでフッターを出力するか。デフォルト値はfalseです。
| csvDownloadFooter | String | 汎用検索のCSVダウンロードのフッター文言。
| fileUploadCommitCount | int | ファイルアップロードコミット単位。デフォルト値は1000です。
| recycleBinMaxCount | int | ゴミ箱の表示件数上限値。未指定の場合のデフォルト値は100です。-1を指定した場合は無制限となります。
| deleteAllCommandBatchSize | int | 一括削除のコミットバッチサイズ件数。未指定の場合のデフォルト値は100です。一括削除コミットタイプがDIVISIONの場合適用されます。
| shallowCopyLobData | boolean | Lobデータをシャローコピーするか。
`true` の場合、実体のコピーは行わず、コピー元と同じデータを参照します。
`false` の場合、実体のコピーを行い、コピー後のデータを参照します。
| displayBreakpoint | <<DisplayBreakpoint>> | ディスプレイブレイクポイント。各デバイスサイズの幅を設定します。
| permitRolesToMdc | String、複数指定可 | MdcAuthでのMdc許可ロール。
デフォルト値は `MdcUser` と `AppAdmin` です。
| permitRolesToNoView | String、複数指定可 | MdcAuthでのEntityViewが未定義の場合の許可ロール。
デフォルト値は `AppAdmin` です。
| binaryDownloadLoggingTargetProperty | <<Mdc_BinaryDownloadLoggingTargetProperty>>、複数指定可 | バイナリダウンロード用ログの出力対象のプロパティ。
| binaryUploadAcceptMimeTypesPattern | String a| エンティティのバイナリプロパティでアップロード可能なファイルのMIME Typeパターンを指定します。設定値は正規表現パターンを指定します。 +
設定が無い場合はアップロード時のファイルの MIME Type の確認は実施しません。 +

設定例

* CSVファイルのアップロード許可 `^(text/csv)$`
* PDFと画像のアップロード許可 `^(application/pdf\|image/.*)$`

検証対象となる MIME Type の決定方法については、<<WebFrontendService, WebFrontendService uploadFileTypeDetector>>, <<FileTypeDetector, FileTypeDetector>> を参照してください。

|===

[[DisplayBreakpoint]]
.DisplayBreakpoint
classはorg.iplass.mtp.mdc.DisplayBreakpointを指定します。以下の項目を設定可能です。 +
WebAPI呼び出し時、ディスプレイブレイクポイントを特定するためのリクエストヘッダー（`X-Mdc-Display-Breakpoint`）を送信します。表示判定スクリプトなどで利用可能です。

[cols="1,1,3", options="header"]
|====================
| 項目 | 値 | 説明
| mobileBreakpoint | String | モバイルブレイクポイント。モバイルと判断する閾値の項目名を設定します。
| thresholds | <<BreakpointThresholds>> | 閾値。
|====================

[[BreakpointThresholds]]
.BreakpointThresholds
classはorg.iplass.mtp.mdc.BreakpointThresholdsを指定します。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|====================
| 項目 | 値 | 説明
| xs | int | xsの閾値(px)。
| sm | int | smの閾値(px)。
| md | int | mdの閾値(px)。
| lg | int | lgの閾値(px)。
| xl | int | xlの閾値(px)。
|====================

[[Mdc_BinaryDownloadLoggingTargetProperty]]
.BinaryDownloadLoggingTargetProperty
classはorg.iplass.mtp.mdc.BinaryDownloadLoggingTargetPropertyを指定します。

バイナリダウンロード用ログの出力対象のプロパティです。以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| entityName | String | エンティティ名。
| propertyName | String | プロパティ名。
|===

===== 設定例
[source,xml]
----
<service>
	<interface>org.iplass.mtp.mdc.MdcConfigService</interface>

	<!-- 詳細画面で数値プロパティの値をカンマでフォーマットするか -->
	<property name="formatNumberWithComma" value="true" />

	<!-- 検索結果での詳細画面の表示形式 DIALOG or TWO_PANE -->
	<property name="searchResultDetailViewType" value="DIALOG" />

	<!-- 検索画面で表示する検索結果の件数 -->
	<property name="searchResultDispRowCount" value="10"/>

	<!-- 検索処理のインターバル、無期限(0)/指定ミリ秒(1以上) -->
	<property name="searchInterval" value="60000"/>
	
	<!-- ファイルダウンロード処理で表示ラベルとして扱うプロパティを出力するか -->
	<property name="useDisplayLabelItemInFileDownload" value="false"/>

	<!-- Entityデータのサポートファイルタイプ。CSV, EXCEL, SPECIFY -->
	<property name="fileSupportType" value="CSV" />

    <!-- ファイルアップロード時のサポートファイルタイプ 。CSV, EXCEL, SPECIFY　-->
    <property name="fileSupportTypeForUpload" value="CSV" />
		
	<!-- ファイルダウンロード件数上限値 -->
	<property name="fileDownloadMaxCount" value="65535" />

	<!-- Upload形式のCSVダウンロード時に多重度複数の参照を含む場合の一括ロード件数 -->
	<property name="uploadableFileDownloadLoadSize" value="1" />

	<!-- ファイルダウンロード時User名取得のための検索内部キャッシュサイズ -->
	<property name="searchUserResultCacheLimitForFileDownload" value="300" />

	<!-- ファイルダウンロード参照項目バージョン出力 -->
	<property name="fileDownloadReferenceVersion" value="true"/>

	<!-- SearchConditionDialog内でダウンロードボタンを表示するか -->
	<property name="showDownloadButtonInSearchConditionDialog" value="false"/>

	<!-- CSVダウンロード文字コード -->
	<property name="csvDownloadCharacterCode" value="UTF-8" additional="true" />

	<!-- CSVダウンロード常時ダブルクォート出力 -->
	<property name="csvDownloadQuoteAll" value="true"/>

	<!-- 汎用検索のCSVダウンロードでフッターを出力するか -->
	<property name="csvDownloadWithFooter" value="false"/>

	<!-- 汎用検索のCSVダウンロードのフッター文言 -->
	<property name="csvDownloadFooter" value=""/>

    <!-- ファイルアップロードコミット単位 -->
    <property name="fileUploadCommitCount" value="1000"/>
	
	<!-- ゴミ箱の表示件数上限値 (-1は無制限) -->
	<property name="recycleBinMaxCount" value="100" />

	<!-- 一括削除のコミット件数 -->
	<property name="deleteAllCommandBatchSize" value="100" />

	<!-- 詳細画面のエンティティデータをコピーする際にLobデータをシャローコピーするか -->
	<property name="shallowCopyLobData" value="false" />

	<!-- ディスプレイ設定  -->
	<property name="displayBreakpoint" class="org.iplass.mtp.mdc.DisplayBreakpoint">
		<property name="mobileBreakpoint" value="md" />
		<property name="thresholds" class="org.iplass.mtp.mdc.BreakpointThresholds" >
			<property name="xs" value="0" />
			<property name="sm" value="600" />
			<property name="md" value="960" />
			<property name="lg" value="1264" />
			<property name="xl" value="1904" />
		</property>
	</property>

	<!-- MdcAuth Mdc許可ロール -->
	<property name="permitRolesToMdc" value="MdcUser" />
	<property name="permitRolesToMdc" value="AppAdmin" />

	<!-- MdcAuth EntityViewが未定義の場合の許可ロール -->
	<property name="permitRolesToNoView" value="AppAdmin" />

	<!-- Binaryダウンロード時のログ出力設定 -->
	<property name="binaryDownloadLoggingTargetProperty">
		<property name="entityName" value="mtp.maintenance.Package" />
		<property name="propertyName" value="archive" />
	</property>

	<!-- バイナリファイルアップロード受け入れ可能な MIME Type パターン。正規表現を指定する。 -->
	<!-- 設定例
	<property name="binaryUploadAcceptMimeTypesPattern" value="^(image/.*|application/pdf|text/csv)$" />
	-->
</service>
----
