[[MdcRelativeRangeService]]
=== [.eeonly]#MdcRelativeRangeService#
MDC版の相対範囲を独自に追加するためのサービスです。

==== インタフェース名
----
org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeService
----

==== 実装クラス名
----
org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeService
----

==== MdcRelativeRangeServiceの設定
MdcRelativeRangeServiceを設定します。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| relativeRanges | <<MdcRelativeRange>>、複数指定可 | カスタム相対範囲の設定。
|===

[[MdcRelativeRange]]
.MdcRelativeRange
classはorg.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeを指定します。

カスタム相対範囲です。以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| relativeRangeName | String | カスタム相対範囲名。
| displayLabel | String | 表示ラベル。
| localizedDisplayLabel | <<MdcRelativeRangeLocalizedLabel>>、複数指定可 | 言語毎の表示ラベルの設定。
| converter | String | 変換ロジッククラス。 `org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeConverter` インターフェースを実装したクラスの名前を指定してください。
|===

[[MdcRelativeRangeLocalizedLabel]]
.MdcRelativeRangeLocalizedLabel
classはorg.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeLocalizedLabelを指定します。

言語毎の表示ラベルです。以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| locale | String | ロケール。
| displayLabel | String | 表示ラベル。
|===

===== 設定例
[source,xml]
----
<service>
	<interface>org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeService</interface>
	<class>org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeService</class>
	<!-- カスタム相対範囲 -->
	<property name="relativeRanges" class="org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRange">
		<property name="relativeRangeName" value="firstHalfOfThisFiscalYear" />
		<property name="displayLabel" value="今年度上期" />
		<property name="localizedDisplayLabel" class="org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeLocalizedLabel">
			<property name="locale" value="ja" />
			<property name="displayLabel" value="今年度上期" />
		</property>
		<property name="localizedDisplayLabel" class="org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeLocalizedLabel">
			<property name="locale" value="en" />
			<property name="displayLabel" value="First half of this fiscal year" />
		</property>
		<property name="converter" class="sample.FirstHalfRelativeRangeConverter" />
	</property>
	<property name="relativeRanges" class="org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRange">
		<property name="relativeRangeName" value="secondHalfOfThisFiscalYear" />
		<property name="displayLabel" value="今年度下期" />
		<property name="localizedDisplayLabel" class="org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeLocalizedLabel">
			<property name="locale" value="ja" />
			<property name="displayLabel" value="今年度下期" />
		</property>
		<property name="localizedDisplayLabel" class="org.iplass.mtp.impl.mdc.relativeRange.MdcRelativeRangeLocalizedLabel">
			<property name="locale" value="en" />
			<property name="displayLabel" value="2nd half of this fiscal year" />
		</property>
		<property name="converter" class="sample.SecondHalfRelativeRangeConverter" />
	</property>
</service>
----
