[[MdcSearchViewService]]
=== [.eeonly]#MdcSearchViewService#
モバイル版の詳細画面の設定を行うサービスです。

==== インタフェース名
----
org.iplass.mtp.impl.mdc.view.entityview.search.MdcSearchViewService
----

==== 実装クラス名
----
org.iplass.mtp.impl.mdc.view.entityview.search.MdcSearchViewService
----

==== MdcSearchViewServiceの設定
MdcSearchViewServiceを設定します。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| searchViewGenerator | <<MdcSearchViewHandlerGenerator>> | 検索画面の画面定義の自動生成設定。
| searchController | <<SearchController>> | 検索処理。
| searchSelectListController | <<SearchSelectListController>> | 選択処理検索処理。
| deleteListController | <<DeleteListController>> | Entityの一括削除処理。
| trashController | <<TrashController>> | ごみ箱操作。
|===

[[MdcSearchViewHandlerGenerator]]
.MdcSearchViewHandlerGenerator
classはorg.iplass.mtp.mdc.view.entityview.search.definition.MdcSearchViewHandlerGeneratorを指定します。

標準でorg.iplass.mtp.impl.mdc.view.entityview.search.MdcSearchViewHandlerGeneratorImplを提供しています。
以下の項目を指定可能です。

[cols="1,1,3", options="header"]
|====================
| 項目 | 値 | 説明
| showSystemProperty | boolean | システムプロパティを出力。
| systemProperties | <<searchSectionProperty>>, 複数指定可能 | システムプロパティ。 基本項目であるnameとバージョン管理項目(startDate、endDate)は対象外。
| systemPropertyDisplayPosition | SystemPropertyDisplayPosition a| システムプロパティの表示位置。
SystemPropertyDisplayPositionのenum値を指定。
次のいずれかを指定します。

TOP:: 検索条件の先頭に表示します。

BOTTOM:: 検索条件の末尾に表示します。

デフォルト値は `TOP` です。
| excludeOidWhenCustomOid | boolean | OIDをカスタマイズしている場合にOIDを非表示。
| useUserPropertyEditor | boolean | createBy、updateBy、lockedByにUserPropertyEditorを利用。
UserPropertyEditorを利用する場合、OIDではなくUserのnameが表示されます。
|====================

[[searchSectionProperty]]
.SectionProperty
システムプロパティ毎の表示可否に関する設定です。
以下の項目を設定可能です。

[cols="1,1,3", options="header"]
|====================
| 項目 | 値 | 説明
| propertyName | String | プロパティ名。
| displayCondition | boolean | 検索条件で表示するか。
| displayResult | boolean | 検索結果で表示するか。
|====================

[[SearchController]]
.SearchController
classはorg.iplass.mtp.mdc.view.entityview.search.search.SearchControllerの実装クラスを指定します。

標準でorg.iplass.mtp.impl.mdc.view.entityview.search.SearchControllerImplを提供しています。
設定可能な項目はありません。

[[SearchSelectListController]]
.SearchSelectListController
classはorg.iplass.mtp.mdc.view.entityview.search.select.SearchSelectListControllerの実装クラスを指定します。

標準でorg.iplass.mtp.impl.mdc.view.entityview.search.SearchSelectListControllerImplを提供しています。
設定可能な項目はありません。

[[DeleteListController]]
.DeleteListController
classはorg.iplass.mtp.mdc.view.entityview.search.delete.DeleteListControllerの実装クラスを指定します。

標準でorg.iplass.mtp.impl.mdc.view.entityview.search.DeleteListControllerImplを提供しています。
設定可能な項目はありません。

[[TrashController]]
.TrashController
classはorg.iplass.mtp.mdc.view.entityview.trash.TrashControllerの実装クラスを指定します。

標準でorg.iplass.mtp.impl.mdc.view.entityview.search.TrashControllerImplを提供しています。
設定可能な項目はありません。


===== 設定例
[source, xml]
----
<service>
	<interface>org.iplass.mtp.impl.mdc.view.entityview.search.MdcSearchViewService</interface>
	<!-- Auto Generator -->
	<property name="searchViewGenerator" class="org.iplass.mtp.impl.mdc.view.entityview.search.MdcSearchViewHandlerGeneratorImpl">
		<!-- システムプロパティを出力 -->
		<property name="showSystemProperty" value="false" />
		<!-- 出力するシステムプロパティ -->
		<property name="systemProperties" class="org.iplass.mtp.mdc.view.entityview.search.definition.SectionProperty">
			<property name="propertyName" value="oid" />
			<property name="displayCondition" value="false" />
			<property name="displayResult" value="false" />
		</property>
		<property name="systemProperties" class="org.iplass.mtp.mdc.view.entityview.search.definition.SectionProperty">
			<property name="propertyName" value="state" />
			<property name="displayCondition" value="false" />
			<property name="displayResult" value="false" />
		</property>
		<property name="systemProperties" class="org.iplass.mtp.mdc.view.entityview.search.definition.SectionProperty">
			<property name="propertyName" value="createDate" />
			<property name="displayCondition" value="false" />
			<property name="displayResult" value="false" />
		</property>
		<property name="systemProperties" class="org.iplass.mtp.mdc.view.entityview.search.definition.SectionProperty">
			<property name="propertyName" value="createBy" />
			<property name="displayCondition" value="false" />
			<property name="displayResult" value="false" />
		</property>
		<property name="systemProperties" class="org.iplass.mtp.mdc.view.entityview.search.definition.SectionProperty">
			<property name="propertyName" value="updateDate" />
			<property name="displayCondition" value="false" />
			<property name="displayResult" value="false" />
		</property>
		<property name="systemProperties" class="org.iplass.mtp.mdc.view.entityview.search.definition.SectionProperty">
			<property name="propertyName" value="updateBy" />
			<property name="displayCondition" value="false" />
			<property name="displayResult" value="false" />
		</property>
		<property name="systemProperties" class="org.iplass.mtp.mdc.view.entityview.search.definition.SectionProperty">
			<property name="propertyName" value="lockedBy" />
			<property name="displayCondition" value="false" />
			<property name="displayResult" value="false" />
		</property>
		<!-- システムプロパティの表示位置 TOP or BOTTOM -->
		<property name="systemPropertyDisplayPosition" value="BOTTOM" />
		<!-- OIDをカスタマイズしている場合にOIDを非表示 -->
		<property name="excludeOidWhenCustomOid" value="true" />
		<!-- createBy、updateBy、lockedByにUserPropertyEditorを利用 -->
		<property name="useUserPropertyEditor" value="true" />
	</property>
	<!-- Search Controller -->
	<property name="searchController" class="org.iplass.mtp.impl.mdc.view.entityview.search.SearchControllerImpl" />
	<!-- Search Select List Controller -->
	<property name="searchSelectListController" class="org.iplass.mtp.impl.mdc.view.entityview.search.SearchSelectListControllerImpl" />
	<!-- Delete List Controller -->
	<property name="deleteListController" class="org.iplass.mtp.impl.mdc.view.entityview.search.DeleteListControllerImpl" />
	<!-- Trash Controller -->
	<property name="trashController" class="org.iplass.mtp.impl.mdc.view.entityview.search.TrashControllerImpl" />
</service>
----
