[[appflow]]
== [.eeonly]#Amazon AppFlowを利用したデータ連携#

link:https://aws.amazon.com/jp/appflow/[Amazon AppFlow^]を利用したiPLAssと外部システム（SaaSやAWSサービス）とのデータ連携機能を提供します。 +
iPLAssをデータフローの送信元または送信先としてAppFlowに統合するためのカスタムコネクタ実装（AWS Lambdaにデプロイ可能なZipファイル）を標準で提供します。

=== カスタムコネクタの設定項目

[[connector_profile_setting]]
==== 接続作成時の設定

接続（コネクタ・プロファイル）の作成時に入力する設定項目です。

[cols="1,3a", options="header"]
|===
| 項目 | 説明
| 接続名 | 任意の接続名を入力してください
| 個人アクセストークン（トークン認証の場合） | （トークンで認証する場合に入力） Admin権限を有するユーザーの有効な個人アクセストークンを入力してください
| ユーザーID（ID・パスワード認証の場合） | （ID・パスワードで認証する場合に入力） Admin権限を有するユーザーのユーザーIDを入力してください
| パスワード（ID・パスワード認証の場合）） | （ID・パスワードで認証する場合に入力） Admin権限を有するユーザーのパスワードを入力してください
| iPLAss URL（テナントコンテキストパスまで含むURL） | データ連携対象のiPLAssが稼働するURLを入力してください
| （送信元のみ）Select型の連携フォーマット（デフォルト : DISPLAY_NAME） | （送信元の場合に入力） Select型データの連携フォーマット（`VALUE` or `DISPLAY_NAME` or `STRUCT`）を選択してください。未指定の場合のデフォルトは `DISPLAY_NAME` です。

VALUE:: Select型データの「値」を文字列として連携します

DISPLAY_NAME:: Select型データの「表示名」を文字列として連携します

STRUCT:: Select型データの「値」と「表示名」を構造体として連携します

| （送信元のみ）Reference型の連携フォーマット（デフォルト : OID） | （送信元の場合に入力） Reference型データの連携フォーマット（`OID` or `OID_VERSION`）を選択してください。未指定の場合のデフォルトは `OID` です。

OID:: Reference型データの「oid」を文字列として連携します

OID_VERSION:: Reference型データの「oid」と「version」を構造体として連携します

| （送信元のみ）Binary型の連携フォーマット（デフォルト : LOBID） | （送信元の場合に入力） Binary型データの連携フォーマット（`LOBID` or `HTTP_URI` or `S3_URI`）を選択してください。未指定の場合のデフォルトは `LOBID` です。

LOBID:: Binary型データの「LobID」をLong値として連携します。

HTTP_URI:: Binary型データのバイナリ格納先のHTTP URIを文字列として連携します。バイナリ格納先のHTTP URIとは、<<../webapi/index.adoc#binary_api, バイナリ操作 API>> で当該バイナリを取得可能なURIです。

S3_URI:: Binary型データのバイナリ格納先のS3 URIを文字列として連携します。`S3_URI` を選択した場合には、iPLAss上で管理されるバイナリを取得し、Amazon S3に格納する処理が実行されます（その格納先のS3 URIが連携されます）。バイナリの格納先となるS3バケットおよびパスはフロー作成時の設定により決定されます。
|===

[[flow_setting]]
==== フロー作成時の設定

===== 共通

フロー作成時に入力する共通の設定項目です。

[cols="1,3", options="header"]
|===
| 項目 | 説明
| DateTime型の変換に使用するタイムゾーン（デフォルト : JST） | DateTime型データのUNIX時間を変換する際のタイムゾーンを指定してください。未指定の場合のデフォルトは「JST」です。
| ドメイン単位のHTTPコネクションの最大数（デフォルト : 5） | ドメイン単位のHTTPコネクションの最大数を指定してください。未指定の場合のデフォルトは「5」です。
| HTTPコネクションのプールの最大数（デフォルト : 10）| HTTPコネクションのプールの最大数を指定してください。未指定の場合のデフォルトは「10」です。
| S3バイナリ転送時の最小パートサイズ（デフォルト : 8） | S3へのバイナリ転送時の最小パートサイズ（MB）を指定してください。未指定の場合のデフォルトは「8」です。
| S3接続の最大数 | 転送中に確立されるS3接続の最大数を指定してください。未指定の場合、転送リクエストの目標スループットによって最大数が決定されます。
| S3転送リクエストの目標スループット（デフォルト : 10） | S3転送リクエストの目標スループット（Gbps）を指定してください。未指定の場合のデフォルトは「10」です。
|===

===== 送信元のみ

iPLAssが送信元の場合にのみ、フロー作成時に入力する設定項目です。

[cols="1,3a", options="header"]
|===
| 項目 | 説明
| ソート条件（デフォルト : createDate DESC） | データを取得する際にOrderBy句に指定するソート条件を指定してください。未指定の場合のデフォルトは「createDate DESC」です。
| Binary型データを保存するS3バケット | Binary型データを保存するS3バケット名を指定してください。Binary型のデータ連携フォーマットとして `S3_URI` を選択した場合は入力必須です。
| Binary型データS3保存時のバケットプレフィックス | Binary型データをS3に保存する際のバケットプレフィックスを指定してください
| Binary型データS3保存時にLobIDをプレフィックスとして使用するか（デフォルト : 使用する） | Binary型データをS3に保存する際にLobIDをバケットプレフィックスとして使用するかを指定してください。デフォルトは「True」です。
|===

===== 送信先のみ

iPLAssが送信先の場合にのみ、フロー作成時に入力する設定項目です。

[cols="1,3a", options="header"]
|===
| 項目 | 説明
| Entity CRUD APIの更新処理時の制御オプション | Entity CRUD APIの更新処理時の制御オプションをクエリパラメータ形式で指定してください（例 : regenerateOid=false）。
| 書き込み操作パターン（デフォルト : PER_RECORD） | 書き込み操作パターン（`PER_RECORD` or `CSV_UPLOAD`）を指定してください。未指定の場合のデフォルトは「PER_RECORD」です。

PER_RECORD:: <<../webapi/index.adoc#entity_crud_api, Entity CRUD API>>を利用して、1レコード単位で書き込み処理を行います

CSV_UPLOAD:: 一定レコード数毎にCSV形式のバイナリに変換し、<<../webapi/index.adoc#entity_crud_api, Entity CRUD API>>を利用して、CSVによる一括更新を行います。AppFlowのフロー設定の「送信先レコードの設定」においてデータの挿入方法に「新しいレコードの挿入」を選択した場合には、送信元から送信先フィールドへのマッピングでoidのマッピングが必須になります。


| （PER_RECORDのみ）書き込み処理を非同期で実行するか（デフォルト : false） | 書き込み処理を非同期で実行するかを指定してください。未指定の場合のデフォルトは「False」です。
| （PER_RECORDのみ）書き込み処理を非同期で実行する場合の処理スレッド数（デフォルト : 10） | 書き込み処理を非同期で実行する場合の処理スレッド数を指定してください。未指定の場合のデフォルトは「10」です。
| （CSV_UPLOADのみ）書き込み処理のバッチサイズ（デフォルト : 100、最大 : 100） | 一括で書き込み処理を行う際のバッチサイズ（コミット単位）を指定してください。最大は「100」です。未指定の場合のデフォルトは「100」です。
|===

=== 特殊型プロパティのデータ連携における留意点

==== 送信元

iPLAssをAppFlowデータフローの送信元として利用する場合、特殊型プロパティのデータ連携において以下の留意点があります。

- Select型、Binary型、Reference型プロパティのデータ連携フォーマットは、<<connector_profile_setting, 接続作成時の設定>>によって決定されます。

- iPLAssから連携されたDateTime型データのUNIX時間を変換する際のタイムゾーンは、<<flow_setting, フロー作成時の設定>>によって決定されます。

==== 送信先

iPLAssをAppFlowデータフローの送信先として利用する場合、特殊型プロパティのデータ連携において以下の留意点があります。

- 連携された日付データをUNIX時間に変換する際のタイムゾーンは、<<flow_setting, フロー作成時の設定>>によって決定されます。

- Select型プロパティのデータ連携フォーマットは、選択値の値のみの文字列、もしくは選択値の値(value)とラベル(displayName)をキーにもった構造体に対応しています。

- Reference型プロパティのデータ連携フォーマットは、参照データのoidのみの文字列、もしくは参照データのoidとversionをキーにもった構造体に対応しています。

- Binary型プロパティのデータ連携フォーマットは、LobID、HTTP URI形式（https://）、S3 URI形式（s3://）に対応しています。HTTP URI形式とS3 URI形式の場合は、URIで指定されたリソースを取得し、<<../webapi/index.adoc#binary_api, バイナリ操作 API>> で当該バイナリをiPLAss上にアップロードし、返却されたLobIDを書き込みレコードに紐づけます。

=== 動作手順

iPLAssをデータフローの送信元または送信先としてAppFlowに統合し、データフローを実行するための手順を以下に示します。

. メタデータ CRUD APIの有効化 +
iPLAssからEntity定義の設定情報を取得するために<<../webapi/index.adoc#metadata_crud_api, メタデータ CRUD API>>を利用します。 +
メタデータ CRUD APIを利用するには、WebApiServiceの `enableDefinitionApi` 設定を有効化する必要があります。詳細は、 <<../../serviceconfig/index.adoc#WebApiService, WebApiService>>を参照してください。

. (必要に応じて) バイナリ操作 APIの有効化 +
iPLAssをデータフローの送信先に設定している場合、Binary型プロパティのデータ連携フォーマットは、LobID、HTTP URI形式（https://）、S3 URI形式（s3://）に対応しています。HTTP URI形式とS3 URI形式の場合は、URIで指定されたリソースを取得し、<<../webapi/index.adoc#binary_api, バイナリ操作 API>> で当該バイナリをiPLAss上にアップロードし、返却されたLobIDを書き込みレコードに紐づけます。 +
HTTP URI形式とS3 URI形式でのデータ連携が想定され、バイナリ操作 APIを利用する場合には、WebApiServiceの `enableBinaryApi` 設定を有効化する必要があります。詳細は、 <<../../serviceconfig/index.adoc#WebApiService, WebApiService>>を参照してください。

. Entity CRUD APIの権限設定 +
iPLAssとのデータ連携には、<<../webapi/index.adoc#entity_crud_api, Entity CRUD API>>を利用します。連携対象のEntityに対して権限を付与する必要があります。 +
詳しくは、<<../webapi/index.adoc#entity_crud_api_permission, 権限設定>>を参照してください。

. AWS Lambdaの関数作成 +
Lambda関数の設定における特筆事項を以下に示します。
* コードソース
** 有償版のSDKに同梱されているAppFlowカスタムコネクタの実装(ファイル名: iplass-ee-aws-appflow-x.x.x.zip)をアップロードしてください

* ランタイム設定
** ランタイム: `Java21`、アーキテクチャ: `x86_64` 、ハンドラ: `org.iplass.mtp.appflow.handler.MtpLambdaHandler::handleRequest` を指定してください

* アクセス権限 > 実行ロール
** Lambdaの実行ロールに対して、ID・パスワードなどの認証情報を保持するAWS Secrets Managerへのアクセス権限（`secretsmanager:GetSecretValue`、 `secretsmanager:CreateSecret`）、必要に応じてバイナリファイルの格納先であるAmazon S3（`s3:GetObject`、 `s3:PutObject`）へのアクセス権限を追加で付与してください

* アクセス権限 > リソースベースのポリシーステートメント
** AppFlowからLambda関数を実行するための権限を付与します
** サービス: `Other`、ステートメントID: `任意の一意なID`、プリンシパル: `appflow.amazonaws.com`、ソースARN: `arn:aws:appflow:ap-northeast-1:<AWSアカウントID>:*`、アクション: `lambda:InvokeFunction` を指定してください

. カスタムコネクタの登録 & 接続の作成 +
以下の手順でAppFlowに新しいコネクタを登録し、接続（コネクタ・プロファイル）を作成します（AWS マネジメントコンソールを利用する想定）。

.. AppFlowの「コネクタ」の画面から、「新しいコネクタを登録」ボタンを押下します
.. 先の手順で作成した Lambda関数を選択し、任意のコネクタラベルを指定して「登録」ボタンを押下します
.. 「接続を作成」ボタンを押下します
.. <<connector_profile_setting, 接続作成時の設定>>を参考に必要事項を入力し、「接続する」ボタンを押下します
.. 接続が正常に作成されたことを確認してください

. フロー作成 +
以下の手順でAppFlowのデータフローを作成します（AWS マネジメントコンソールを利用する想定）。

.. AppFlowの「フロー」の画面から、「フローを作成」ボタンを押下します
.. 「手順1 フローの詳細を指定」では、特筆事項はありません。必要事項を入力してください。
.. 「手順2 フローを設定」では、データフローの送信元と送信先を指定します。以下の設定を行ってください。
... 先の手順で作成したカスタムコネクタ（iPLAss）を送信元または送信先に指定してください。その後、以下の設定を行います。
.... 先の手順で作成した接続（コネクタ・プロファイル）を指定してください
.... 連携対象のEntity定義を指定してください
....  <<flow_setting, フローの設定>>を参考に必要事項を入力してください
... iPLAssと連携する外部システム（SaaSやAWSサービス）を送信元または送信先に指定し、必要事項を入力してください
... フロートリガー（オンデマンド実行 or スケジュール実行）を設定してください
.. 「手順3 データフィールドをマッピング」では、特筆事項はありません。送信先レコードの設定、送信元から送信先フィールドへのマッピングなど必要な設定を行ってください。
.. 「手順4 フィルターを追加する」では、特筆事項はありません。必要に応じてフィルターを設定してください。
.. 「手順5 確認して作成」では、特筆事項はありません。設定内容を確認してフローの作成を完了してください。

. フロー実行 +
* フロートリガーで「オンデマンドで実行」を選択した場合、フローは、「フローの詳細」画面の「フローを実行」ボタンを押下すると実行されます。
* フロートリガーで「スケジュール通りにフローを実行」を選択した場合、設定した時間にフローが自動で起動します。
