[[customcomponent]]
== カスタムコンポーネント

カスタムコンポーネントをレイアウトに配置することで、独自の画面部品を画面に組み込むことができます。

カスタムコンポーネントは、 `コンポーネント種別` によって、テンプレート文字列を直接記述する方法と、登録済みのコンポーネントを呼び出す方法のいずれかを選択できます。 +
テンプレートの実装方法の詳細については、 link:../../../storybook/index.html?path=/docs/開発者ドキュメント-オリジナルテンプレート[コンポーネントカタログ^]を参照してください。


[[customcomponent_settings]]
=== カスタムコンポーネントの設定

[cols="1,4a", options="header"]
|===
|設定項目 |設定内容

|コンポーネント種別
|カスタムコンポーネントの実装方式を選択します。 +
選択した種別によって、以降の項目の有効範囲や挙動が異なります。

TEMPLATE:: テンプレート文字列を直接記述してコンポーネントを定義します。 +
`テンプレートの解釈方法` に応じて `HTML` / `VUE_SFC` / `VUE_SFC_LIKE` のいずれかを選択できます。

COMPONENT:: 登録済みのコンポーネントを呼び出します。 +
`コンポーネント名` には呼び出すコンポーネントの名称を指定します。実行時にはコンポーネントが動的にロードされ、コンポーネントとしてレンダリングされます。 +
未登録のコンポーネント名を指定した場合、ロードに失敗し、コンポーネントが正しく表示されません。

|テンプレート定義名
|登録済テンプレート名を設定します。 +
`コンポーネント種別` が `TEMPLATE` の場合に有効な設定です。

|テンプレートの解釈方法
|記述されたテンプレート文字列の解釈タイプです。 `コンポーネント種別` が `TEMPLATE` の場合に選択できます。 +
以下の3つから選択できます。

HTML:: HTMLとして解釈します。HTMLやスクリプトの記述が可能です。
VUE_SFC:: Vue.jsのSFC形式（単一ファイルコンポーネント形式）で記述されたコンポーネントとして解釈します。
VUE_SFC_LIKE:: Vue.jsのランタイムを用いてコンポーネントとして解釈します。MDCでは、Vue.jsのランタイムに加えてコンパイラもバンドルしており、Vue.jsのテンプレート構文を利用することが可能です。

|コンポーネント名
|`コンポーネント種別` が `COMPONENT` の場合は必須です。呼び出すコンポーネントの名称を指定します。 +
`コンポーネント種別` が `TEMPLATE` の場合で `テンプレートの解釈方法` が `VUE_SFC_LIKE` の場合も必須です。 +
`テンプレートの解釈方法` が `VUE_SFC` でコンポーネント名が未入力の場合、自動でランダムなコンポーネント名を割り当てます。 +
コンポーネント名は、英文字とハイフン(-)のみを利用したパスカルケースでの命名を推奨します。

|VUE_SFC形式のテンプレートをプリコンパイルするか
|Vue.jsのSFC形式のテンプレートをプリコンパイルするかを指定します。`テンプレートの解釈方法` が `VUE_SFC` であり、Vue.jsのSFC形式のテンプレートを定義保存時にプリコンパイルしておきたい場合にチェックします。プリコンパイルしておくことで、コンポーネントの初期化処理を高速化できます。

[NOTE]
====
プリコンパイルの注意点::
- プリコンパイルを実行したい場合には、 `コンポーネント名` の指定が必須となります。
- `テンプレート定義名` で指定した登録済みのテンプレートは、定義保存時に実行されてプリコンパイルされるため、テンプレートの内容が変更された場合は再度定義を保存する必要があります。また、JSPやGroovyTemplateなどで記述されたテンプレートには、リクエスト情報やセッション情報、ユーザー固有情報などを使用しないように注意してください。
====

|===


[[customcomponent_data_binding]]
=== データ受け渡し

カスタムコンポーネントが受け取る props および発火する emits は、 **カスタムコンポーネントで置き換える対象のMDC標準のコンポーネントが受け取る props および発火する emits と同じ** になります。 +
詳細は置き換え対象のMDC標準コンポーネントの実装を参照してください。

.例：検索条件ダイアログをカスタムコンポーネントに置き換える場合
====
置き換え対象の `MSearchConditionDialog.vue` が受け取る props と発火する emits がそのままカスタムコンポーネントに引き渡されます。 +

.置き換え対象の props
* `viewKey` : EntityView の Key 情報
* `title` : 検索画面タイトル
* `searchConditionSection` : 検索条件セクション
* `initialSearchCondition` : 初期検索条件
* `searchErrorInfo` : 検索エラーメッセージ
* `aboveConditionSection` : 検索条件上のセクション
* `belowConditionSection` : 検索条件下のセクション
* `customSearchCondition` : 検索条件をさらに別のカスタムコンポーネントで置き換える設定
* `contextMap` : コンテキストマップ（下位のコンポーネントに引き渡す情報）

.置き換え対象の emits
* `change:search-condition` : 検索条件変更
* `loaded:definition` : 検索画面定義ロード完了
* `error:load` : 検索画面定義ロード失敗
* `update:linkProperty` : 連動プロパティ更新

カスタムコンポーネントはこれらの props / emits を、置き換え対象が `VUE_SFC` / `VUE_SFC_LIKE` のテンプレートで実装されたコンポーネントか、 `COMPONENT` で読み込まれたコンポーネントかにかかわらず、透過的に受け渡します。
====
