[[customize]]
== カスタム処理の組み込み

[[MdcCustomize_Search]]
=== カスタム検索処理
検索画面や選択画面で、検索処理の実行前後に独自の処理を組み込むことができます。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを検索画面のEQLカスタム処理クラス名に指定します。

====
org.iplass.mtp.mdc.view.entityview.search.SearchQueryInterceptor
====

.処理一覧
[cols="1,1,1,1a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

|beforeSearch
|SearchQueryContext
|なし
|検索前処理を行います。

.2+|afterSearch
|SearchQueryContext
.2+|なし
.2+|検索後処理を行います。afterSearchではEntity1レコード毎に処理が呼ばれます。
|Entity

.2+|afterSearchComplete
|SearchQueryContext
.2+|なし
.2+|検索完了処理を行います。
|List<Entity>

|===

CAUTION: 3.2.18から新しいシグネチャのメソッドを追加し、3.2.17以前のシグネチャのメソッドを非推奨としました。将来のバージョンでは3.2.17以前のシグネチャのメソッドは削除されます。

.SearchQueryInterceptorの例
`SearchQueryInterceptor` では、`beforeSearch` `afterSearch` `afterSearchComplete` をデフォルト実装しています。
必要に応じてオーバーライドします。

例えば `beforeSearch` では、クエリのカスタマイズ結果や検索時のオプションを設定したSearchQueryContextを返すように実装します。

[source,java]
----
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.iplass.mtp.entity.query.condition.expr.And;
import org.iplass.mtp.entity.query.condition.predicate.Like;
import org.iplass.mtp.entity.query.condition.predicate.Like.MatchPattern;
import org.iplass.mtp.mdc.command.view.entityview.search.DetailSearchCondition;
import org.iplass.mtp.mdc.command.view.entityview.search.search.SearchParameter;
import org.iplass.mtp.mdc.view.entityview.search.SearchQueryContext;
import org.iplass.mtp.mdc.view.entityview.search.SearchQueryInterceptor;
import org.iplass.mtp.mdc.view.entityview.search.SearchType;
import org.iplass.mtp.mdc.view.entityview.search.SearchViewConstants;
import org.iplass.mtp.mdc.view.entityview.search.definition.element.MdcSearchConditionElement;
import org.iplass.mtp.mdc.view.entityview.search.definition.element.property.MdcSearchConditionProperty;
import org.iplass.mtp.mdc.view.entityview.definition.editor.search.condition.MdcSearchConditionPropertyEditor;
import org.iplass.mtp.mdc.view.entityview.definition.editor.search.condition.MdcSearchConditionScriptPropertyEditor;
import org.iplass.mtp.mdc.view.entityview.definition.editor.search.condition.MdcSearchConditionTemplatePropertyEditor;

public class TestSearchQueryInterceptor implements SearchQueryInterceptor {
    @Override
    public void beforeSearch(SearchQueryContext context) {
        // 入力された検索条件を取得
        SearchParameter param = (SearchParameter) context.getRequest().getAttribute(SearchViewConstants.PARAMS);

        List<MdcSearchConditionElement> elements = context.getSearchViewDefinition().getSearchConditionSection()
                .getElements();
        
        List<MdcSearchConditionProperty> propertyElements = new ArrayList<>();
        for (MdcSearchConditionElement element : elements) {
            if (element instanceof MdcSearchConditionProperty) {
                propertyElements.add((MdcSearchConditionProperty) element);
            }
        }

        SearchType searchType = SearchType.resolveSearchType(param.getSearchCondition().getSearchType());

        if (searchType.equals(SearchType.NORMAL)) {
            // 通常検索の場合

            // 通常検索で入力した検索条件を取得
            Map<String, Object> inputCondNormal = param.getSearchCondition().getNormal();
            // 検索条件を取得する場合は以下のように対象のプロパティを取得して処理を実行する
            for (MdcSearchConditionProperty property : propertyElements) {
                MdcSearchConditionPropertyEditor editor = property.getEditor();
                // 例)
                // MdcSearchConditionTemplatePropertyEditorかMdcSearchConditionScriptPropertyEditorの場合の条件を作成してクエリーのWhere句に追加
                if (editor instanceof MdcSearchConditionTemplatePropertyEditor
                        || editor instanceof MdcSearchConditionScriptPropertyEditor) {
                    if (context.getQuery().getWhere().getCondition() == null) {
                        And and = new And();
                        context.getQuery().getWhere().setCondition(and);
                    }
                    ((And) context.getQuery().getWhere().getCondition()).and(new Like(property.getPropertyName(),
                            (String) inputCondNormal.get(property.getPropertyName()), MatchPattern.PARTIAL));
                } else {
                    continue;
                }
            }
        } else if (searchType.equals(SearchType.DETAIL)) {
            // 詳細検索の場合

            // 詳細検索で入力した検索条件を取得
            DetailSearchCondition inputCondDetail = param.getSearchCondition().getDetail();

            
        } else if (searchType.equals(SearchType.FIXED)) {
            // 定型検索の場合

            // 定型検索で入力した検索条件を取得
            String inputCondFixed = param.getSearchCondition().getFixed();

 
        }

        // 特権実行する場合
        context.setDoPrivileged(true);

        // Entity権限における限定条件を適用せずに検索を実行する参照先名
        // 特権実行する場合は無視されます
        context.setWithoutConditionReferenceName("ref1", "ref2");
    }
}
----

.クエリのカスタマイズ
beforeSearch内ではクエリをカスタマイズし、SELECT句の対象を追加したり、WHERE句に条件を追加したりすることが可能です。

また、 `org.iplass.mtp.entity.query.ASTTransformer` インターフェースを利用することで、クエリに設定されている式自体をカスタマイズすることも可能になります。
ASTTransformerはデザインパターンのVisitorパターンを利用してクエリを解析します。

以下は検索条件を取り出し、特定の項目に対する条件が指定されていた場合に値を書き換えるサンプルになります。
下記サンプルでは、ASTTransformerの実装クラスのASTTransformerSupportを継承した独自の無名クラスを作成し、特定のEQLの条件クラスが来た場合にクエリをカスタマイズしています。

[source,java]
----
Condition condition = query.getWhere().getCondition();
if (condition != null) {
	condition.accept(new ASTTransformerSupport() {

		@Override
		public ASTNode visit(Equals equals) {
			encriptName(equals);
			return super.visit(equals);
		}

		@Override
		public ASTNode visit(NotEquals notEquals) {
			encriptName(notEquals);
			return super.visit(notEquals);
		}

		@Override
		public ASTNode visit(Greater greater) {
			encriptName(greater);
			return super.visit(greater);
		}

		@Override
		public ASTNode visit(GreaterEqual greaterEqual) {
			encriptName(greaterEqual);
			return super.visit(greaterEqual);
		}

		@Override
		public ASTNode visit(Lesser lesser) {
			encriptName(lesser);
			return super.visit(lesser);
		}

		@Override
		public ASTNode visit(LesserEqual lesserEqual) {
			encriptName(lesserEqual);
			return super.visit(lesserEqual);
		}
	});
}


private void encriptName(ComparisonPredicate predicate) {
	if (predicate.getPropertyName().equals("name")
        && predicate.getValue() != null
        && predicate.getValue() instanceof Literal) {
		Literal literal = (Literal) predicate.getValue();
		if (literal.getValue() instanceof String) {
			String value = (String) literal.getValue();
			predicate.setValue(new Literal(CipherUtil.encrypt(value)));
		}
	}
}
----

[[MdcCustomize_Upload]]
=== カスタムアップロード処理
検索画面でのアップロード時に独自の処理を組み込むことができます。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスをアップロードボタン設定の `カスタムアップロード処理クラス名` に指定します。

====
org.iplass.mtp.mdc.view.entityview.search.SearchFormFileUploadInterrupter
====

.処理一覧
[cols="1,1,1,2a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

.4+|dataMapping
|row(int)
.4+|なし
.4+|アップロードファイルから登録用のデータをマッピングします。

CsvRegistrationType で登録の種類を判断できます。

INSERT:: 新規追加。
UPDATE:: 更新。
DELETE:: 削除。

|Entity
|EntityDefinition
|CsvRegistrationType

.4+|beforeRegister
|row(int)
.4+|List<ValidateError>
.4+|当該メソッド内に設定した処理内容が、Entityの登録・更新・削除前に実施されます。
|Entity
|EntityDefinition
|CsvRegistrationType

.4+|afterRegister
|row(int)
.4+|List<ValidateError>
.4+|当該メソッド内に設定した処理内容が、Entityの登録・更新・削除後に実施されます。
|Entity
|EntityDefinition
|CsvRegistrationType

|insertOption
|InsertOption
|InsertOption
|新規登録時のInsertOptionを制御します。

標準の登録対象プロパティの判定は、アップロードファイルのヘッダ情報または検索条件設定の `アップロード登録項目` により制御されます。登録対象以外のプロパティは null 値が設定されます。

|updateOption
|UpdateOption
|UpdateOption
|更新時のUpdateOptionを制御します。
標準の更新対象プロパティの判定は、アップロードファイルのヘッダ情報または検索条件設定の `アップロード更新項目` により制御されます。

|deleteOption
|DeleteOption
|DeleteOption
|削除時のDeleteOptionを制御します。

|columnNameMap
|EntityDefinition
|Map<String, String>
|ヘッダ名をカスタマイズしたい場合に指定します。keyをプロパティ名、valueを出力列名としてマッピングを定義します。
nullを返す場合、またはMapに該当がない場合は、標準の形式で出力します。

.2+|sampleFileData
|EntityDefinition
.2+|List<Entity>
.2+|サンプルファイルとして出力したいEntityデータを返します。引数で出力対象のプロパティが渡されます。nullを返す場合、プロパティ型に応じてランダムな値を出力します。
|List<PropertyDefinition>

|===

カスタムアップロード処理の各メソッドは以下のように呼ばれます。

. ファイルデータの1行分を読み込みます。
. `_useCtrl` フラグの有無、ユニークキー値と既存データの有無により、新規、更新、削除を判断します。
. `dataMapping` が実行され、処理対象のEntityが作成されます。
. `beforeRegister` が実行されます。
. Entityを登録します。 +
新規の場合:: `insertOption` が実行されます。
更新の場合:: `updateOption` が実行されます。
削除の場合:: `deleteOption` が実行されます。
. `afterRegister` が実行されます。

`beforeRegister` `afterRegister` でValidateErrorを返した場合、
またはいずれかでエラーが発生した場合、ロールバックされます。
`beforeRegister` でValidateErrorを返した場合にも登録処理は実行しませんが、
 `afterRegister` 処理は呼び出します。

.ヘッダのカスタマイズ
`columnNameMap` を実装することで、ヘッダを変更することが可能です。
Upload形式のダウンロード、サンプルダウンロード、アップロード処理時に参照します。

[source,java]
----
import java.util.Map;
import java.util.stream.Collectors;

import org.iplass.mtp.entity.definition.EntityDefinition;
import org.iplass.mtp.mdc.view.entityview.search.SearchFormFileUploadInterrupter;

public class SampleSearchFormFileUploadInterrupter implements SearchFormFileUploadInterrupter {

	@Override
	public Map<String, String> columnNameMap(EntityDefinition definition) {

		// 列名を表示名だけで出力する
		return definition.getPropertyList().stream()
			.collect(Collectors.toMap(
					property -> property.getName(),
					property -> property.getDisplayName()));
	}

}
----

[[MdcCustomize_Delete]]
=== カスタム一括削除処理
一括削除処理で複数のEntityに対する一括操作時に独自の処理を組み込むことができます。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを検索結果のカスタム一括削除処理クラス名に指定します。

====
org.iplass.mtp.mdc.view.entityview.search.delete.DeleteListInterceptor
====

.処理一覧
[cols="1,1,1,1a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

|beforeDelete
|DeleteListContext
|なし
|削除前処理を行います。

|afterDelete
|DeleteListContext
|なし
|削除後処理を行います。

|===

[[MdcCustomize_Load]]
=== カスタムロード処理
詳細表示、編集画面でEntityのロード時に独自の処理を組み込むことができます。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを詳細・編集画面のカスタムロード処理クラス名に指定します。

====
org.iplass.mtp.mdc.view.entityview.detail.load.LoadEntityInterceptor
====

.処理一覧
[cols="1,1,1,1a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

|beforeLoadEntity
|LoadEntityContext
|なし
|ロード前処理を行います。
詳細・編集画面の表示時や、登録、更新時の登録済データ取得時に呼ばれます。
`LoadOption` のカスタマイズや特権実行の指定が可能です。

.2+|afterLoadEntity
|LoadEntityContext
.2+|Entity
.2+|ロード後処理を行います。
ロードされたエンティティデータをカスタマイズすることが可能です。
|Entity

.2+|beforeLoadMappedByReference
|LoadEntityContext
.2+|なし
.2+|データ登録時の被参照プロパティのロード前処理を行います。
`LoadOption` のカスタマイズや特権実行の指定が可能です。
|ReferenceProperty

.3+|afterLoadMappedByReference
|LoadEntityContext
.3+|Entity
.3+|被参照プロパティのロード後処理を行います。
ロードされたエンティティデータをカスタマイズすることが可能です。
|ReferenceProperty
|Entity

|===

.LoadMode
`LoadEntityContext#getLoadMode()` からロードのタイミングを取得できます。

====
VIEW:: 詳細画面表示時
EDIT:: 編集画面表示時
BEFORE_UPDATE:: 更新処理、初期ロード時(表示判定用)
UPDATE_MAPPEDBY:: 更新処理、被参照対象ロード時
COPY:: コピー処理、コピー元データロード時(DEEP以外)
BEFORE_DELETE:: 削除処理、対象ロード時
BEFORE_LOCK:: ロック、ロック解除処理、初期ロード時(ボタン表示判定用)
====


[[MdcCustomize_Save]]
=== カスタム保存処理
編集画面での登録・更新時に独自の処理を組み込むことができます。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを詳細・編集画面のカスタム登録処理クラス名に指定します。

====
org.iplass.mtp.mdc.view.entityview.detail.save.SaveEntityInterceptor
====

.処理一覧
[cols="1,1,1,1a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

|dataMapping
|SaveEntityContext
|なし
|登録用のデータにリクエストのデータをマッピングします。
リクエストデータから生成された登録用エンティティデータをカスタマイズすることが可能です。

|isSpecifyAllProperties
|SaveEntityContext
|boolean
|更新対象の範囲を制御します。 `UpdateOption` のカスタマイズを行います。

true:: getAdditionalPropertiesで設定した戻り値のみを更新対象とする
false:: 汎用登録処理が自動で設定した更新対象に `getAdditionalProperties` の戻り値を追加する

デフォルトは `false` です。

|getAdditionalProperties
|SaveEntityContext
|Set<String>
|更新対象のプロパティを指定します。
更新対象のプロパティは `isSpecifyAllProperties` により対象範囲が変わります。

|beforeRegister
|SaveEntityContext
|List<ValidateError>
|当該メソッド内に設定した処理内容が、エンティティの登録・更新前に実施されます。
戻り値としてValidateErrorを返すと、登録処理を行いません。

|afterRegister
|SaveEntityContext
|List<ValidateError>
|当該メソッド内に設定した処理内容が、エンティティの登録・更新後に実施されます。
戻り値としてValidateErrorを返すと、保存データはロールバックされます。

|===

.登録処理の順序
カスタム登録処理の各メソッドは以下のように呼ばれます。

. リクエストデータから登録用のエンティティデータが作成されます。
. カスタム登録処理の `dataMapping` が実行されます。
. 参照型のデータを登録します。
. カスタム登録処理の `beforeRegister` が実行されます。
. エンティティ(本データ)を登録(insert)または更新(update)します。 +
更新時は、 `isSpecifyAllProperties` `getAdditionalProperties` の設定により `UpdateOption` を制御します。
. 被参照の参照型のデータを登録します。
. カスタム登録処理の `afterRegister` が実行されます。

いずれかでエラーが発生した場合、ロールバックされます。

.参照データの登録
参照データの追加や編集時に表示される編集画面での保存処理では、実際の登録処理は実行せず、 `validate` 処理のみを行います。
本データの保存時に、参照データ１件ごとに登録処理が実行されます。参照データは、 `ReferencePropertyEditor` で指定されているView定義の設定によって上記の登録処理が同様に行われます。

[[MdcCustomize_MassReferenceSearch]]
=== カスタム検索処理（大量データ参照セクション）
詳細画面の大量データ参照セクションで、検索処理の実行前後に独自の処理を組み込むことができます。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを大量データ参照セクションのEQLカスタム処理クラス名に指定します。

====
org.iplass.mtp.mdc.view.entityview.detail.massreference.MassReferenceSearchQueryInterceptor
====

.処理一覧
[cols="1,1,1,1a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

|beforeSearch
|MassReferenceSearchQueryContext
|なし
|検索前処理を行います。

.2+|afterSearch
|MassReferenceSearchQueryContext
.2+|なし
.2+|検索後処理を行います。afterSearchではEntity1レコード毎に処理が呼ばれます。
|Entity

.2+|afterSearchComplete
|MassReferenceSearchQueryContext
.2+|なし
.2+|検索完了処理を行います。
|List<Entity>

|===

[[MdcCustomize_BulkUpdateLoad]]
=== カスタムロード(単一項目)処理
一括更新画面(単一項目)でEntityのロード時に独自の処理を組み込むことができます。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを検索結果セクションの設定のカスタムロード処理クラス名に指定します。

====
org.iplass.mtp.mdc.view.entityview.bulk.load.BulkUpdateLoadEntityInterceptor
====

.処理一覧
[cols="1,1,1,1a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

|beforeLoadEntity
|BulkUpdateLoadEntityContext
|なし
|ロード前処理を行います。
一括更新時の登録済データ取得時に呼ばれます。
`LoadOption` のカスタマイズや特権実行の指定が可能です。

.2+|afterLoadEntity
|BulkUpdateLoadEntityContext
.2+|Entity
.2+|ロード後処理を行います。
ロードされたエンティティデータをカスタマイズすることが可能です。
|Entity

|===

[[MdcCustomize_BulkUpdate]]
=== カスタム一括更新(単一項目)処理
一括更新画面(単一項目)での更新時に独自の処理を組み込むことができます。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを検索結果セクションの設定のカスタム登録処理クラス名に指定します。

====
org.iplass.mtp.mdc.view.entityview.bulk.save.BulkUpdateInterceptor
====

.処理一覧
[cols="1,1,1,1a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

|dataMapping
|BulkUpdateContext
|なし
|登録用のデータにリクエストのデータをマッピングします。
リクエストデータから生成された登録用エンティティデータをカスタマイズすることが可能です。

|isSpecifyAllProperties
|BulkUpdateContext
|boolean
|更新対象の範囲を制御します。 `UpdateOption` のカスタマイズを行います。

true:: getAdditionalPropertiesで設定した戻り値のみを更新対象とする
false:: 汎用登録処理が自動で設定した更新対象に `getAdditionalProperties` の戻り値を追加する

デフォルトは `false` です。

|getAdditionalProperties
|BulkUpdateContext
|Set<String>
|更新対象のプロパティを指定します。
更新対象のプロパティは `isSpecifyAllProperties` により対象範囲が変わります。

|beforeBulkUpdate
|BulkUpdateContext
|List<ValidateError>
|当該メソッド内に設定した処理内容が、エンティティの登録・更新前に実施されます。
戻り値としてValidateErrorを返すと、登録処理を行いません。

|afterBulkUpdate
|BulkUpdateContext
|List<ValidateError>
|当該メソッド内に設定した処理内容が、エンティティの登録・更新後に実施されます。
戻り値としてValidateErrorを返すと、保存データはロールバックされます。

|===

.登録処理の順序
カスタム登録処理の各メソッドは以下のように呼ばれます。

. リクエストデータから登録用のエンティティデータが作成されます。
. カスタム登録処理の `dataMapping` が実行されます。
. カスタム登録処理の `beforeBulkUpdate` が実行されます。
. 一括更新対象をループ処理。
. 参照型のデータを登録します。
. エンティティ(本データ)を登録(update)します。 +
更新時は、 `isSpecifyAllProperties` `getAdditionalProperties` の設定により `UpdateOption` を制御します。
. ループ処理完了、カスタム登録処理の `afterBulkUpdate` が実行されます。

処理1-6でエラーが発生した場合、ロールバックされます。

.参照データの登録
参照データの追加や編集時に表示される編集画面での保存処理では、実際の登録処理は実行せず、 `validate` 処理のみを行います。
本データの保存時に、参照データ１件ごとに登録処理が実行されます。参照データは、 `ReferencePropertyEditor` で指定されているView定義の設定によって上記の登録処理が同様に行われます。

[[MdcCustomize_BulkViewLoad]]
=== カスタムロード(複数項目)処理
一括更新画面(複数項目)でEntityのロード時に独自の処理を組み込むことができます。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを一括更新画面の設定のカスタムロード処理クラス名に指定します。

====
org.iplass.mtp.mdc.view.entityview.bulk.load.BulkViewLoadEntityInterceptor
====

.処理一覧
[cols="1,1,1,1a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

|beforeLoadEntity
|BulkViewLoadEntityContext
|なし
|ロード前処理を行います。
一括更新時の登録済データ取得時に呼ばれます。
`LoadOption` のカスタマイズや特権実行の指定が可能です。

.2+|afterLoadEntity
|BulkViewLoadEntityContext
.2+|Entity
.2+|ロード後処理を行います。
ロードされたエンティティデータをカスタマイズすることが可能です。
|Entity

|===

[[MdcCustomize_BulkViewUpdate]]
=== カスタム一括更新(複数項目)処理
一括更新画面(複数項目)での更新時に独自の処理を組み込むことができます。

以下のインターフェースを実装したJavaクラスまたはUtilityClassを作成してください。
作成したクラスを一括更新画面のカスタム登録処理クラス名に指定します。

====
org.iplass.mtp.mdc.view.entityview.bulk.save.BulkViewInterceptor
====

.処理一覧
[cols="1,1,1,1a",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

|dataMapping
|BulkViewContext
|なし
|登録用のデータにリクエストのデータをマッピングします。
リクエストデータから生成された登録用エンティティデータをカスタマイズすることが可能です。

|isSpecifyAllProperties
|BulkViewContext
|boolean
|更新対象の範囲を制御します。 `UpdateOption` のカスタマイズを行います。

true:: getAdditionalPropertiesで設定した戻り値のみを更新対象とする
false:: 汎用登録処理が自動で設定した更新対象に `getAdditionalProperties` の戻り値を追加する

デフォルトは `false` です。

|getAdditionalProperties
|BulkViewContext
|Set<String>
|更新対象のプロパティを指定します。
更新対象のプロパティは `isSpecifyAllProperties` により対象範囲が変わります。

|beforeBulkUpdate
|BulkViewContext
|List<ValidateError>
|当該メソッド内に設定した処理内容が、エンティティの登録・更新前に実施されます。
戻り値としてValidateErrorを返すと、登録処理を行いません。

|afterBulkUpdate
|BulkViewContext
|List<ValidateError>
|当該メソッド内に設定した処理内容が、エンティティの登録・更新後に実施されます。
戻り値としてValidateErrorを返すと、保存データはロールバックされます。

|===

.登録処理の順序
カスタム登録処理の各メソッドは以下のように呼ばれます。

. リクエストデータから登録用のエンティティデータが作成されます。
. カスタム登録処理の `dataMapping` が実行されます。
. カスタム登録処理の `beforeBulkUpdate` が実行されます。
. 一括更新対象をループ処理。
. 参照型のデータを登録します。
. エンティティ(本データ)を登録(update)します。 +
更新時は、 `isSpecifyAllProperties` `getAdditionalProperties` の設定により `UpdateOption` を制御します。
. ループ処理完了、カスタム登録処理の `afterBulkUpdate` が実行されます。

処理1-6でエラーが発生した場合、ロールバックされます。

.参照データの登録
参照データの追加や編集時に表示される編集画面での保存処理では、実際の登録処理は実行せず、 `validate` 処理のみを行います。
本データの保存時に、参照データ１件ごとに登録処理が実行されます。参照データは、 `ReferencePropertyEditor` で指定されているView定義の設定によって上記の登録処理が同様に行われます。

