[[OpenApiService]]
=== OpenApiService
This is a service for managing functions related to OpenAPI.

==== Interface Name
----
org.iplass.mtp.impl.webapi.openapi.OpenApiService
----

==== Implementing Class
----
org.iplass.mtp.impl.webapi.openapi.OpenApiService
----

==== OpenApiService Configuration
OpenApiService can be configured with the following items.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| infoTitleOfExport | String | The value of info.title when exporting OpenAPI.
| infoVersionOfExport | String | The value of info.version when exporting OpenAPI.
| infoDescriptionOfExport | String | The value of info.description when exporting OpenAPI.
| propertySchema | <<openapiservice_PropertySchema>>, Multiple | The property schema definitions used when exporting OpenAPI.
|===

[[openapiservice_PropertySchema]]
.PropertySchema
class is specified as org.iplass.mtp.impl.webapi.openapi.schema.PropertySchema.

When generating JsonSchema from Java class information, fixed schemas can be set. +
The schema determination method prioritizes cases where the class-property combination matches, followed by cases where only the property matches. +
The following items can be configured.

[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| className | String | The target class name for JsonSchema output.
| propertyName | String, Required | The target property name for JsonSchema output.
| schemaType | String, Required a| The type of the schema.

Configurable schema types::
- `STRING`
- `INTEGER`
- `BOOLEAN`
- `DATE`
- `DATETIME`

| description | String | The description of the schema.
| format | String | The format of the schema.
|===


===== Example
[source,xml]
----
<service>
	<interface>org.iplass.mtp.impl.webapi.openapi.OpenApiService</interface>
    <class>org.iplass.mtp.impl.webapi.openapi.OpenApiService</class>

    <property name="infoTitleOfExport" value="iPLAss WebAPI, EntityCRUDApi OpenAPI Spec" />
    <property name="infoVersionOfExport" value="1.0.0" />
    <property name="infoDescriptionOfExport" value="iPLAss WebAPI and EntityCRUDApi OpenAPI Specification" />
    <property name="propertySchema" class="org.iplass.mtp.impl.webapi.openapi.schema.PropertySchema">
        <property name="propertyName" value="@class" />
        <property name="schemaType" value="STRING" />
        <property name="description" value="Fully qualified class name is set as the value. This property is used to identify the concrete class when the type of parameter or response is an interface or abstract class." />
    </property>
</service>
----
