[[ReportingEngineService]]
=== ReportingEngineService
This service manages receipt reports output.

==== Interface Name
----
org.iplass.mtp.impl.report.ReportingEngineService
----

==== Implementing Class
----
org.iplass.mtp.impl.report.ReportingEngineServiceImpl
----

==== The settings of ReportingEngineService
ReportingEngineService can be configured with the following items.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| reportingEngine | <<ReportingEngine>>, Multiple | The settings of the report generation engine.
|===

[[ReportingEngine]]
.ReportingEngine
Please specify the implementing class of org.iplass.mtp.impl.report.ReportingEngine to the class to the class.

As the standard implementation, the following ReportingEngine are provided.

* <<JasperReportingEngine>>
* <<PoiReportingEngine>>
* <<JxlsReportingEngine>>

[[JasperReportingEngine]]
.JasperReportingEngine
An engine for creating reports using Jasper Report.

Please specify org.iplass.mtp.impl.report.JasperReportingEngine to the class.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| supportFiles | String, Multiple |Specify the type of the supporting files.
|===

[[PoiReportingEngine]]
.PoiReportingEngine
An engine for creating forms using Apache POI.

Please specify org.iplass.mtp.impl.report.PoiReportingEngine to the class.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| supportFiles | String, Multiple | Specify the type of the supporting files.
|===

[[JxlsReportingEngine]]
.JxlsReportingEngine
An engine for creating forms using JXLS.

Please specify org.iplass.mtp.impl.report.JxlsReportingEngine to the class.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| supportFiles | String, Multiple | Specify the type of the supporting files. If PDF_JXLS is specified, a PDF is output using the PDF conversion service (<<PdfConversionService>>).
|===

===== Example
[source,xml]
----
<service>
	<interface>org.iplass.mtp.impl.report.ReportingEngineService</interface>
	<class>org.iplass.mtp.impl.report.ReportingEngineServiceImpl</class>
	<property name="repotingEngine" class="org.iplass.mtp.impl.report.JasperReportingEngine">
		<property name="supportFiles" value="PDF"/>
		<property name="supportFiles" value="XLS"/>
		<property name="supportFiles" value="XLSX"/>
	</property>
	<property name="repotingEngine" class="org.iplass.mtp.impl.report.PoiReportingEngine">
		<property name="supportFiles" value="XLS_POI"/>
		<property name="supportFiles" value="XLSX_POI"/>
		<property name="supportFiles" value="XLSX_SXSSF_POI"/>
	</property>
	<property name="repotingEngine" class="org.iplass.mtp.impl.report.JxlsReportingEngine">
		<property name="supportFiles" value="XLS_JXLS"/>
		<property name="supportFiles" value="XLSX_JXLS"/>
		<property name="supportFiles" value="XLSX_SXSSF_JXLS"/>
		<property name="supportFiles" value="PDF_JXLS"/>
	</property>
</service>
----

[[PdfConversionService]]
=== PdfConversionService
A service that converts Excel to PDF, used for PDF (PDF_JXLS) output of JXLS reports.
This service is registered as an independent service in the service-config.
The implementation can be replaced by rewriting the class definition in the service-config (the same switching structure as Lucene/Elasticsearch of the FulltextSearchService for full-text search).

==== Interface Name
----
org.iplass.mtp.impl.report.converter.PdfConversionService
----

==== Implementing Class
.PDF conversion using Gotenberg
----
org.iplass.mtp.impl.report.converter.GotenbergPdfConversionService
----

==== The settings of GotenbergPdfConversionService
Configure the items for PDF conversion using Gotenberg.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| baseUrl | String | The endpoint URL of the conversion service. `http://localhost:3000` is set in the default service-config.
| connectTimeoutSeconds | int | The connection timeout (in seconds) for requests to the conversion service. The default value is 5.
| requestTimeoutSeconds | int | The request timeout (in seconds) for requests to the conversion service. The default value is 60. Adjust this value according to the number of pages and the amount of images of the report.
| maxRetries | int | The number of retries when a request to the conversion service fails. The default value is 0.
| retryIntervalMillis | long | The retry interval (in milliseconds) when retrying. The default value is 1000.
|===

===== Example
[source,xml]
----
<service>
	<interface>org.iplass.mtp.impl.report.converter.PdfConversionService</interface>
	<class>org.iplass.mtp.impl.report.converter.GotenbergPdfConversionService</class>
	<property name="baseUrl" value="http://localhost:3000"/>
	<property name="connectTimeoutSeconds" value="5"/>
	<property name="requestTimeoutSeconds" value="60"/>
	<property name="maxRetries" value="0"/>
	<property name="retryIntervalMillis" value="1000"/>
</service>
----
