[[ScimIdentityProviderService]]
=== [.eeonly]#ScimIdentityProviderService#
SCIM Identity Provider 機能の動作を管理するサービスです。

==== インタフェース名
----
org.iplass.mtp.impl.webapi.scim.ScimIdentityProviderService
----

==== 実装クラス名
----
org.iplass.mtp.impl.webapi.scim.ScimIdentityProviderService
----

==== ScimIdentityProviderService の設定
ScimIdentityProviderService を設定します。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目
| 値
| 説明

| entityReference
| <<ScimEntityReference>> 、複数指定可
| SCIM リソース対象のエンティティ（mtp.auth.User, mtp.auth.Group）に対して、エンティティプロパティ設定、レスポンス作成の機能を提供します。
|===

[[ScimEntityReference]]
.ScimEntityReference
class に org.iplass.mtp.impl.webapi.scim.receive.reference.ScimEntityReference の実装クラスを指定します。

標準で以下の ScimEntityReference を提供します。

* <<ScimUserEntityReference>>
* <<ScimGroupEntityReference>>

[[ScimUserEntityReference]]
.ScimUserEntityReference
エンティティのリファレンス先が mtp.auth.User の値を解決します。

class は org.iplass.mtp.impl.webapi.scim.receive.reference.ScimUserEntityReference を指定します。
設定可能な項目はありません。

[[ScimGroupEntityReference]]
.ScimGroupEntityReference
エンティティのリファレンス先が mtp.auth.Group の値を解決します。

class は org.iplass.mtp.impl.webapi.scim.receive.reference.ScimGroupEntityReference を指定します。
設定可能な項目はありません。


===== 設定例
[source,xml]
----
<!-- SCIM Identity Provider -->
<service>
    <interface>org.iplass.mtp.impl.webapi.scim.ScimIdentityProviderService</interface>
    <class>org.iplass.mtp.impl.webapi.scim.ScimIdentityProviderService</class>
    
    <!-- エンティティのリファレンスプロパティ解決機能。User, Group はデフォルト定義 -->
    <property name="entityReference" class="org.iplass.mtp.impl.webapi.scim.receive.reference.ScimUserEntityReference" />
    <property name="entityReference" class="org.iplass.mtp.impl.webapi.scim.receive.reference.ScimGroupEntityReference" />
</service>
----
