[[WebApiObjectMapperService]]
=== WebApiObjectMapperService
WebApiのJSON出力時のObjectMapper定義を行うサービスです。

==== インタフェース名
----
org.iplass.mtp.impl.webapi.jackson.WebApiObjectMapperService
----

==== 実装クラス名
----
org.iplass.mtp.impl.webapi.jackson.WebApiObjectMapperService
----

==== WebApiObjectMapperServiceの設定
WebApiObjectMapperServiceを設定します。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| typeMap | <<WebApiParameterType>>、複数指定可 | パラメータの型と対応するクラスの設定。
| mixin | <<MixinConfig>>、複数指定可 | 出力内容を調整する対象。
| writeNullMapValues | boolean | null値を持つマップエントリをjsonに出力するか。
| writeNullValues | boolean | nullの項目をjsonに出力するか。
| escapeNonAscii | boolean | WebApiの結果をjsonで返却する際に、ascii以外をすべてエスケープする形で出力するか。
|===

[[WebApiParameterType]]
.WebApiParameterType
classはorg.iplass.mtp.impl.webapi.jackson.WebApiParameterTypeを指定します。
以下の項目を設定可能です。

[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| typeName | String | 型の名前。
| className | String | 型に対応するクラス名。
|===

[[MixinConfig]]
.MixinConfig
classはorg.iplass.mtp.impl.webapi.jackson.MixinConfigを指定します。
以下の項目を設定可能です。

[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| target | String | jacksonで出力内容を調整する対象のクラス。
| mixinSource | String | `target` に指定したクラスの表現を調整するためのMix-InのAnnotation。
|===

===== 設定例
[source,xml]
----
<service>
	<interface>org.iplass.mtp.impl.webapi.jackson.WebApiObjectMapperService</interface>
	<property name="mixin">
		<property name="target" value="org.iplass.mtp.entity.GenericEntity" />
		<property name="mixinSource" value="org.iplass.mtp.impl.webapi.jackson.MixinEntity" />
	</property>
	<property name="mixin">
		<property name="target" value="org.iplass.mtp.entity.Entity" />
		<property name="mixinSource" value="org.iplass.mtp.impl.webapi.jackson.MixinEntity" />
	</property>
	<property name="mixin">
		<property name="target" value="org.iplass.mtp.definition.binary.BinaryDefinition" />
		<property name="mixinSource" value="org.iplass.mtp.impl.webapi.jackson.MixinBinaryDefinition" />
	</property>

	<property name="parameterType">
		<property name="typeName" value="entity" />
		<property name="className" value="org.iplass.mtp.entity.GenericEntity" />
	</property>
	<property name="parameterType">
		<property name="typeName" value="decimal" />
		<property name="className" value="java.math.BigDecimal" />
	</property>
	<property name="parameterType">
		<property name="typeName" value="binary" />
		<property name="className" value="org.iplass.mtp.entity.BinaryReference" />
	</property>
	<property name="parameterType">
		<property name="typeName" value="select" />
		<property name="className" value="org.iplass.mtp.entity.SelectValue" />
	</property>
	<property name="parameterType">
		<property name="typeName" value="boolean" />
		<property name="className" value="java.lang.Boolean" />
	</property>
	<property name="parameterType">
		<property name="typeName" value="date" />
		<property name="className" value="java.sql.Date" />
	</property>
	<property name="parameterType">
		<property name="typeName" value="dateTime" />
		<property name="className" value="java.sql.Timestamp" />
	</property>
	<property name="parameterType">
		<property name="typeName" value="float" />
		<property name="className" value="java.lang.Double" />
	</property>
	<property name="parameterType">
		<property name="typeName" value="integer" />
		<property name="className" value="java.lang.Long" />
	</property>
	<property name="parameterType">
		<property name="typeName" value="string" />
		<property name="className" value="java.lang.String" />
	</property>
	<property name="parameterType">
		<property name="typeName" value="time" />
		<property name="className" value="java.sql.Time" />
	</property>
</service>
----
