=== ユーザー管理

==== ユーザーの登録
ユーザーの登録は、 `User` エンティティを登録することで実行されます。

`User` に設定されている `UserEntityEventListener` によって、 `t_account` テーブルに連携されます。

==== ユーザー自身の編集
ログインユーザー自身でユーザー情報を編集することが可能です。汎用画面上部の「ユーザー情報変更」から実行します。

標準では、パスワードのみ変更が可能になります。

* 編集可能項目の変更 +
TopViewの設定により、変更が可能な項目を設定することができます。 +
「Toolbar Parts」の「User Maintenance」をパーツエリアにドロップします。
User Maintenance パーツの設定で、 `User` エンティティに定義されたViewを指定することで、入力可能な項目を指定します。
標準で、 `maintenance` Viewが用意されています。
+
NOTE: `admin` Viewは全てのプロパティが設定されているため、指定しないでください。 +
パスワードの保存と、ここで指定したユーザー情報の編集部分の保存処理は分かれています。 +
`maintenance` View以外でも、独自にViewを定義することでカスタマイズすることが可能です。

==== パスワードの指定登録
標準設定ではユーザー登録時、パスワードリセット時にパスワードは自動で生成されます。
場合によっては登録時に明示的にパスワードを指定したい場合もあります。
登録時にパスワードを指定したい場合には以下の設定を行います。

. 認証ポリシーの設定 +
認証ポリシーの `Create Account With Specific Password` にチェックを入れます。 +

. Detail Layoutの設定 +
ユーザー登録で利用するDetailLayoutの設定を変更します。
 `User` エンティティの詳細画面設定を開き、カスタム登録処理クラスを指定します。
+
カスタム登録処理クラスに、標準で提供されている `UserPasswordRegistrationInterrupter` を指定します。
+
====
org.iplass.gem.command.auth.UserPasswordRegistrationInterrupter
====

. パスワード項目の追加(仮想プロパティ) +
入力項目に「パスワード」を追加します。
`User` エンティティにはパスワードプロパティはありません。仮想プロパティを利用して追加します。
+
プロパティ名は `password` にしてください。
+
[cols="1,1,2a", options="header"]
|===
|項目|設定値|備考
|新規/編集時の表示可否|INSERT|登録時のみ表示させます。
|詳細画面で非表示|チェック|詳細画面では非表示にします。
|プロパティエディタ|StringPropertyEditor|Editorの設定で、表示タイプに `Password` を指定します。
|===
+
NOTE: パスワードを指定して登録する場合は、アカウントポリシーで `Create Account With Specific Password`
を有効にした認証ポリシーを選択してください。 +
`DEFAULT` 認証ポリシーで有効にしている場合は、アカウントポリシーを指定する必要はありません。

パスワードを入力して登録を実行すると、「カスタム登録処理クラス」で指定した
`UserPasswordRegistrationInterrupter` の処理によって、パスワードが指定された状態で登録されます。

==== パスワードのリセット
ユーザー情報の編集画面上からパスワードのリセットを行うことができます。

リセット時には初期パスワードが発行されます。
認証ポリシーの通知設定によりメール通知も可能になります。
また、パスワードリセットを行うとログイン失敗時のカウントがリセットされます。

==== 管理者の作成
AdminConsoleを利用するには `User` エンティティの `admin` プロパティが `true` になっている必要があります。

ただし標準のユーザー情報登録画面では `admin` プロパティの設定はできないようになっています。
予め `User` エンティティのView定義に定義されている `admin` Viewを利用するか、
新たにView定義を作成して `admin` プロパティを指定してください。

Viewを指定した汎用画面を表示するには、Menu定義で `User` エンティティに対するEntityMenuItemを作成しView Nameを指定します。
そのメニューをメニューツリーに設定します。

==== 一時ユーザーの作成
iPLAssでは一時的に利用可能となるユーザーをシステム側で作成する事が可能です。

`User` エンティティのプロパティにある `temporary` プロパティを `true` にすることで、対象ユーザーは一時ユーザーとなります。

標準のユーザー情報登録画面では `temporary` プロパティの設定はできないようになっています。
予め `User` エンティティのView定義に定義されている `admin` Viewを利用するか、
新たにView定義を作成して `temporary` プロパティを指定してください。

NOTE: 一時ユーザーは「Temporary User Cleaner」バッチのクリーニング処理で一定期間を過ぎると自動的に削除されます。 +
詳細は<<../support/index.adoc#temporary_user_cleaner, Temporary User Cleaner>>を参照してください。

==== ユーザーデータの移行
各環境間でメタデータやエンティティデータのインポート、エクスポートを実行する場合があると思いますが、
テストユーザーなどの本番環境への誤った移行を防ぐため、ツールでの移行（簡単な手順での移行）はサポートしていません。

テスト環境間等での移行を行う場合には、下記のいずれかでご対応頂くようお願い致します。

* 別途それぞれの環境でユーザーを作成する
* `User` エンティティデータ及びデータベースの `t_account` テーブルデータそのものを移行する

iPLAssではPackagingというデータ移行ツールを提供していますが、これを利用しても `t_account` については移行されません。
 `User` エンティティを移行した後に `t_account` も移行していただく必要があります。

直接INSERT文で登録、DBの機能を利用したエクスポート、インポート等、どのような方法で `t_account` を
移行していただいても問題ありません。
ただし、移行後の `User` エンティティの `tenant_id` , `oid` と `t_account` テーブルの
`tenant_id` , `oid` を一致させる必要があります。
（Packagingのインポートでoidをprefixつけて変更した場合は、その項目も洗い替えする）
 `User` エンティティの `tenant_id` , `oid` はEQL Worksheet等で確認して下さい。

.移行イメージ
テスト環境１からテスト環境２にパッケージを利用して移行する場合のイメージは以下のようになります。

[cols="1,1,1", options="header"]
|===
|テスト環境１|User|t_account
.3+||tenant_id：100|tenant_id：100
|oid：100001|oid：100001
|accountId：user0001|accountId：user0001
|===

`User` エンティティのデータをAdminConsoleのパッケージを利用しエクスポート、インポートします。

[cols="1,1,1", options="header"]
|===
|テスト環境２|User|t_account
.3+||tenant_id：001|
|oid：000001|
|accountId：user0001|
|===

インポート時に新しいテナントIDと自動採番された `oid` が付与されます。
また、 `t_account` のデータは移行されません。

続いて `t_account` のデータをDBの機能を利用しエクスポート、インポートします。

[cols="1,1,1", options="header"]
|===
|テスト環境２|User|t_account
.3+||tenant_id：001|tenant_id：100
|oid：000001|oid：100001
|accountId：user0001|accountId：user0001
|===

`tenant_id` や `oid` はそのままインポートされるため、 `User` エンティティと差異が出てしまいます。

そこで `t_account` の対象データを `User` エンティティに合わせてアップデートします。

[cols="1,1,1", options="header"]
|===
|テスト環境２|User|t_account
.3+||tenant_id：001|tenant_id：001
|oid：000001|oid：000001
|accountId：user0001|accountId：user0001
|===
