[[Template]]
== Template
画面を表示するためのプレゼンテーションロジックやリソースを表します。
Templateは実装手段、出力する内容により、いくつかの種類が存在します。
主にhtmlなどのテキストデータを出力する為のJspTemplate、GroovyTemplateやバイナリ出力用のTemplate、帳票出力用のTemplateなどが存在します。
JspTemplateは実装手段としてJSPを利用します。GroovyTemplateはGroovyベースのJSPライクなDSLで記述します。

[[Template-Admin]]
=== Template定義（AdminConsole）
AdminConsoleを利用してTemplateを定義する方法を説明します。

==== Templateの作成
メニューを右クリックし「テンプレートを作成する」を選択します。 +
この際、作成するTemplateの種類を指定します。

==== Templateの設定項目
Templateの設定画面は３つのパートに分かれます。

===== 共通設定
[cols="1,3",format="dsv",options="header"]
|===
項目:内容
Name: Template定義名です。
Display Name: 表示名です。現状、AdminConsole上でのみ利用されます。
Description: Templateの概要文です。現状、AdminConsole上でのみ利用されます。
|===

===== Template固有設定
[cols="1,3",format="psv",options="header"]
|===
|項目|内容
|Content Type|必要に応じて対象TemplateのContent Typeを設定します。 +
(例) `text/html; charset=utf-8`
|Type|
Templateの種類を設定します。 +
詳細は <<Template-Types,Templateの種類>> を参照してください。
|Layout Action a|
Layout Actionを設定します。 +
Layout Actionについては、 <<Template-Componentization, Templateの部品化>> を参照してください。
|Path|（TypeがJSPの場合） +
JSPのパスを指定します。
|Source |（TypeがGroovyTemplate、Html(Text Resource)もしくは[.eeonly]#Vue.js SFC#の場合） +
ソースコードを直接記述します。
|File |（TypeがBinaryの場合） +
ファイルを指定します。
|===

===== 多言語設定
言語毎にTemplate定義を異なるものに設定することが可能です。

[cols="1,3",format="dsv",options="header"]
|===
項目:内容
Language:言語設定を行います。
そのほかの項目:Templateの種別毎に、指定されたLanguageに対応する項目を設定可能です。
|===

[[Template-Types]]
=== Templateの種類

==== JSP
Templateの実装にJSPを利用します。 +
PathにJSPファイルへのパスを指定します。
iPLAssが提供するカスタムタグ、EL関数を利用することが可能です。
詳細は、 <<JSPTag-EL,JSPカスタムタグ・EL関数>> を参照してください。

==== GroovyTemplate
Templateの実装にGroovyTemplateを利用します。 +
Sourceにコードを直接記述します。
GroovyTemplateの記法は <<groovytemplate,GroovyTemplate>> を参照してください。

==== Html(Text Resource)
Htmlなどの静的なテキストを出力します。 +
適切なContent Typeを指定した上で、Sourceに直接記述します。

==== [.eeonly]#Vue.js SFC#
Templateの実装にVue.jsのSingle File Componentを利用します。 +
[.eeonly]#MDCモジュール# でのみ利用可能です。 +
詳細については link:../../storybook/index.html?path=/docs/開発者ドキュメント-オリジナルテンプレート[オリジナルテンプレート^] を参照してください。

==== Binary
テキスト以外の静的なバイナリデータを出力します。 +
適切なContent Typeを指定した上で、ファイルをアップロードします。

NOTE: Binaryの場合、Layout Actionは設定できません。

NOTE: Template定義のバイナリデータはメモリ内にキャッシュされます。大きなサイズのバイナリデータを出力したい場合は、 <<StaticResource,静的リソース>> や  <<Action,Action>> の実行結果：Streamなどを利用してください。

==== Report
ExcelやPDFを出力します。 +
詳細は <<../report/index.adoc#,帳票出力（Jasper/JXLS/POI）>> を参照してください。

[[Template-Componentization]]
=== Templateの部品化
Templateの一部分をパーツとして切り出し別のTemplateに組み込んだり、Templateに共通のヘッダー・フッターを切り出して、共通のレイアウトとして定義することが可能です。

==== include（パーツの組み込み）
JSPと同様、Template内に、別に定義されたTemplate/Actionを組み込む（includeする）ことが可能です。
Actionをincludeした場合は、そのActionに紐付けされているCommandの処理も実行されます。

JSPでincludeを行う場合、iPLAssが提供するカスタムタグを呼び出します。

.JSPにおけるincludeのサンプル
[source,jsp]
----
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib prefix="m" uri="http://iplass.org/tags/mtp"%> <1>
<!DOCTYPE html>
<html>
 :
 :
<body>

    <div>
        <p>This is main Contents.</p>
    </div>
    <div>
        <p>include action.</p>
        <m:include action="your/action/name" /> <2>
    </div>
    <div>
        <p>include template.</p>
        <m:include template="your/template/name" /> <3>
    </div>
:
:
</body>
</html>
----
<1> iPLAssの提供するカスタムタグライブラリを定義します
<2> actionをincludeする場合はタグ属性actionにAction名を指定します
<3> templateをincludeする場合はタグ属性templateにTemplate名を指定します

GroovyTemplateでincludeする場合はinclude/includeTemplate関数を呼び出します。

.GroovyTemplateにおけるincludeのサンプル
[source,html]
----
<!DOCTYPE html>
<html>
 :
 :
<body>

    <div>
        <p>This is main Contents.</p>
    </div>
    <div>
        <p>include action.</p>
        <%include("your/action/name")%> <1>
    </div>
    <div>
        <p>include template.</p>
        <%includeTemplate("your/template/name")%> <2>
    </div>
:
:
</body>
</html>
----
<1> actionをincludeする場合はinclude関数を呼び出します
<2> templateをincludeする場合はincludeTemplate関数を呼び出します


==== LayoutAction（レイアウトの適用）
includeは、Template内にパーツを組み込むための手法ですが、LayoutActionは、Templateの外側にレイアウトを適用する為の仕組みです。
レイアウト（ヘッダやフッター）を作成して、それを、コンテンツを表現する複数のTemplateに共通的に適用することが可能です。 +

次にJSPでLayoutActionを作成し、適用する例を示します。 +

.レイアウト用Templateを作成する
[source,jsp]
----
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib prefix="m" uri="http://iplass.org/tags/mtp"%> <1>
<!DOCTYPE html>
<html>
 :
 :
<body>

    <div>
        <p>This is Header.</p>
    </div>

    <m:renderContent /> <2>

    <div>
        <p>This is Footer.</p>
    </div>
:
:
</body>
</html>
----
<1> iPLAssの提供するカスタムタグライブラリを定義します
<2> renderContentタグが指定された箇所に個別のTemplateの内容が出力されます

作成したレイアウト用Templateに紐付けたLayoutActionを作成します。
Actionの定義の方法は <<Action,Action>> を参照してください。

.コンテンツを表現するTemplateを作成する
[source,jsp]
----
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

    <div>
        <p>This is main Contents in Template A.</p>
    </div>
----

上記、TemplateにLayoutActionを適用した場合、次のように出力されます。

.html出力結果
[source,html]
----
<!DOCTYPE html>
<html>
 :
 :
<body>

    <div>
        <p>This is Header.</p>
    </div>

    <div>
        <p>This is main Contents in Template A.</p>
    </div>

    <div>
        <p>This is Footer.</p>
    </div>
:
:
</body>
</html>
----


GroovyTemplateでLayoutActionを作成する場合は、renderContent関数を利用します。

.GroovyTemplateにおけるrenderContentのサンプル
[source,html]
----
<!DOCTYPE html>
<html>
 :
 :
<body>

    <div>
        <p>This is Header.</p>
    </div>

    <%renderContent()%> <1>

    <div>
        <p>This is Footer.</p>
    </div>
:
:
</body>
</html>
----
<1> renderContent関数を呼び出した箇所に個別のTemplateの内容が出力されます


[[Template-Annotation]]
=== Template定義（アノテーション）
Javaにてカスタムロジックを実装する場合、任意のクラス、インタフェースにアノテーションでTemplate定義を設定することが可能です。なお、アノテーションで指定可能なテンプレートの種類はJSPのみとなります。

NOTE: アノテーションで定義されたTemplate定義はすべてのテナントで有効化されます。

Template定義を行うためのアノテーションは `@Template` です。
複数のTemplate定義を行う場合は、 `@Templates` を利用します。
詳細はjavadocを参照ください。

.アノテーションによる定義のサンプル
[source,java]
----
package sample;
import org.iplass.mtp.command.annotation.CommandClass;
import org.iplass.mtp.command.annotation.template.Template;
import org.iplass.mtp.command.annotation.template.Templates;

@Templates({
	@Template(name="sample/top", displayName="トップ画面", path="/jsp/sample/top.jsp", contentType="text/html; charset=utf-8"),
    @Template(name="sample/detail", displayName="詳細画面", path="/jsp/sample/detail.jsp", contentType="text/html; charset=utf-8", layoutActionName="sample/layout")
})
@CommandClass(name="sample/tutorial", displayName="チュートリアル",
        description="チュートリアルの説明です")
public class TutorialCommand implements Command {
    @Override
    public String execute(RequestContext request) {

        ：
        ：

        return "OK";
    }
}
----

Templateアノテーションは、あくまでTemplateを定義するもので、Commandとの関連付けはされません。CommandとTemplateを関連付けするためにはAction定義を行う必要があります。
