[[StaticResource]]
== Static Resource
画面で利用する各種リソースファイルを管理します。
画像やテキストなどの様々な形式のリソースや、リソースファイルを格納したZip及びJar形式の圧縮ファイルなどを扱えます。
作成したStaticResourceはTemplateのようにActionの結果として利用できます。

=== StaticResource定義

==== StaticResourceの作成
メニューを右クリックし「静的リソースを作成する」を選択します。

==== StaticResourceの設定項目

===== 固有設定

[cols="1,3a",format="psv",options="header"]
|===
|項目|内容
|Content Type|
リソースのコンテキストタイプを設定します。
（例：text/html; charset=utf-8）
ファイルが選択されている時に未設定の場合、保存後に自動的に設定されます。

.File TypeがSimpleの場合 +
レスポンスの `Content-Type` に設定されます。
|File Type|
リソースファイルのタイプを指定します。

Archive::
Zip及びJar形式の圧縮ファイルの場合に指定します。
Simple::
単一のリソースファイルの場合に指定します。

ファイルが選択されていない場合は変更できません。
|File|
File Typeで指定したリソースファイルを設定します。
リソースファイルを変更する必要がない場合は選択する必要はありません。
未指定の場合は、既に登録済のリソースファイルが利用されます。
|Entry Text Charset|
.File TypeがArchiveの場合 +
リソースのMIMEタイプがテキストの時に文字セット(Charset)を指定する場合に設定します。
|Entry Path Translator|
.File TypeがArchiveの場合 +
コマンドで指定されたEntry Pathに対し変換処理が必要な場合に設定します。
変換処理の方式を以下のタイプから選択します。

Java::
変換処理が実装されたJavaクラスの完全修飾名を設定します。
Javaクラスは `org.iplass.mtp.web.staticresource.EntryPathTranslator` インターフェースを実装する必要があります。
Prefix::
Entry Pathに付与されるプレフィックスの文字列を設定します。
Script::
変換処理をスクリプトにより実装します。
|MimeType Mappings|
.File TypeがArchiveの場合 +
レスポンスに設定するMIMEタイプを、読み込むリソースの拡張子から判断するための設定を行います。
設定がない場合は、リソースに応じたデフォルトのMIMEタイプが使用されます。
MIMEタイプが不明な場合は、 `application/octet-stream` となります。 +
<<StaticResource-Settings-StaticResourceSetting-MIMETypeSetting,MIMEタイプ設定>>を参照してください。
|===

[[StaticResource-Settings-StaticResourceSetting-MIMETypeSetting]]
.MIMEタイプ設定
File TypeがArchiveの場合に、呼び出すリソースの拡張子からレスポンスに設定するMIMEタイプを指定します。

[cols="1,3",options="header"]
|===
|項目|内容
|Extension|拡張子を設定します。
|MIME Type|MIMEタイプを設定します。
|===

===== 多言語設定
言語毎にリソースを異なるものに設定することが可能です。

[cols="1,3",options="header"]
|===
|項目|内容
|Language|言語設定を行います。
|そのほかの項目|File TypeとFileを設定します。
|===

=== 利用方法
StaticResourceを利用するには、Action定義のResult設定でStaticResourceタイプを選択します。 +
Resultの設定方法については、<<Result-StaticResource, Result: StaticResource>>を参照してください。
