[[TenantToolService]]
=== TenantToolService
A service related to tenant management tools.

==== Interface Name
----
org.iplass.adminconsole.server.base.service.TenantToolService
----

==== Implementing Class
----
org.iplass.adminconsole.server.base.service.TenantToolService
----

==== The settings of TenantToolService
TenantToolService can be configured with the following items.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| createProcesses | <<TenantCreateProcess>>, Multiple | Set the process to be executed when creating a tenant.
| tenantRdbManagerParameter | <<TenantRdbManagerParameter>> | Set parameters for tenant management functions by RDB.
|===

[[TenantCreateProcess]]
.TenantCreateProcess
Pleas specify the implementing class of org.iplass.mtp.impl.tools.tenant.create.TenantCreateProcess to the class.

The following TenantCreateProcess is provided as our standard implementation.

* <<CreateAdminUserProcess>>
* <<BlankSkipProcess>>
* <<CreateMenuProcess>>
* <<CreateTopViewProcess>>
* <<CreateAppAdminRoleProcess>>
* <<CreateGemUserRoleProcess>>
* <<CreateAppAdminRoleEEProcess>>
* <<CreateGemUserRoleEEProcess>>
* <<CreateAppConsolePermissionProcess>>
* <<CreateCompleteProcess>>

[[CreateAdminUserProcess]]
.CreateAdminUserProcess
Create an administrator user.

Please specify org.iplass.mtp.impl.tools.tenant.create.CreateAdminUserProcess to the class.
There is no configurable items.

[[BlankSkipProcess]]
.BlankSkipProcess
Create an empty tenant.

Pleas specify org.iplass.mtp.impl.tools.tenant.create.BlankSkipProcess to the class.
There is no configurable items.

[[CreateMenuProcess]]
.CreateMenuProcess
Create the initial menu definition.

Pleas specify org.iplass.mtp.impl.tools.tenant.create.CreateMenuProcess to the class.
There is no configurable items.

[[CreateTopViewProcess]]
.CreateTopViewProcess
Create an initial TopView definition.

Pleas specify org.iplass.mtp.impl.tools.tenant.create.CreateTopViewProcess to the class.
There is no configurable items.

[[CreateAppAdminRoleProcess]]
.CreateAppAdminRoleProcess
Create administrator roles and permission data.

Pleas specify org.iplass.mtp.impl.tools.tenant.create.CreateAppAdminRoleProcess to the class.
There is no configurable items.

[[CreateGemUserRoleProcess]]
.CreateGemUserRoleProcess
Create Gem user role and permission data.

Pleas specify org.iplass.mtp.impl.tools.tenant.create.CreateGemUserRoleProcess to the class.
There is no configurable items.

[[CreateAppAdminRoleEEProcess]]
.[.eeonly]#CreateAppAdminRoleEEProcess#
Create authority data for EnterpriseEdition for administrator role.

Pleas specify org.iplass.mtp.impl.tools.tenant.create.CreateAppAdminRoleEEProcess to the class.
There is no configurable items.

[[CreateGemUserRoleEEProcess]]
.[.eeonly]#CreateGemUserRoleEEProcess#
Create EnterpriseEdition permission data for Gem user role.

Pleas specify org.iplass.mtp.impl.tools.tenant.create.CreateGemUserRoleEEProcess to the class.
There is no configurable items.

[[CreateAppConsolePermissionProcess]]
.[.eeonly]#CreateAppConsolePermissionProcess#
Create App Console permission data for the administrator role and Gem user role.

Pleas specify org.iplass.mtp.impl.tools.tenant.create.CreateAppConsolePermissionProcess to the class.
There is no configurable items.

[[CreateCompleteProcess]]
.CreateCompleteProcess
Perform tenant creation completing process.

Pleas specify org.iplass.mtp.impl.tools.tenant.create.CreateCompleteProcess to the class.
There is no configurable items.


[[TenantRdbManagerParameter]]
.TenantRdbManagerParameter
Please specify org.iplass.mtp.impl.tools.tenant.rdb.TenantRdbManagerParameter to the class.
The following items can be configured.

[cols="1,1,3", options="header"]
|====================
| 項目 | 値 | 説明
| deleteRows | Integer a| Number of table records deleted when deleting tenants. Default value is `10,000`.
|====================

===== Example
[source, xml]
----
<service>
	<interface>org.iplass.mtp.impl.tools.tenant.TenantToolService</interface>

	<property name="createProcesses" class="org.iplass.mtp.impl.tools.tenant.create.CreateAdminUserProcess" />
	<property name="createProcesses" class="org.iplass.mtp.impl.tools.tenant.create.BlankSkipProcess" />
	<property name="createProcesses" class="org.iplass.mtp.impl.tools.tenant.create.CreateMenuProcess" />
	<property name="createProcesses" class="org.iplass.mtp.impl.tools.tenant.create.CreateTopViewProcess" />
	<property name="createProcesses" class="org.iplass.mtp.impl.tools.tenant.create.CreateAppAdminRoleProcess" />
	<property name="createProcesses" class="org.iplass.mtp.impl.tools.tenant.create.CreateGemUserRoleProcess" />

	<!-- for ee -->
	<property name="createProcesses" class="org.iplass.mtp.impl.tools.tenant.create.CreateAppAdminRoleEEProcess" />
	<property name="createProcesses" class="org.iplass.mtp.impl.tools.tenant.create.CreateGemUserRoleEEProcess" />
	<!-- for appconsole -->
	<property name="createProcesses" class="org.iplass.mtp.impl.tools.tenant.create.CreateAppConsolePermissionProcess" />

	<property name="createProcesses" class="org.iplass.mtp.impl.tools.tenant.create.CreateCompleteProcess" />

	<!-- TenartRdbManagerParameter -->
	<property name="tenantRdbManagerParameter" class="org.iplass.mtp.impl.tools.tenant.rdb.TenantRdbManagerParameter">
		<!-- Number of records deleted when deleting tenants. Default value is 10,000 -->
		<!--
		<property name="deleteRows" value="10000" />
		-->
	</property>
</service>
----
