= Material Design Components (初期設定)
:_hreflang-path: developerguide/materialdesigncomponents/setup/index.html
:_relative-root-path: ../../../
:_menu-title-ee-only: true

== 初期設定
MDCを利用する際には以下の設定が必要となります。

=== MDCモジュールの追加

.mtp-service-configの編集
mtp-service-configに以下を追記し、MDCモジュールの設定ファイルを読み込めるようにします。
「iplass-ee-skeleton」を利用している場合は該当箇所のコメント化を解除します。

----
<inherits>/mdc-service-config.xml</inherits>
----

また、「iplass-ee-skeleton」を利用している場合は<<../../../serviceconfig/index.adoc#WebFrontendService, WebFrontendService>>の以下箇所のコメント化を解除します。 +
GEM画面の場合にはGEM用のエラー画面を、MDC画面の場合にはMDC用のエラー画面を表示するための設定です。

----
		<property name="errorUrlSelector" class="org.iplass.mtp.impl.web.CompositeErrorUrlSelector">
			<property name="selectorMap">
				<property name="default" class="org.iplass.gem.EnterpriseGemErrorUrlSelector" />
				<property name="gem/" class="org.iplass.gem.EnterpriseGemErrorUrlSelector" />
				<property name="mdc/" class="org.iplass.mtp.mdc.MdcErrorUrlSelector" />
			</property>
		</property>
----

.build.gradleの編集
build.gradleに以下を追記し、MDCモジュールを実行時の依存関係に追加します。
「iplass-ee-skeleton」を利用している場合は該当箇所のコメント化を解除します。

----
implementation 'org.iplass.ee:iplass-ee-mdc'
runtimeOnly 'org.iplass.ee:iplass-ee-admin-mdc'
----

追記後、プロジェクトのコンテキストメニューから `Gradleプロジェクトのリフレッシュ` を行ってください。

.web.xmlの編集
web.xmlのWebFragment設定に `mtp_admin_mdc` を追記し、AdminConsoleでMDCを利用できるようにします。
iplass-ee-skeletonを利用している場合は該当箇所のコメント化を解除します。

----
<!-- iPLAss web-fragment setting -->
<absolute-ordering>
	<name>mtp</name>
	<name>mtp_admin</name>

	<!-- for adminconsole mdc -->
	<name>mtp_admin_mdc</name>

	・・・・・
</absolute-ordering>
----

=== ロール / 権限設定
MDCモジュールを利用するユーザー用のグループ作成、ロール作成、権限設定を行います。 +
MDCモジュールにおける権限制御の詳細については、<<../mdcauth/index.adoc#, MDC権限制御>>を参照してください。

NOTE: iPLAssのバージョン3.2.0以降でテナントを新規作成した場合、MDC用のグループやロール、権限設定は自動で作成されます。 +
それ以前のバージョンで作成した既存のテナントでMDCを利用する場合、本項を参考にMDC用のグループやロール、権限設定を手動で追加してください。

.グループ
MDCを利用するユーザー用のグループを作成します。
グループのコードは `MdcUser` にします。

.ロール
MDCを利用するユーザー用のロールを作成します。
ロールのコードは `MdcUser` にします。

ロール条件を追加し、前項で作成したグループに所属していることを条件にします。

----
user.memberOf("MdcUser")
----

.Entity権限
Entityに対して権限を設定します。
`MdcUser` ロールには、iPLAssが標準提供する `mtp.auth.User(ユーザー)` 等のエンティティを含め、Entity権限は初期設定されていません。
必要に応じてEntity権限を追加してください。

.Action権限
MDCユーザーが利用するActionに対して権限を設定します。
`mdc` 配下の全てのActionに対して許可を設定するため、「PermissionExplorer」の「Action Permission」にて、`MdcUser` ロールの列と `mdc` の階層フォルダが交差するセルをクリックし、Nameに適切な名前を、Allow Conditionに下記条件を設定してOKボタンを押してください。

----
org.iplass.mtp.mdc.auth.MdcAuth.isPermitAction(action, parameter)
----

Action権限の詳細については、<<../mdcauth/index.adoc#_mdcauth, MdcAuth>> を参照してください。

.WebApi権限
MDCユーザーが利用するWebApiに対して権限を設定します。
`mdc` 配下の全てのWebApiに対して許可を設定するため、「PermissionExplorer」の「WebApi Permission」にて、`MdcUser` ロールの列と `mdc` の階層フォルダが交差するセルをクリックし、Nameに適切な名前を、Allow Conditionに下記条件を設定してOKボタンを押してください。

----
org.iplass.mtp.mdc.auth.MdcAuth.isPermitWebApi(WebApi, parameter)
----

WebApi権限の詳細については、<<../mdcauth/index.adoc#_mdcauth, MdcAuth>> を参照してください。

=== 画面定義の設定
MDCの画面を構成する各種画面定義の初期設定を行います。

.TopView
MDCモジュールにおけるTop画面のデフォルト定義を作成します。 +
AdminConsoleのメニューから `MDC_TopView` を右クリックし、 `TopViewを作成する` をクリックします。
表示されたダイアログのNameに `DEFAULT` を入力して定義を作成してください。 +
TopViewの詳細については、<<../topview/index.adoc#topview, TopView>> を参照してください。

.Navigation
MDCモジュールにおけるナヴィゲーション（サイドメニュー/アプリケーションバー）のデフォルト定義を作成します。 +
AdminConsoleのメニューから `Navigation` を右クリックし、 `Navigationを作成する` をクリックします。
表示されたダイアログのNameに `DEFAULT` を入力して定義を作成してください。 +
`DEFAULT` のNavigation作成後は、新規に追加したエンティティのメニューアイテムが `DEFAULT` に自動で追加されます。 +
Navigationの詳細については、<<../navigation/index.adoc#navigation, Navigation>> を参照してください。

.EntityView
MDCモジュールでは、iPLAssが標準提供する `mtp.auth.User(ユーザー)` 等のエンティティを含め、MDC用のEntityView定義は初期登録されていません。 +
EntityView定義が未登録のエンティティについては、検索画面や詳細・編集画面をエンティティ定義を元に自動で構成して表示します。 +
MDC用のEntityView定義を作成するには、AdminConsoleのメニューから操作したいエンティティを右クリックし、 `MDC EntityView` をクリックします。 +
EntityViewの詳細については、<<../entityview/index.adoc#entityview, EntityView>> を参照してください。
