[[AiPromptService]]
=== [.eeonly]#AiPromptService#
AI Prompt Service.

==== Interface Name
----
org.iplass.mtp.impl.ai.prompt.AiPromptService
----

==== Implementing Class Name
----
org.iplass.mtp.impl.ai.prompt.AiPromptService
----

==== Settings of AiPromptService
Configures the AiPromptService.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item
| Value
| Description

| definitionMetaClassMap
| String, in format of Map
| Sets the mapping between AI platform definition classes and metadata classes in AI prompt. +
This configuration value should be defined by the system and does not need to be set by the user. +
In the Map format, the name property should be set to the fully qualified class name of a subclass of `org.iplass.mtp.ai.prompt.AiPlatformDefinition`. +
In the Map format, the value property should be set to the fully qualified class name of a subclass of `org.iplass.mtp.impl.ai.prompt.MetaAiPlatform`.

| userIdFactory
| <<AiPromptService_AiPromptService_AiIdFactory>>
| Sets the factory class that generates a unique ID for each user. +
By default, the `org.iplass.mtp.impl.ai.prompt.DefaultAiUserIdFactory` class is set.

| userIdCharacterReplacementRule
| String, in format of Map
a| Sets the rules for replacing characters that cannot be used in the user ID. +
The key is the character (char) to be replaced, and the value is the replacement string. +
By default, the following replacement rules are applied.

- Character to be replaced: `@`, Replacement string: `x40`
- Character to be replaced: `.` , Replacement string: `x2e`
- Character to be replaced: `+`, Replacement string: `x2b`

| sessionIdFactory
| <<AiPromptService_AiPromptService_AiIdFactory>>
| Sets the factory class that generates a unique ID for each request session. +
By default, the `org.iplass.mtp.impl.ai.prompt.DefaultAiSessionIdFactory` class is set.

| sessionIdCharacterReplacementRule
| String, in format of Map
a| Sets the rules for replacing characters that cannot be used in the session ID. +
The key is the character (char) to be replaced, and the value is the replacement string. +
By default, the following replacement rules are applied.

- Character to be replaced: `@`, Replacement string: `x40`
- Character to be replaced: `.` , Replacement string: `x2e`
- Character to be replaced: `+`, Replacement string: `x2b`

|===

[[AiPromptService_AiPromptService_AiIdFactory]]
.AiIdFactory
class specifies the implementation class of `org.iplass.mtp.impl.ai.prompt.AiIdFactory`. +
By default, the following AiServiceProviderConfig is provided.

- <<AiPromptService_AiPromptService_AiIdFactory_DefaultAiSessionIdFactory>>
- <<AiPromptService_AiPromptService_AiIdFactory_DefaultAiUserIdFactory>>

[[AiPromptService_AiPromptService_AiIdFactory_DefaultAiSessionIdFactory]]
.[.eeonly]#DefaultAiSessionIdFactory#
class specifies the `org.iplass.mtp.impl.ai.prompt.DefaultAiSessionIdFactory` class. +
There are no configurable items.

[[AiPromptService_AiPromptService_AiIdFactory_DefaultAiUserIdFactory]]
.[.eeonly]#DefaultAiUserIdFactory#
class specifies the `org.iplass.mtp.impl.ai.prompt.DefaultAiUserIdFactory` class. +
There are no configurable items.

===== Example
[source,xml]
----
<!-- AI Prompt -->
<service>
    <interface>org.iplass.mtp.impl.ai.prompt.AiPromptService</interface>
    <class>org.iplass.mtp.impl.ai.prompt.AiPromptService</class>

    <!-- Character replacement rules for ID generation -->
    <bean name="sharedIdCharacterReplacementRule" class="java.util.HashMap">
        <property name="@" value="x40" />
        <property name="." value="x2e" />
        <property name="+" value="x2b" />
    </bean>

    <property name="definitionMetaClassMap">
        <property name="org.iplass.mtp.ai.prompt.AiPlatformDefinition" value="org.iplass.mtp.impl.ai.prompt.MetaAiPlatform" />
        <property name="org.iplass.mtp.ai.prompt.AiPlatformCustomDefinition" value="org.iplass.mtp.impl.ai.prompt.MetaAiPlatformCustom" />
    </property>

    <!-- Generating user ID -->
    <property name="userIdFactory" class="org.iplass.mtp.impl.ai.prompt.DefaultAiUserIdFactory" />
    <property name="userIdCharacterReplacementRule" ref="sharedIdCharacterReplacementRule" />

    <!-- Generating session ID -->
    <property name="sessionIdFactory" class="org.iplass.mtp.impl.ai.prompt.DefaultAiSessionIdFactory" />
    <property name="sessionIdCharacterReplacementRule" ref="sharedIdCharacterReplacementRule" />
</service>
----

[[AiPromptService_AiPromptServiceStub]]
==== Settings of AiPromptServiceStub
Configures the AiPromptServiceStub. +
AiPromptServiceStub is a stub implementation for development that does not use an external AI platform. +
It is a simple implementation that returns the values set in the properties.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item
| Value
| Description

| stubLogic
| <<AiPromptService_AiPromptServiceStub_AiPlatform>>
| Sets the stub logic for the AI platform in the AI prompt. +
If this property is set, other stub properties are ignored.

| stubText
| String
| Sets the text response for the AI platform in the AI prompt. +
The default value is `default stub text`.

| stubImagePath
| String
| Sets the file path for the image response from the AI platform in the AI prompt.

| stubImageType
| String
a| Sets the type of the image response from the AI platform in the AI prompt. +
If stubImagePath is set, stubImageType is required.

Configurable values::
- GIF
- JPEG
- PNG
- WEBP

| stubPdfPath
| String
| Sets the file path for the PDF response from the AI platform in the AI prompt.
|===

[[AiPromptService_AiPromptServiceStub_AiPlatform]]
.AiPlatform
class specifies the implementation class of `org.iplass.mtp.impl.ai.prompt.AiPlatform`. +
There are no provided classes.

===== Example
[source,xml]
----
<!-- AI Prompt -->
<service>
    <interface>org.iplass.mtp.impl.ai.prompt.AiPromptService</interface>
    <class>org.iplass.mtp.impl.ai.prompt.AiPromptServiceStub</class>

    <!-- Sets the stub logic. If you want to return custom values, set the stubLogic property. -->
    <!--
    <property name="stubLogic" class="package.to.AiPlatformImpl" />
    -->

    <!-- Sets the stub return values. All values set will be returned. -->
    <property name="stubText" value="stub text" />
    <property name="stubImagePath" value="/path/to/image.png" />
    <property name="stubImageType" value="PNG" />
    <property name="stubPdfPath" value="/path/to/document.pdf" />
</service>
----
