[[AuditLoggingService]]
=== AuditLoggingService
Entityに対する登録・更新・削除を操作ログとして出力するサービスです。

==== インタフェース名
----
org.iplass.mtp.impl.entity.auditlog.AuditLoggingService
----

==== 実装クラス名
.ロガーを利用した操作ログ出力
----
org.iplass.mtp.impl.entity.auditlog.LoggerAuditLoggingService
----
.[.eeonly]#RDBとロガーを利用した操作ログ出力#
----
org.iplass.mtp.impl.entity.auditlog.RdbAuditLoggingService
----

==== LoggerAuditLoggingServiceの設定
ロガーへの出力内容を設定します。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| logCompact | boolean | LongTextなど長すぎる文字列を指定文字数でカットするか。デフォルト値はfalseです。
| logQuery | boolean | クエリをロガーに出力するか。デフォルト値はfalseです。
| logSelectValueWithLabel | boolean | SelectValueをログに出力する時に、ラベルで出力するか。デフォルト値はfalseです。
| logReferenceWithLabel | boolean | Referenceをログに出力する時に、nameで出力するか。falseの場合、oidを出力します。デフォルト値はfalseです。
| textMaxLength | int | LongTextなど長すぎる文字列をカットする文字数。デフォルト値は256です。
| maskTarget | <<MaskTarget>> | ログをマスクする際に使用する、個別のMaskTargetを設定。
|===

[[MaskTarget]]
.MaskTarget
classはorg.iplass.mtp.impl.entity.auditlog.MaskTargetを指定します。
マスク対象のEntityとProperty、マスク方式を設定します。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| entity | String | マスク対象のEntityを指定します。"*"で全てのEntityを指定可能です。
| property | String | マスク対象のPropertyを指定します。"\*"で全てのPropertyを指定可能です。また、"*"指定のEntity、PropertyであってもProperty名を個別で指定することにより、個別指定の `maskHandler` の設定が優先されます。
| maskHandler | <<maskHandler>> | マスク方式を設定します。
|===

[[maskHandler]]
.MaskHandler
classはorg.iplass.mtp.impl.entity.auditlog.LogMaskHandlerの実装クラスを指定します。
標準で、以下のMaskHandlerを提供します。

- <<LogAllMaskHandler>>
- <<LogRegexMaskHandler>>
- <<LogHashMaskHandler>>
- <<LogNoMaskHandler>>

[[LogAllMaskHandler]]
.LogAllMaskHandler
値を固定文字列でマスクするLogMaskHandlerです。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| maskString | String | 設定した文字列で値を置き換えます。
|===

[[LogRegexMaskHandler]]
.LogRegexMaskHandler
値を正規表現でマスクするLogMaskHandlerです。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| maskChar | String | 正規表現に一致した文字を `maskChar` で置き換えます。
| maskRegex | String | 正規表現のパターン。指定できる文字列は `java.util.regex.Pattern` のパターンとなります。
|===

[[LogHashMaskHandler]]
.LogHashMaskHandler
値をハッシュ化してマスクするLogMaskHandlerです。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| hashAlgorithm | String | ハッシュのアルゴリズムを指定。 デフォルトは `SHA-256` です。
|===

[[LogNoMaskHandler]]
.LogNoMaskHandler
マスクしないことを明示するLogMaskHandlerです。
"*"指定でマスク対象のPropertyとなる場合でも、LogNoMaskHandlerを個別のPropertyに指定することにより、マスクさせないことが可能です。

==== [.eeonly]#RdbAuditLoggingServiceの設定#
RDBとロガーへの出力内容を設定します。

===== 設定項目
LoggerAuditLoggingServiceの設定項目に加え以下の項目を設定可能です。

[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| searchResultCacheLimit | long | 検索結果からユーザー名などの追加情報を取得する為の内部キャッシュサイズ。
| logIndexOrder | boolean | 多重度が複数のプロパティの更新ログを記録する際、並び順（配列のindex）の変更も記録するか否か。デフォルト値はtrueです。
| disableLogging | boolean | RDBへのログ記録を一時的に無効化したい場合trueを指定。
システム管理者によるデータメンテナンス時にログが記録されるのを防ぎたい場合、一時的にログ記録を無効化することが可能です。
|===


===== 設定例
[source, xml]
----
<service>
	<interface>org.iplass.mtp.impl.entity.auditlog.AuditLoggingService</interface>
	<class>org.iplass.mtp.impl.entity.auditlog.RdbAuditLoggingService</class>

	<!-- logファイルへの出力時、LongTextなど長すぎる文字列を全部出力しない場合（デフォルト256文字まで）はtrue -->
	<property name="logCompact" value="false" />
	<!-- if log query, set to true -->
	<property name="logQuery" value="false" />
	
	<!-- Internal cache size for retrieving additional information, such as user name, from search result -->
	<property name="searchResultCacheLimit" value="50" />

	<!-- log出力時、SelectValueのコードとラベルを出力する場合はtrue -->
	<property name="logSelectValueWithLabel" value="true" />
	<!-- log出力時、Referenceのoidとnameを出力する場合はtrue -->
	<property name="logReferenceWithLabel" value="true" />

	<!-- logファイルへ出力されるプロパティのマスク設定 -->
	<property name="maskTarget" class="org.iplass.mtp.impl.entity.auditlog.MaskTarget">
		<property name="entity" value="entityA" />
		<property name="property" value="propertyA" />
		<property name="maskHandler" ref="allMaskHandler" />
	</property>
	<property name="maskTarget" class="org.iplass.mtp.impl.entity.auditlog.MaskTarget">
		<property name="entity" value="*" />
		<property name="property" value="propertyB" />
		<property name="maskHandler" ref="regexMaskHandler" />
	</property>
	<bean name="allMaskHandler" class="org.iplass.mtp.impl.entity.auditlog.LogAllMaskHandler">
		<property name="maskString" value="*****" />
	</bean>
	<bean name="regexMaskHandler" class="org.iplass.mtp.impl.entity.auditlog.LogRegexMaskHandler">
		<property name="maskChar" value="*" />
		<property name="maskRegex" value=".+?" />
	</bean>
	<bean name="hashMaskHandler" class="org.iplass.mtp.impl.entity.auditlog.LogHashMaskHandler">
		<property name="hashAlgorithm" value="SHA-256" />
	</bean>
	<bean name="noMaskHandler" class="org.iplass.mtp.impl.entity.auditlog.LogNoMaskHandler">
	</bean>
</service>
----
