[[AutoNumberTypeCounter]]
=== AutoNumberTypeCounter
AutoNumber型の採番を行うサービスです。
EntityのプロパティとしてAutoNumber型を利用する場合のCounterServiceの定義です。
採番時に飛び番を許容するかどうかで利用する設定が変わります。
許容する場合は `AutoNumberTypeCounterAcceptSkip` の設定を、
許容しない場合は `AutoNumberTypeCounterNoSkip` の設定を利用します。

==== インタフェース名
----
org.iplass.mtp.impl.counter.CounterService
----

==== 実装クラス名
.キャッシュなし
----
org.iplass.mtp.impl.counter.RdbTableCounterService
----

.キャッシュあり
----
org.iplass.mtp.impl.counter.CachableRdbTableCounterService
----

==== RdbTableCounterServiceの設定
RdbTableCounterServiceを設定します。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| separateTransaction | boolean | 採番時にトランザクションを分けるか。デフォルト値はfalseです。
| retryCount | int | 採番失敗時にリトライする回数。デフォルト値は3です。
| counterTypeName | String |  採番タイプの名前。デフォルト値は `defaultCounter` です
|===

==== CachableRdbTableCounterServiceの設定
CachableRdbTableCounterServiceを設定します。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| separateTransaction | boolean | 採番時にトランザクションを分けるか。デフォルト値はfalseです。
| retryCount | int | 採番失敗時にリトライする回数。デフォルト値は3です。
| counterTypeName | String |  採番タイプの名前。デフォルト値は `defaultCounter` です
| cacheSize | int | キャッシュサイズ。デフォルト値は20です。
|===

===== 設定例
[source,xml]
----
<service name="AutoNumberTypeCounterAcceptSkip">
	<interface>org.iplass.mtp.impl.counter.CounterService</interface>
	<!-- without cache RdbTableCounterService -->
	<!--
	<class>org.iplass.mtp.impl.counter.RdbTableCounterService</class>
	<property name="counterTypeName" value="AutoNumberTypeCounter" />
	<property name="separateTransaction" value="true" />
	<property name="retryCount" value="3" />
	 -->
	<!-- with cache RdbTableCounterService -->
	<class>org.iplass.mtp.impl.counter.CachableRdbTableCounterService</class>
	<property name="counterTypeName" value="AutoNumberTypeCounter" />
	<property name="cacheSize" value="20" />
	<property name="retryCount" value="3" />
</service>
<service name="AutoNumberTypeCounterNoSkip">
	<interface>org.iplass.mtp.impl.counter.CounterService</interface>
	<class>org.iplass.mtp.impl.counter.RdbTableCounterService</class>
	<property name="counterTypeName" value="AutoNumberTypeCounter" />
	<property name="separateTransaction" value="false" />
</service>
----
