[[LobStoreService]]
=== LobStoreService
A service for the persistance of LOB data.

==== Interface Name
----
org.iplass.mtp.impl.lob.LobStoreService
----

==== Implementing Class Name
----
org.iplass.mtp.impl.lob.LobStoreService
----

==== Settings of LobStoreService
LobStoreService can be configured with the following items.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| binaryStore | <<LobStore>> | Set the LobStore for Binary data.
| longTextStore | <<LobStore>> | Set the LobStore for long text.
| defaultLobStoreName | String | The name of the default Lob store. The default value is `default`.
| manageLobSizeOnRdb | boolean | Whether to manage the Lob size with Rdb (lob_store). The default value is `false` (do not manage).
| temporaryKeepDay | int | Number of days to keep the temporary data. The cleaner will delete data older than the specified value here. The default value is `1`.
| invalidKeepDay | int | Number of days to keep invalid (non-reference) data. The cleaner will delete data older than specified here. The default value is `0`.
| cleanCommitLimit | int | Commit batch size of the cleaner deletion process. The default value is `100`.
| detectAbandonedStream | boolean | Specifies whether to detect and close the InputStream/OutputStream used for input/output of binary data. The default value is `false` .
| logAbandoned | boolean | When detectAbandonedStream is `true` , whether to output a stack trace to identify the location where the stream was created. The default value is `false` .
|===

[[LobStore]]
.LobStore
Please specify the implementing class of org.iplass.mtp.impl.lob.lobstore.LobStore.

As the standard implementation, the following LobStore are provided.

- <<RdbLobStore>>
- <<FileLobStore>>
- <<S3LobStore>>
- <<aws2_S3LobStore>>
- <<MetricsS3LobStore>>
- <<AddableMultiLobStore>>

[[RdbLobStore]]
.RdbLobStore
Please specify org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore to the class.

This is the LobStore using RDB.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| lobValidator | <<LobValidator>> | The validation process corresponding to Lob.
|===

[[FileLobStore]]
.FileLobStore
Please specify org.iplass.mtp.impl.lob.lobstore.file.FileLobStore to the class.

This is the LobStore using files.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| rootDir | String | Specify the root directory of where to save the data.
| overwriteFile | boolean | Set whether to overwrite the files. The default value is false.(no overwriting)
| lobValidator | <<LobValidator>> | The validation process corresponding to Lob.
|===

[[S3LobStore]]
.[.eeonly]#(Deprecated)S3LobStore#
Please specify org.iplass.mtp.impl.aws.lobstore.s3.S3LobStore to the class.

[CAUTION]
====
AWS SDK for Java 1.x is in maintenance mode and will be discontinued in December 2025. +
iPLAss recommends deprecating the AWS SDK for Java 1.x-based library iplass-ee-aws and moving to the AWS SDK for Java 2.x-based library iplass-ee-aws2. +
If you are using this function, please migrate your settings to <<aws2_S3LobStore>> in the library iplass-ee-aws2. +
The library iplass-ee-aws will be removed in the future.
====

This is the LobStore using S3.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| region | String | The region for S3.
| endpoint | String | Specify the S3 endpoint.
| bucketName | String | S3 package name.
| encryption | <<S3Encryption>> | Specify this item when it is needed to encrypt and obfuscate S3 objects.
| overwriteFile | boolean | Set whether to overwrite the existing S3 objects. +
The default value is false.(no overwriting)
| useTransferManager | boolean | Use TransferManager or not. The default value is `false`
| transferManagerConfiguration | <<TransferManagerConfiguration>> | The settings of TransferManager
| transferManagerThreadPoolSize | int | The size of thread pool that use at TransferManager. When `-1` is set, thread pools are created with the default values in the AWS SDK. The default value is `-1`.
| lobValidator | <<LobValidator>> | The validation process corresponding to Lob.
| requiredTagMap | String, in format of Map | Specify in Map format when checking the required tag value in the S3 object. Set the tag name as key and the tag value as value.
| retryTagCheckIntervalMillis | long | Retry interval when checking tags (milliseconds).
| retryTagCheckCount | int | The number of retry attempts for checking tags.
|===

[[TransferManagerConfiguration]]
.TransferManagerConfiguration
Please specify com.amazonaws.services.s3.transfer.TransferManagerConfiguration to the class. So to configure the settings of TransferManager.

[[S3Encryption]]
.[.eeonly]#S3Encryption#
Please specify org.iplass.mtp.impl.aws.lobstore.s3.S3Encryption to the class.

As our standard implementation, the following S3Encryption are provided.

- <<SseS3Encryption>>
- <<SseKmsEncryption>>

[[SseS3Encryption]]
.[.eeonly]#SseS3Encryption#
Please specify the implementing class of org.iplass.mtp.impl.aws.lobstore.s3.SseS3Encryption.

Perform the Encryption process with SSE-S3 method. There are no changeable settings available.

[[SseKmsEncryption]]
.[.eeonly]#SseKmsEncryption#
Please specify org.iplass.mtp.impl.aws.lobstore.s3.SseKmsEncryption to the class.

Perform the Encryption process with SSE-KMS methods.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| awsKmsKeyId | String | The Key Id for AWS Key Management Service (KMS)S3
|===

[[aws2_S3LobStore]]
.[.eeonly]#S3LobStore#
Please specify org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3LobStore to the class. +
This is the LobStore using S3.
The following items can be configured.

[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| bucketName | String, required | S3 bucket name.
| s3controller | <<aws2_S3Controller>> | S3 control function. If not set, the default value is <<aws2_S3AsyncClientController>>.
| clientConfig | <<aws2_AWSSetting_AWSClientConfig>> | Manage S3 client settings. Configure AWS regions and communication settings. Used to initialize <<aws2_S3Controller>> and <<aws2_S3ClientFactory>>.
| overwriteFile | boolean | Set whether to overwrite the existing S3 objects. +
The default value is false.(no overwriting)
| keyPrefix | String a| Set a prefix to the S3 object key. 

.Example result with and without prefix when object key is "object/key/file.dat"
* No prefix : `object/key/file.dat`
* With prefix(Set "test-key-prefix".) : `test-key-prefix/object/key/file.dat` 

Set the prefix according to link:https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html#object-key-guidelines[Object key naming guidelines^].

| lobValidator | <<LobValidator>> | The validation process corresponding to Lob.
| requiredTagMap | String, in format of Map | Specify in Map format when checking the required tag value in the S3 object. Set the tag name as key and the tag value as value.
| retryTagCheckIntervalMillis | long | Retry interval when checking tags (milliseconds).
| retryTagCheckCount | int | The number of retry attempts for checking tags.
|===

[[aws2_S3Controller]]
.[.eeonly]#S3Controller#
Please specify the implementing class of org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3Controller to the class. +
As the standard implementation, the following S3Controller are provided.

- <<aws2_S3SyncClientController>>
- <<aws2_S3AsyncClientController>>

[[aws2_S3SyncClientController]]
.[.eeonly]#S3SyncClientController#
Please specify org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3SyncClientController to the class. +
S3 control function using S3Client. Uses authentication information and client settings managed in <<aws2_AWSSetting>>. The following items can be set.

[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| s3ClientFactory | <<aws2_S3ClientFactory>> | Specify the S3 synchronization client generation function. If not set, the default value is <<aws2_S3SyncClientFactory>>.
| requestConfigureList | <<aws2_S3RequestConfigure>>, Multiple | Additional settings are configured at the time the S3 request is executed.
|===

[[aws2_S3AsyncClientController]]
.[.eeonly]#S3AsyncClientController#
Please specify org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3AsyncClientController to the class. +
S3 control function using S3AsyncClient. Uses authentication information and client settings managed in <<aws2_AWSSetting>>. The following items can be set.

[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| s3ClientFactory | <<aws2_S3ClientFactory>> | Specify S3 asynchronous client generation functionality. If not set, the default value is <<aws2_S3AsyncClientFactory>>.
| requestConfigureList | <<aws2_S3RequestConfigure>>, Multiple | Additional settings are configured at the time the S3 request is executed.
|===

[[aws2_S3ClientFactory]]
.[.eeonly]#S3ClientFactory#
Please specify the implementing class of org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3ClientFactory to the class. +
As the standard implementation, the following S3ClientFactory are provided.

* Class to generate synchronous clients
** <<aws2_S3SyncClientFactory>>
* Class to generate asynchronous clients
** <<aws2_S3AsyncClientFactory>>
** <<aws2_S3AsyncCrtClientFactory>>

[TIP]
====
The maximum size of an S3 object part is 5GB. This is the maximum object size for clients that do not support transparent multipart. +
If you are uploading objects larger than 5GB, please use a client with transparent multipart enabled.

Please refer to link:https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/examples-s3.html#s3-clients[S3 clients in the AWS SDK for Java 2.x^] for S3 Client selection.
====
[[aws2_S3SyncClientFactory]]
.[.eeonly]#S3SyncClientFactory#
Please specify org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3SyncClientFactory to the class. +
Transparent multipart operation is not supported. +
Generate S3Client for the synchronization client. There are no configuration items.

[[aws2_S3AsyncClientFactory]]
.[.eeonly]#S3AsyncClientFactory#
Please specify org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3AsyncClientFactory to the class. +
Transparent multipart operation can be enabled by configuration. +
Generates an asynchronous client, S3AsyncClient. The following items can be configured.

[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| multipartEnabled | Boolean | If set to true, enables multipart. If not set, the default value is false.
|===

[[aws2_S3AsyncCrtClientFactory]]
.[.eeonly]#S3AsyncCrtClientFactory#
Please specify org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3AsyncCrtClientFactory to the class. +
Transparent multipart operation is supported. +
Generates an asynchronous client, S3AsyncClient. The client generated by this function is link:https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/crt-based-s3-client.html[AWS CRT-based S3 client^]. There are no configuration items.

If performance of S3 operations is important to you, we recommend using a CRT-based client. +
CRT-based clients use native libraries. Therefore, please make sure that the system runs on the platform you are using.

The addition of the library `software.amazon.awsdk.crt:aws-crt` is required to use the feature. +
For more information, see link:https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/crt-based-s3-client.html#crt-based-s3-client-depend[Add dependencies to use the AWS CRT-based S3 client^].

[[aws2_S3RequestConfigure]]
.[.eeonly]#S3RequestConfigure#
Please specify the implementing class of org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3RequestConfigure to the class. +
Specify if you want to add additional settings to GetObjectRequest, PutObjectRequest, DeleteObjectRequest, HeadObjectRequest, or GetObjectTaggingRequest. +
As the standard implementation, the following S3RequestConfigure are provided.

- <<aws2_S3PutRequestEncryptionSseKmsConfigure>>
- <<aws2_S3PutRequestEncryptionSseS3Configure>>
- <<aws2_micrometer_S3RequestMetricPublisherConfigure>>

[[aws2_S3PutRequestEncryptionSseKmsConfigure]]
.[.eeonly]#S3PutRequestEncryptionSseKmsConfigure#
Please specify org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3PutRequestEncryptionSseKmsConfigure to the class. +
Set SSE-KMS encryption when executing S3 PutObjectRequest. Set the following items

[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| awsKmsKeyId | String | Set the KMS key ID. Setting this will configure encryption using the specified key.  +
If not set, encryption will be set using the AWS Managed KMS key.
|===

[[aws2_S3PutRequestEncryptionSseS3Configure]]
.[.eeonly]#S3PutRequestEncryptionSseS3Configure#
Please specify org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3PutRequestEncryptionSseS3Configure to the class. +
Set SSE-S3 encryption when executing S3 PutObjectRequest. There are no configuration items.

[[aws2_micrometer_S3RequestMetricPublisherConfigure]]
.[.eeonly]#S3RequestMetricPublisherConfigure#
Please specify org.iplass.mtp.impl.lob.lobstore.s3.awsv2.S3RequestMetricPublisherConfigure to the class.
Add a setting for Micrometer to collect metrics when executing S3 requests.

CAUTION: If you are using <<aws2_S3AsyncCrtClientFactory, CRT-based S3Client (S3AsyncCrtClientFactory)>>, metrics collection by Micrometer is not available.

[[MetricsS3LobStore]]
.[.eeonly]#(Deprecated)MetricsS3LobStore#
Please specify org.iplass.mtp.impl.micrometer.metrics.aws.lobstore.s3.MetricsS3LobStore to the class.

It’s S3LobStore with the metric collection function by Micrometer.
The same items as S3LobStore can be configured.

[CAUTION]
====
AWS SDK for Java 1.x is in maintenance mode and will be discontinued in December 2025. +
iPLAss recommends deprecating the AWS SDK for Java 1.x-based library iplass-ee-aws and moving to the AWS SDK for Java 2.x-based library iplass-ee-aws2. +
If you are using this feature, please migrate your configuration to AWS SDK for Java 2.x based <<aws2_S3LobStore>> and <<aws2_micrometer_S3RequestMetricPublisherConfigure>>. +
The library iplass-ee-aws will be removed in the future.
====

[[AddableMultiLobStore]]
.AddableMultiLobStore
Please specify org.iplass.mtp.impl.lob.lobstore.multi.AddableMultiLobStore to the class.

LobStore that can be configured as a single LobStore by combining multiple LobStores.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| lobStore | <<LobStore>>, Multiple | Set LobStore here.
| lobValidator | <<LobValidator>> | The validation process corresponding to Lob.
|===

[[LobValidator]]
.LobValidator
Please specify the implementing class of org.iplass.mtp.impl.lob.lobstore.LobValidator.

As the standard implementation, the following LobValidator are provided.

- <<LogLobValidator>>
- <<ProcessLobValidator>>

[[LogLobValidator]]
.LogLobValidator
Please specify org.iplass.mtp.impl.lob.lobstore.LogLobValidator to the class.

It simply output the log. There are no settings that can be configured.

[[ProcessLobValidator]]
.ProcessLobValidator
Please specify org.iplass.mtp.impl.lob.lobstore.ProcessLobValidator to the class.

Initiated the external process.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| command | String, Multiple | Specify the external process parameter.
| checksumAlgorithm | String | Specify the algorithms of the checksum.
You can chose from: Adler-32/CRC-32/MD5/SHA-1/SHA-256
|===

===== Example
[source,xml]
----
<service>
	<interface>org.iplass.mtp.impl.lob.LobStoreService</interface>
	<property name="lobDao" class="org.iplass.mtp.impl.lob.EncryptLobDao" />

	<property name="defaultLobStoreName" value="defaultStore" />
	<property name="defaultStore" class="org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore">
	</property>
	<!--
	<property name="binaryStore" class="org.iplass.mtp.impl.lob.lobstore.file.FileLobStore">
		<property name="rootDir" value="D:\tmp\fileLobStore" />
		<property name="overwriteFile" value="false" />
	</property>
	<property name="longTextStore" class="org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore">
	</property>
	 -->

	<!--
		Multiple LobStores can be combined into a single LobStore.
		New addition is performed according to the lobStore defined at the top.
		The system will search references from all lobStores.
		Deletion is also performed on all lobStores.
	 -->
	<!--
	<property name="binaryStore" class="org.iplass.mtp.impl.lob.lobstore.multi.AddableMultiLobStore">
		<property name="lobStore" class="org.iplass.mtp.impl.lob.lobstore.file.FileLobStore">
			<property name="rootDir" value="D:\tmp\fls2" />
		</property>
		<property name="lobStore" class="org.iplass.mtp.impl.lob.lobstore.file.FileLobStore">
			<property name="rootDir" value="D:\tmp\fls1" />
		</property>
		<property name="lobStore" class="org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore" />
	</property>
	 -->

	 <!--
		Specify whether the Lob size is managed by Rdb (lob_store).
		Changed the layout of the lob_store table for size management control in ver1.5.2.
		If the lob_store table cannot be changed in the existing system, it can be avoided by specifying false. -->
	<property name="manageLobSizeOnRdb" value="false" />
</service>
----
