[[LobStoreService]]
=== LobStoreService
A service for the persistance of LOB data.

==== Interface Name
----
org.iplass.mtp.impl.lob.LobStoreService
----

==== Implementing Class Name
----
org.iplass.mtp.impl.lob.LobStoreService
----

==== Settings of LobStoreService
LobStoreService can be configured with the following items.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| binaryStore | <<LobStore>> | Set the LobStore for Binary data.
| longTextStore | <<LobStore>> | Set the LobStore for long text.
| defaultLobStoreName | String | The name of the default Lob store. The default value is `default`.
| manageLobSizeOnRdb | boolean | Whether to manage the Lob size with Rdb (lob_store). The default value is `false` (do not manage).
| temporaryKeepDay | int | Number of days to keep the temporary data. The cleaner will delete data older than the specified value here. The default value is `1`.
| invalidKeepDay | int | Number of days to keep invalid (non-reference) data. The cleaner will delete data older than specified here. The default value is `0`.
| cleanCommitLimit | int | Commit batch size of the cleaner deletion process. The default value is `100`.
|===

[[LobStore]]
.LobStore
Please specify the implementing class of org.iplass.mtp.impl.lob.lobstore.LobStore.

As the standard implementation, the following LobStore are provided.

- <<RdbLobStore>>
- <<FileLobStore>>
- <<S3LobStore>>
- <<MetricsS3LobStore>>
- <<AddableMultiLobStore>>

[[RdbLobStore]]
.RdbLobStore
Please specify org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore to the class.

This is the LobStore using RDB.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| lobValidator | <<LobValidator>> | The validation process corresponding to Lob.
|===

[[FileLobStore]]
.FileLobStore
Please specify org.iplass.mtp.impl.lob.lobstore.file.FileLobStore to the class.

This is the LobStore using files.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| rootDir | String | Specify the root directory of where to save the data.
| overwriteFile | boolean | Set whether to overwrite the files. The default value is false.(no overwriting)
| lobValidator | <<LobValidator>> | The validation process corresponding to Lob.
|===

[[S3LobStore]]
.[.eeonly]#S3LobStore#
Please specify org.iplass.mtp.impl.aws.lobstore.s3.S3LobStore to the class.

This is the LobStore using S3.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| region | String | The region for S3.
| endpoint | String | Specify the S3 endpoint.
| bucketName | String | S3 package name.
| encryption | <<S3Encryption>> | Specify this item when it is needed to encrypt and obfuscate S3 objects.
| overwriteFile | boolean | Set whether to overwrite the existing S3 objects. +
The default value is false.(no overwriting)
| useTransferManager | boolean | Use TransferManager or not. The default value is `false`
| transferManagerConfiguration | <<TransferManagerConfiguration>> | The settings of TransferManager
| transferManagerThreadPoolSize | int | The size of thread pool that use at TransferManager. When `-1` is set, thread pools are created with the default values in the AWS SDK. The default value is `-1`.
| lobValidator | <<LobValidator>> | The validation process corresponding to Lob.
| requiredTagMap | String, in format of Map | Specify in Map format when checking the required tag value in the S3 object. Set the tag name as key and the tag value as value.
| retryTagCheckIntervalMillis | long | Retry interval when checking tags (milliseconds).
| retryTagCheckCount | int | The number of retry attempts for checking tags.
|===

[[TransferManagerConfiguration]]
.TransferManagerConfiguration
Please specify com.amazonaws.services.s3.transfer.TransferManagerConfiguration to the class. So to configure the settings of TransferManager.

[[S3Encryption]]
.[.eeonly]#S3Encryption#
Please specify org.iplass.mtp.impl.aws.lobstore.s3.S3Encryption to the class.

As our standard implementation, the following S3Encryption are provided.

- <<SseS3Encryption>>
- <<SseKmsEncryption>>

[[SseS3Encryption]]
.[.eeonly]#SseS3Encryption#
Please specify the implementing class of org.iplass.mtp.impl.aws.lobstore.s3.SseS3Encryption.

Perform the Encryption process with SSE-S3 method. There are no changeable settings available.

[[SseKmsEncryption]]
.[.eeonly]#SseKmsEncryption#
Please specify org.iplass.mtp.impl.aws.lobstore.s3.SseKmsEncryption to the class.

Perform the Encryption process with SSE-KMS methods.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| awsKmsKeyId | String | The Key Id for AWS Key Management Service (KMS)S3
|===

[[MetricsS3LobStore]]
.[.eeonly]#MetricsS3LobStore#
Please specify org.iplass.mtp.impl.micrometer.metrics.aws.lobstore.s3.MetricsS3LobStore to the class.

It’s S3LobStore with the metric collection function by Micrometer.
The same items as S3LobStore can be configured.

[[AddableMultiLobStore]]
.AddableMultiLobStore
Please specify org.iplass.mtp.impl.lob.lobstore.multi.AddableMultiLobStore to the class.

LobStore that can be configured as a single LobStore by combining multiple LobStores.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| lobStore | <<LobStore>>, Multiple | Set LobStore here.
| lobValidator | <<LobValidator>> | The validation process corresponding to Lob.
|===

[[LobValidator]]
.LobValidator
Please specify the implementing class of org.iplass.mtp.impl.lob.lobstore.LobValidator.

As the standard implementation, the following LobValidator are provided.

- <<LogLobValidator>>
- <<ProcessLobValidator>>

[[LogLobValidator]]
.LogLobValidator
Please specify org.iplass.mtp.impl.lob.lobstore.LogLobValidator to the class.

It simply output the log. There are no settings that can be configured.

[[ProcessLobValidator]]
.ProcessLobValidator
Please specify org.iplass.mtp.impl.lob.lobstore.ProcessLobValidator to the class.

Initiated the external process.
The following items can be configured.
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| command | String, Multiple | Specify the external process parameter.
| checksumAlgorithm | String | Specify the algorithms of the checksum.
You can chose from: Adler-32/CRC-32/MD5/SHA-1/SHA-256
|===

===== Example
[source, xml]
----
<service>
	<interface>org.iplass.mtp.impl.lob.LobStoreService</interface>
	<property name="lobDao" class="org.iplass.mtp.impl.lob.EncryptLobDao" />

	<property name="defaultLobStoreName" value="defaultStore" />
	<property name="defaultStore" class="org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore">
	</property>
	<!--
	<property name="binaryStore" class="org.iplass.mtp.impl.lob.lobstore.file.FileLobStore">
		<property name="rootDir" value="D:\tmp\fileLobStore" />
		<property name="overwriteFile" value="false" />
	</property>
	<property name="longTextStore" class="org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore">
	</property>
	 -->

	<!--
		Multiple LobStores can be combined into a single LobStore.
		New addition is performed according to the lobStore defined at the top.
		The system will search references from all lobStores.
		Deletion is also performed on all lobStores.
	 -->
	<!--
	<property name="binaryStore" class="org.iplass.mtp.impl.lob.lobstore.multi.AddableMultiLobStore">
		<property name="lobStore" class="org.iplass.mtp.impl.lob.lobstore.file.FileLobStore">
			<property name="rootDir" value="D:\tmp\fls2" />
		</property>
		<property name="lobStore" class="org.iplass.mtp.impl.lob.lobstore.file.FileLobStore">
			<property name="rootDir" value="D:\tmp\fls1" />
		</property>
		<property name="lobStore" class="org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore" />
	</property>
	 -->

	 <!--
		Specify whether the Lob size is managed by Rdb (lob_store).
		Changed the layout of the lob_store table for size management control in ver1.5.2.
		If the lob_store table cannot be changed in the existing system, it can be avoided by specifying false. -->
	<property name="manageLobSizeOnRdb" value="false" />
</service>
----
