[[LobStoreService]]
=== LobStoreService
LOBデータの永続化を行うサービスです。

==== インタフェース名
----
org.iplass.mtp.impl.lob.LobStoreService
----

==== 実装クラス名
----
org.iplass.mtp.impl.lob.LobStoreService
----

==== LobStoreServiceの設定
LobStoreServiceを設定します。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| binaryStore | <<LobStore>> | バイナリデータのLobStore。
| longTextStore | <<LobStore>> | LongTextのLobStore。
| defaultLobStoreName | String | デフォルトとするLobストアの名前。デフォルト値は `default` です。
| manageLobSizeOnRdb | boolean | LobサイズをRdb(lob_store)で管理するか。デフォルト値は `false` （管理しない）です。
| temporaryKeepDay | int | テンポラリデータの保存日数。クリーナによりここで指定された日数よりも前のデータが削除されます。デフォルト値は `1` です。
| invalidKeepDay | int | 無効(非参照)データの保存日数。クリーナによりここで指定された日数よりも前のデータが削除されます。デフォルト値は `0` です。
| cleanCommitLimit | int | クリーナの削除処理のコミット単位。デフォルト値は `100` です。
|===

[[LobStore]]
.LobStore
classはorg.iplass.mtp.impl.lob.lobstore.LobStoreの実装クラスを指定します。

標準で以下のLobStoreを提供します。

- <<RdbLobStore>>
- <<FileLobStore>>
- <<S3LobStore>>
- <<MetricsS3LobStore>>
- <<AddableMultiLobStore>>

[[RdbLobStore]]
.RdbLobStore
classはorg.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStoreを指定します。

RDBに保存するLobStoreです。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| lobValidator | <<LobValidator>> | Lobに対するチェック処理。
|===

[[FileLobStore]]
.FileLobStore
classはorg.iplass.mtp.impl.lob.lobstore.file.FileLobStoreを指定します。

ファイルに保存するLobStoreです。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| rootDir | String | 保存先のルートディレクトリ。
| overwriteFile | boolean | ファイルの上書きを行うか。デフォルト値はfalse（上書きしない）です。
| lobValidator | <<LobValidator>> | Lobに対するチェック処理。
|===

[[S3LobStore]]
.[.eeonly]#S3LobStore#
classはorg.iplass.mtp.impl.aws.lobstore.s3.S3LobStoreを指定します。

S3に保存するLobStoreです。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| region | String | S3のリージョン
| endpoint | String | S3のendpoint
| bucketName | String | S3のバケット名
| encryption | <<S3Encryption>> | S3オブジェクトを暗号化する場合に指定
| overwriteFile | boolean | 既にS3オブジェクトが存在した場合に上書きを行うか否か。 +
デフォルト値はfalse（上書きしない）です。
| useTransferManager | boolean | TransferManagerを利用するか否か。デフォルト値はfalseです。
| transferManagerConfiguration | <<TransferManagerConfiguration>> | TransferManagerの設定
| transferManagerThreadPoolSize | int | TransferManagerで利用するスレッドプールのサイズ。 `-1` が設定された場合はAWSSDKのデフォルト値によってスレッドプールが作成されます。デフォルト値は `-1` です。
| lobValidator | <<LobValidator>> | Lobに対するチェック処理。
| requiredTagMap | String、Map形式 | S3オブジェクトにおいて、必要なタグの値をチェックする場合にMap形式で指定します。keyとしてタグ名、valueとしてタグ値を設定します。
| retryTagCheckIntervalMillis | long | タグチェックのリトライ間隔（ミリ秒）。
| retryTagCheckCount | int | タグチェックのリトライ回数。
|===

[[TransferManagerConfiguration]]
.TransferManagerConfiguration
classはcom.amazonaws.services.s3.transfer.TransferManagerConfigurationです。TransferManager関連の設定が可能です。

[[S3Encryption]]
.[.eeonly]#S3Encryption#
classはorg.iplass.mtp.impl.aws.lobstore.s3.S3Encryptionの実装クラスを指定します。

標準で、以下のS3Encryptionを提供しています。

- <<SseS3Encryption>>
- <<SseKmsEncryption>>

[[SseS3Encryption]]
.[.eeonly]#SseS3Encryption#
classはorg.iplass.mtp.impl.aws.lobstore.s3.SseS3Encryptionを設定します。

SSE-S3方式で暗号化します。設定変更可能な項目は有りません。

[[SseKmsEncryption]]
.[.eeonly]#SseKmsEncryption#
classはorg.iplass.mtp.impl.aws.lobstore.s3.SseKmsEncryptionを設定します。

SSE-KMS方式で暗号化します。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| awsKmsKeyId | String | AWS Key Management Service (KMS)S3のKey Id
|===

[[MetricsS3LobStore]]
.[.eeonly]#MetricsS3LobStore#
classはorg.iplass.mtp.impl.micrometer.metrics.aws.lobstore.s3.MetricsS3LobStoreを指定します。

Micrometerによるメトリクス収集機能を追加したS3LobStoreです。
S3LobStoreと同じ項目を設定可能です。

[[AddableMultiLobStore]]
.AddableMultiLobStore
classはorg.iplass.mtp.impl.lob.lobstore.multi.AddableMultiLobStoreを指定します。

複数のLobStoreを合わせて単一のLobStoreと設定することが可能なLobStoreです。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| lobStore | <<LobStore>>、複数指定可 | LobStoreの設定。
| lobValidator | <<LobValidator>> | Lobに対するチェック処理。
|===

[[LobValidator]]
.LobValidator
classにorg.iplass.mtp.impl.lob.lobstore.LobValidatorの実装クラスを設定します。

標準で、以下のLobValidatorを提供しています。

- <<LogLobValidator>>
- <<ProcessLobValidator>>

[[LogLobValidator]]
.LogLobValidator
classはorg.iplass.mtp.impl.lob.lobstore.LogLobValidatorを設定します。

単純にログを出力のみを行います。設定変更可能な項目は有りません。

[[ProcessLobValidator]]
.ProcessLobValidator
classはorg.iplass.mtp.impl.lob.lobstore.ProcessLobValidatorを設定します。

外部プロセスを起動します。
以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| command | String、複数指定可 | 外部プロセスとパラメータを指定します。
| checksumAlgorithm | String | checksumのアルゴリズムを指定します。
Adler-32/CRC-32/MD5/SHA-1/SHA-256のいずれかを指定してください。
|===

===== 設定例
[source, xml]
----
<service>
	<interface>org.iplass.mtp.impl.lob.LobStoreService</interface>
	<property name="lobDao" class="org.iplass.mtp.impl.lob.EncryptLobDao" />

	<property name="defaultLobStoreName" value="defaultStore" />
	<property name="defaultStore" class="org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore">
	</property>
	<!--
	<property name="binaryStore" class="org.iplass.mtp.impl.lob.lobstore.file.FileLobStore">
		<property name="rootDir" value="D:\tmp\fileLobStore" />
		<property name="overwriteFile" value="false" />
	</property>
	<property name="longTextStore" class="org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore">
	</property>
	 -->

	<!--
		複数のLobStoreを合わせて単一のLobStoreと設定することが可能。
		新規追加は先頭に定義されているlobStoreに対して行われる。
		参照はすべてのlobStoreにから検索する。
		削除もすべてのlobStoreに対して実行される。
	 -->
	<!--
	<property name="binaryStore" class="org.iplass.mtp.impl.lob.lobstore.multi.AddableMultiLobStore">
		<property name="lobStore" class="org.iplass.mtp.impl.lob.lobstore.file.FileLobStore">
			<property name="rootDir" value="D:\tmp\fls2" />
		</property>
		<property name="lobStore" class="org.iplass.mtp.impl.lob.lobstore.file.FileLobStore">
			<property name="rootDir" value="D:\tmp\fls1" />
		</property>
		<property name="lobStore" class="org.iplass.mtp.impl.lob.lobstore.rdb.RdbLobStore" />
	</property>
	 -->

	 <!--
		LobサイズをRdb(lob_store)で管理するかを指定する。
		ver1.5.2でサイズ管理制御のためにlob_storeテーブルのレイアウトを変更。
		既存システムでlob_storeテーブルが変更できない場合は、falseを指定することで回避可能。 -->
	<property name="manageLobSizeOnRdb" value="false" />
</service>
----
