[[OidCounter]]
=== OidCounter
This is a service for oid numbering.
It employs CounterService for numbering.
The setting needs to be changed depending on whether or not the RDB sequence numbering function is available.
If there is a sequence function (default setting), set `RdbSequenceCounterService`,
If not (MySQL), use `CachableRdbTableCounterService`.

==== Interface Name
----
org.iplass.mtp.impl.counter.CounterService
----

==== Implementing Class Name
.With Sequence mechanism
----
org.iplass.mtp.impl.counter.RdbSequenceCounterService
----

.Without Sequence mechanism
----
org.iplass.mtp.impl.counter.CachableRdbTableCounterService
----

==== RdbSequenceCounterService
RdbSequenceCounterService can be configured with the folloiwing items.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| sequenceNameMap | <<SequenceNameMap>>, Multiple | Mapping of numbering unit and numbering table.
|===

[[SequenceNameMap]]
.SequenceNameMap
Set mapping of numbering unit and numbering table.
The following items can be set.

[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| name | String | The name of the numbering unit.
| value | String | RDB sequence name.
|===

==== Settings of CachableRdbTableCounterService
CachableRdbTableCounterService can be configured with the following items.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| separateTransaction | boolean | Specify whether to separate the transaction. The default value is false.
| retryCount | int | Number of times to retry when the counter fails. The default value is 3.
| counterTypeName | String |  Define the type of the counter. The default is `defaultCounter`.
| cacheSize | int | Cache size, the default is 20.
|===

===== Example
[source,xml]
----
<!-- Default Settings -->
<service name="OidCounter">
	<interface>org.iplass.mtp.impl.counter.CounterService</interface>
	<class>org.iplass.mtp.impl.counter.RdbSequenceCounterService</class>
	<property name="sequenceNameMap">
		<property name="oid" value="SEQ_OBJ_ID" />
		<property name="rbid" value="SEQ_RB_ID" />
		<property name="lobid" value="SEQ_LOB_ID" />
		<property name="logid" value="SEQ_LOG_ID" />
	</property>
</service>

<!-- MySQL -->
<service name="OidCounter">
	<interface>org.iplass.mtp.impl.counter.CounterService</interface>
	<class>org.iplass.mtp.impl.counter.CachableRdbTableCounterService</class>
	<property name="counterTypeName" value="OidCounter" />
	<property name="cacheSize" value="20" />
	<property name="retryCount" value="3" />
</service>

----
