[[SmsService]]
=== SmsService
SMSテンプレートの定義（メタデータ）の管理と、SMS送信を行うためのサービスです。
SMS送信の実装として、Twilioを利用したSMS送信のモジュールを標準提供します。

==== インタフェース名
----
org.iplass.mtp.impl.sms.SmsService
----


==== 実装クラス名
.[.eeonly]#Twilioを利用したSMS送信#
----
org.iplass.mtp.impl.sms.twilio.TwilioSmsService
----


==== [.eeonly]#TwilioSmsServiceの設定#
TwilioによるSMS送信を利用する場合、TwilioSmsServiceを設定します。
Twilio契約時に取得される「ACCOUNT SID」と「AUTH TOKEN」が必要です。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| accountSid | String、必須 | ACCOUNT SID。
| authToken | String、必須 | AUTH TOKEN。
| region | String | Twilio サービスのリージョンを設定します。設定可能な値は link:https://www.twilio.com/docs/global-infrastructure/edge-locations/legacy-regions[こちら, window="_blank"] を参照ください。
| edge | String | Twilio サービスのエッジロケーションを設定します。設定可能な値は link:https://www.twilio.com/docs/global-infrastructure/edge-locations[こちら, window="_blank"] を参照ください。
| userAgentExtensions | String、複数指定可能 | Twilio サービスへリクエスト時の User-Agent ヘッダーの拡張設定。
| defaultFrom | String | デフォルトの送信元電話番号。
| messageCustomizerList | <<TwilioSmsMessageCustomizer>>、複数指定可能 | SMS送信時のメッセージカスタム処理リスト。
| httpClientConfig | <<HttpClientConfig_tw, HttpClientConfig>> | HTTPクライアントの設定。
| listener | <<SendSmsMailListener>>、複数指定可 | SMS送信時のListener。
|===

[[TwilioSmsMessageCustomizer]]
.TwilioSmsMessageCustomizer
class には org.iplass.mtp.impl.sms.twilio.TwilioSmsMessageCustomizer を実装したクラスを指定します。 +
標準で提供する機能は存在しません。

メッセージをカスタマイズする処理を実装し、実装したクラスを service-config の設定に追加してください。

[[HttpClientConfig_tw]]
.HttpClientConfig
classはorg.iplass.mtp.impl.http.HttpClientConfigを指定します。

以下の項目を設定可能です。
[cols="1,1,3", options="header"]
|====================
| 項目 | 値 | 説明
| connectionTimeout | int | HTTPコネクションを確立する際のタイムアウト（ミリ秒）。デフォルト値は30000（30秒）です。
| soTimeout | int | HTTP通信時のsocket timeout (SO_TIMEOUT)（ミリ秒）。デフォルト値は30000（30秒）です。
| poolingMaxTotal | int | httpコネクションのプールの最大数。デフォルト値は20です。
| poolingDefaultMaxPerRoute | int | ドメイン単位のhttpコネクションの最大数。デフォルト値は2です。
| poolingTimeToLive | int | プールされているhttpコネクションの生存期間（ミリ秒）。デフォルトは無制限です。
| proxyHost | String | プロキシサーバのホスト。
| proxyPort | int | プロキシサーバのポート番号。
| httpClientBuilderFactory | <<HttpClientBuilderFactory_tw, HttpClientBuilderFactory>> |
カスタムのHttpClientBuilderを生成したい場合に指定します。
|====================

[[HttpClientBuilderFactory_tw]]
.HttpClientBuilderFactory
classはorg.iplass.mtp.impl.http.HttpClientBuilderFactoryを実装するクラスを指定します。

標準で以下のHttpClientBuilderFactoryを提供します。

* <<MicrometerHttpClientBuilderFactory>>

[[SendSmsMailListener]]
.SendSmsMailListener
classはorg.iplass.mtp.sms.SendSmsMailListenerの実装クラスを指定します。

標準で以下のSendSmsMailListenerを提供します。

- <<MetricsSendSmsMailListener>>

[[MetricsSendSmsMailListener]]
.MetricsSendSmsMailListener
classはorg.iplass.mtp.impl.micrometer.metrics.sms.MetricsSendSmsMailListenerを指定します。

Micrometerによるメトリクス収集機能を追加したSendSmsMailListenerです。
設定変更可能な項目はありません。

===== 設定例
[source, xml]
----
<service>
	<interface>org.iplass.mtp.impl.sms.SmsService</interface>
	<class>org.iplass.mtp.impl.sms.twilio.TwilioSmsService</class>
	<property name="accountSid" value="yourOwnAccountSid"/>
	<property name="authToken" value="yourOwnAuthToken"/>
	<property name="edge" value="tokyo"/>

	<property name="defaultFrom" value="+1234......."/>

	<!-- org.iplass.mtp.impl.sms.twilio.TwilioSmsMessageCustomizer 実装クラスを設定する -->
	<!--
	<property name="messageCustomizerList" class="...set your implementation class..." />
	-->
	
	<!-- Development
	<property name="httpClientConfig" class="org.iplass.mtp.impl.http.HttpClientConfig">
		<property name="connectionTimeout" value="30000" />
		<property name="soTimeout" value="30000" />
		<property name="proxyHost" value="proxyhost.dentsusoken.com" />
		<property name="proxyPort" value="8080" />
	</property>
	-->
</service>
----
