[[TenantContextService]]
=== TenantContextService
テナント全体の振る舞いを設定するサービスです。

==== インタフェース名
----
org.iplass.mtp.impl.core.TenantContextService
----


==== 実装クラス名
----
org.iplass.mtp.impl.core.TenantContextService
----


==== TenantContextServiceの設定
テナント全体の振る舞いを設定します。

===== 設定項目
[cols="1,1,3", options="header"]
|===
| 項目 | 値 | 説明
| defaultTenantName | String | デフォルトのテナント名。
| defaultPasswordPatternErrorMessage | String | デフォルトのパスワード形式エラーメッセージ。
| defaultMailFrom | String | デフォルトのメール送信Fromアドレス。テナント設定でFromアドレスが指定されていない場合に利用されます。
| defaultMailFromName | String | デフォルトのメール送信Fromアドレス個人名。
| sharedTenantId | int a| 共有テナントのID。RDBの場合、このテナントが共有テナントとして利用されます。-1は共有テナントなしとみなし動作します。デフォルト値は-1です。

共有テナントを有効化した状態でEntity定義を変更した場合は、それに連動してデータのメンテナンス処理が実行されますが、共有されたEntity定義を変更した場合は、すべてのテナントのデータに対してメンテナンス処理が実行されます。 

CAUTION: Entityデータを格納するDBを複数のプロジェクト・システムで共有している場合、共有テナントを有効化した場合、意図せず他のプロジェクト・システムのデータを上書きしてしまう危険性があります。 +
共有テナントを有効化する場合、他のプロジェクト・システムとDBの共有はおこなわないことを推奨します。

| localTenantIds | int、複数指定可 a| 共有テナントを有効にした際、Entity定義更新時のデータメンテナンスを実施する個別テナントを指定可能。
設定されていない場合は、DBに登録されているすべてのテナント（共有テナント除く）を個別テナントとみなしデータメンテナンスを実施します。

sharedTenantIdの説明にあるように、共有テナントを有効化する場合、他プロジェクト・システムとDB共有しないことを推奨しますが、それが難しい場合にこのlocalTenantIdsを利用することが可能です。
共有されたEntity定義が変更された場合、データメンテナンス処理を指定されたテナントに限定することが可能となります。
|===

////
この辺はアプリ側ではコントロールできなさそうなのでコメントアウト

| tenantResource | <<TenantResource>>、複数指定可 | テナントのロード/アンロードに合わせて管理したいリソースを設定します。

[[TenantResource]]
.TenantResource
classにorg.iplass.mtp.impl.core.TenantResourceのサブクラスを指定します。

標準で、以下のTenantResourceを提供しています。

- <<TenantAuthorizeContext>>
- <<ContentCacheContext>>
- <<QueryCacheTenantResource>>
- <<BeanValidationResource>>
- <<CubeContext>>
- <<TenantAvaliableTenantResource>>

[[TenantAuthorizeContext]]
.TenantAuthorizeContext
valueにorg.iplass.mtp.impl.auth.authorize.builtin.TenantAuthorizeContextを指定します。

設定可能な項目はありません。

[[ContentCacheContext]]
.ContentCacheContext
valueにorg.iplass.mtp.impl.web.actionmapping.cache.ContentCacheContextを指定します。

ActionMappingのキャッシュを管理します。
設定可能な項目はありません。

[[QueryCacheTenantResource]]
.QueryCacheTenantResource
valueにorg.iplass.mtp.impl.entity.cache.QueryCacheTenantResourceを指定します。

設定可能な項目はありません。

[[BeanValidationResource]]
.BeanValidationResource
valueにorg.iplass.mtp.impl.validation.bean.BeanValidationResourceを指定します。

設定可能な項目はありません。

[[CubeContext]]
.CubeContext
valueにorg.iplass.mtp.impl.aggregation.cube.CubeContextを指定します。

設定可能な項目はありません。

[[TenantAvaliableTenantResource]]
.TenantAvaliableTenantResource
valueにorg.iplass.mtp.impl.tenant.available.TenantAvaliableTenantResourceを指定します。

設定可能な項目はありません。
////

===== 設定例
[source,xml]
----
<service>
	<interface>org.iplass.mtp.impl.core.TenantContextService</interface>
	<property name="defaultTenantName" value="iPLAss" />
	<property name="defaultMailFrom" value="notenant@nomail.iplass.org" />

	<!-- ■ if use shared tenant, set shared tenant id.(value:-1 for no use of shared tenant) -->
	<!--
	<property name ="sharedTenantId" value="-1" />
	-->
	<!--
		共有テナントを有効にした際、その共有テナントの配下の個別テナントを定義可能。
		定義されていない場合は、DBに登録されているすべてのテナント（共有テナント除く）を個別テナントとみなし動作します。
	-->
	<!--
	<property name ="localTenantIds" value="148" />
	<property name ="localTenantIds" value="149" />
	-->
</service>
----