[[TenantContextService]]
=== TenantContextService
The service that affects all the tenants.

==== Interface Name
----
org.iplass.mtp.impl.core.TenantContextService
----


==== Implementing Class Name
----
org.iplass.mtp.impl.core.TenantContextService
----


==== Settings of TenantContextService
These settings take effects on all tenants.

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
| defaultTenantName | String | Default tenant name.
| defaultPasswordPatternErrorMessage | String | Default password format error message.
| defaultMailFrom | String | Default email sending From address. Used when the From address is not specified in the tenant settings.
| defaultMailFromName | String | Default email sending From address personal name.
| sharedTenantId | int a| Shared tenant ID. In the case of RDB, this tenant is used as a shared tenant. -1 works as if there is no shared tenant. The default value is -1.

If the Entity definition is changed while the shared tenant is enabled, the corresponding data maintenance process will be executed in accompany with it. However, if the shared Entity definition is changed, maintenance process will be executed for the data of all tenants. 

CAUTION: When the database that stores Entity data is shared by multiple project systems, there is a risk that the data of other project systems will be overwritten unintentionally if the shared tenant is enabled. +
When enabling the shared tenant, it is recommended not to share the database with other project systems.

| localTenantIds | int, Multiple a| When shared tenant is enabled, it is possible to specify an specific tenant to perform data maintenance when updating the Entity definition.
If it is not set, all tenants (excluding shared tenants) registered in the DB are regarded as individual tenants and data maintenance is performed on all of them.

As explained in the description of sharedTenantId, when enabling a shared tenant, it is recommended to not to share the DB with other project systems, but it is possible to use this localTenantIds when it is difficult.
When shared Entity definition is changed, it is possible to limit data maintenance processing to the specified tenant.
|===

////
この辺はアプリ側ではコントロールできなさそうなのでコメントアウト

| tenantResource | <<TenantResource>>, Multiple | テナントのロード/アンロードに合わせて管理したいリソースcan be configured with the following items.

[[TenantResource]]
.TenantResource
Please specify the subclass of org.iplass.mtp.impl.core.TenantResource.

As the standard implementation, the followingTenantResourceを提供しています。

- <<TenantAuthorizeContext>>
- <<ContentCacheContext>>
- <<QueryCacheTenantResource>>
- <<BeanValidationResource>>
- <<CubeContext>>
- <<TenantAvaliableTenantResource>>

[[TenantAuthorizeContext]]
.TenantAuthorizeContext
valueにorg.iplass.mtp.impl.auth.authorize.builtin.TenantAuthorizeContextを指定します。

There is no configurable items for this configuration options.

[[ContentCacheContext]]
.ContentCacheContext
valueにorg.iplass.mtp.impl.web.actionmapping.cache.ContentCacheContextを指定します。

ActionMappingのCacheを管理します。
There is no configurable items for this configuration options.

[[QueryCacheTenantResource]]
.QueryCacheTenantResource
valueにorg.iplass.mtp.impl.entity.cache.QueryCacheTenantResourceを指定します。

There is no configurable items for this configuration options.

[[BeanValidationResource]]
.BeanValidationResource
valueにorg.iplass.mtp.impl.validation.bean.BeanValidationResourceを指定します。

There is no configurable items for this configuration options.

[[CubeContext]]
.CubeContext
valueにorg.iplass.mtp.impl.aggregation.cube.CubeContextを指定します。

There is no configurable items for this configuration options.

[[TenantAvaliableTenantResource]]
.TenantAvaliableTenantResource
valueにorg.iplass.mtp.impl.tenant.available.TenantAvaliableTenantResourceを指定します。

There is no configurable items for this configuration options.
////

===== Example
[source, xml]
----
<service>
	<interface>org.iplass.mtp.impl.core.TenantContextService</interface>
	<property name="defaultTenantName" value="iPLAss" />
	<property name="defaultMailFrom" value="notenant@nomail.iplass.org" />

	<!-- ■ if use shared tenant, set shared tenant id.(value:-1 for no use of shared tenant) -->
	<!--
	<property name ="sharedTenantId" value="-1" />
	-->
	<!--
		When a shared tenant is enabled, we can define specific tenants under that shared tenant.
		If it is not defined, all tenants (excluding shared tenants) registered in the DB will operate as individual tenants.
	-->
	<!--
	<property name ="localTenantIds" value="148" />
	<property name ="localTenantIds" value="149" />
	-->
</service>
----