[[WebhookService]]
=== WebhookService
This is the service to manage the ebhookTemplate definitions(Metadata) and the corresponding Webhook behaviors.

==== Interface Name
----
org.iplass.mtp.impl.webhook.WebhookService
----


==== Implementing Class Name
----
org.iplass.mtp.impl.webhook.WebhookServiceImpl
----


==== Configurations of WebhookService
To utilize Webhook, it is required to configure the WebhookService 

===== Configurable Items
[cols="1,1,3", options="header"]
|===
| Item | Value | Description
|retry| boolean | Indicate whether to retry the connection when failed.
|retryMaximumAttempts| int | 
(When retrying)Indicate the maximum retry limit.
|retryInterval| int | (When retrying)Indicate the time interval between each retry attempts.
|hmacHashAlgorithm| String | The hash algorithm used to generate HMAC key. If not specified, "HmacSHA256" will be used in default.
|hmacDefaultHeaderName| String | The default header to store the HMAC key. If not specified, "X-IPLASS-HMAC" will be used. If the header name is customized in WebhookTemplate definition, the customized name will be used in priority.

|httpClientConfig|<<HttpClientConfig_wh, HttpClientConfig>> | Config about the HTTP connection when sending Webhook.
|===


[[HttpClientConfig_wh]]
.HttpClientConfig
Please specify org.iplass.mtp.impl.http.HttpClientConfig to the class.
The following items can be configured.
[cols="1,1,3", options="header"]
|====================
| Item | Value | Description
| connectionTimeout | int | Timeout in milliseconds for establishing an HTTP connection. The default value is 30000 (30 seconds).
| soTimeout | int | socket timeout (SO_TIMEOUT) (milliseconds) during HTTP communication. The default value is 30000 (30 seconds).
| poolingMaxTotal | int | Maximum number of pools for http connections. The default value is 20.
| poolingDefaultMaxPerRoute | int | Maximum number of http connections per domain. The default value is 2.
| poolingTimeToLive | int | Lifetime of pooled http connections (milliseconds). The default is unlimited.
| proxyHost | String | Proxy server host.
| proxyPort | int | Proxy server port number.
| httpClientBuilderFactory | <<HttpClientBuilderFactory_wh, HttpClientBuilderFactory>> | Specify this if you want to create a custom HttpClientBuilder.
|====================

[[HttpClientBuilderFactory_wh]]
.HttpClientBuilderFactory
Please specify the implementation class of org.iplass.mtp.impl.http.HttpClientBuilderFactory to the class.

The following HttpClientBuilderFactory is provided as standard.

* <<MicrometerHttpClientBuilderFactory, [.eeonly]#MicrometerHttpClientBuilderFactory#>>


===== Example
[source,xml]
----
	<!-- Webhook -->
	<service>
		<interface>org.iplass.mtp.impl.webhook.WebhookService</interface>
		<class>org.iplass.mtp.impl.webhook.WebhookServiceImpl</class>
		<property name="retry" value="true" />
		<property name="retryMaximumAttempts" value="10" />
		<property name="retryInterval" value="500" />
		<property name="hmacHashAlgorithm" value="HmacSHA256" />
		<property name="hmacDefaultHeaderName" value="X-IPLASS-HMAC" />
<!-- 		<property name="httpClientConfig" class="org.iplass.mtp.impl.http.HttpClientConfig"> -->
<!-- 			<property name="proxyHost" value="localhost" /> -->
<!-- 			<property name="proxyPort" value="8080" /> -->
<!-- 			<property name="poolingMaxTotal" value="20" /> -->
<!-- 			<property name="poolingDefaultMaxPerRoute" value="20" /> -->
<!-- 			<property name="poolingTimeToLive" value="50000" /> -->
<!-- 		</property> -->
	</service>
	
	<!-- WebhookEndpoint -->
	<service>
		<interface>org.iplass.mtp.impl.webhook.endpoint.WebhookEndpointService</interface>
		<class>org.iplass.mtp.impl.webhook.endpoint.WebhookEndpointServiceImpl</class>
	</service>
		
----