[[entitylisting_management]]
== EntityListingの管理

[[create_entitylisting]]
=== EntityListingの作成
EntityListingアイコンを右クリックし、 `EntityListingを作成する` を選択します。
// TODO: EntityListing作成のスクリーンショット

[[entitylisting_setting]]
=== 設定
メタデータを定義しなくてもEntityListing機能自体は実行可能です。 +
ただし、ユーザーによって利用可能なエンティティやプロパティを制御したい場合には、EntityListingメタデータを作成します。

[[entitylisting_defaultsetting]]
==== Default Setting
ここでの設定は、Custom Settingを設定していないエンティティに対してデフォルトで適用される設定です。

[cols="1,5a", options="header"]
|===
|設定項目|設定値
|exclude mtp entities
|選択可能なエンティティから「mtp.*」を除外します。Custom Settingでエンティティを1つでも選択している場合は、そちらが優先されます。

|exclude inherited properties
|選択可能なプロパティとして継承プロパティを除外するかを設定します。 +
Custom Settingでエンティティ別にプロパティ設定をしている場合は、そちらが優先されます。 +
選択した場合、オブジェクトIDが選択可能なプロパティとして選択できなくなるため、エンティティの参照画面が開けなくなります。

|to edit the narrowing condition, as dialog
|抽出項目に集計関数がある場合に利用可能な絞り込み条件（Having条件）の指定方法を設定します。

ダイアログモードの場合::
絞り込みボタンが表示され、クリックで結果の絞り込みを行うダイアログを表示

直接編集モードの場合::
フィルタの下に絞り込み対象を指定する領域を表示

|handle inherited user property as name
|エンティティの「作成者」「更新者」「ロックユーザー」を名前で扱います。 +
Filter条件に指定する場合は、Userエンティティを参照します。 +
検索結果には名前が出力されます（ただしソートはOIDで比較します）。

|display user name in privileged execution
|`handle inherited user property as name`がチェックされている場合、ユーザー名を特権実行で取得します。 +
それによりユーザー情報のEntity、またはユーザー名のプロパティに参照権限がないユーザーでもユーザー名を表示することが可能になります。

|show reference dialog for edit mode
|エンティティの参照画面を開く際に編集可能モードで開くかを指定します。

|show reference dialog from name property
|抽出項目として「name」プロパティを指定した際に、参照画面のリンクを表示するかを指定します。

|can file download
|条件編集画面で「Download」を利用かを指定します。

|use property name in file header
|ファイルヘッダに表示名ではなくプロパティ名を出力します。

|file type
|ダウンロードで利用するファイル形式を指定します。

CSV::
CSVファイルを利用します。

EXCEL::
EXCELファイルを利用します。

SPECIFY::
CSVファイルかEXCELファイルのどちらを利用するかを画面で選択します。

未指定の場合は、MdcConfigServiceの`entityListingFileSupportType`によって動作します。

|file multiple format
|ファイルダウンロード時の多重度（複数値）プロパティの出力形式を指定します。

Each Column::
多重度の数分別々の列に出力します。

One Column::
1つの列にカンマ区切りでまとめて出力します。

One Column Fill Null::
1つの列にカンマ区切りでまとめて出力します。 +
登録データが多重度分保存されていない場合にも多重度分空を補完します。

|File Name Format
|ファイルダウンロード時のファイル名をGroovyTemplate書式を利用して指定します。 +
フォーマットが指定されている場合、ボタンに「(*)」が表示されます。 +
また、`/`とスペースについては、`_`（アンダースコア）に変換します。 +
利用可能なバインド変数は、編集ダイアログの「Notes」を参照してください。

|Custom ViewScript
|条件編集画面内に埋め込むカスタムコード（HTML）を設定できます。 +
GroovyTemplateとして定義します。 +
`templateInterpretType`でHTMLまたはVue SFC形式を指定可能です。

|Query interrupter class name
|実際に検索が実行される直前に、実行するEQLをカスタマイスするためのクラスを指定します。 +
詳細は<<queryinterrupter, Query Interrupter>>を参照してください。

|===

[[queryinterrupter]]
==== Query interrupter
パフォーマンス改善などの目的で、実際に検索を行う直前のEQLをカスタマイスことも可能です。
以下のQueryInterrupterを実装したJavaクラスまたはUtilityClassを指定します。

----
org.iplass.mtp.mdc.view.entitylisting.EntityListingQueryInterceptor
----

EntityListingの検索では、ページング制御のための件数取得と実際のデータ検索の2回EQLが実行されます。
QueryInterrupterではこの直前にEQLをカスタマイスする処理を追加可能です。

.処理一覧
[cols="1,1,1,2",options="header"]
|===
|メソッド
|引数
|戻り値
|処理内容

|beforeCount
|EntityListingQueryContext
|void
|件数取得前処理を行います。

|beforeSearch
|EntityListingQueryContext
|void
|検索前処理を行います。

|afterSearch
|Object[] data, EntityListingQueryContext
|void
|検索後処理を行います。afterSearchでは1レコード毎に処理が呼ばれます。 +
`EntityListingQueryContext#getSelectIndex(propertyName)` を利用して、Select句の何番目にプロパティが含まれているかを取得可能です。
|===

[source,java]
----
package sample.entitylisting;

import org.iplass.mtp.entity.query.Query;
import org.iplass.mtp.entity.query.hint.CacheHint;
import org.iplass.mtp.entity.query.hint.CacheHint.CacheScope;
import org.iplass.mtp.entity.query.hint.TimeoutHint;
import org.iplass.mtp.mdc.view.entitylisting.EntityListingQueryContext;
import org.iplass.mtp.mdc.view.entitylisting.EntityListingQueryInterceptor;
import org.iplass.mtp.auth.User;

public class SampleQueryInterrupter implements EntityListingQueryInterceptor {

	@Override
	public void beforeCount(EntityListingQueryContext context) {
		Query query = context.getQuery();
		query.hint(new CacheHint(CacheScope.GLOBAL, 60));
	}

	@Override
	public void beforeSearch(EntityListingQueryContext context) {
		Query query = context.getQuery();
		query.hint(new CacheHint(CacheScope.GLOBAL, 60))
		    .hint(new TimeoutHint(120));
	}

	@Override
	public void afterSearch(Object[] data, EntityListingQueryContext context) {
		if (context.getEntityName().equals(User.DEFINITION_NAME)) {
			if (context.getSelectIndex(User.MAIL) != null) {
				for (int index : context.getSelectIndex(User.MAIL)) {
					data[index] = "*****";
				}
			}
		}
	}

}
----

[[entitylisting_customsetting]]
==== Custom Setting
Default Settingではなく、エンティティ個別に設定を行いたい場合に指定します。

// TODO: Custom Setting画面スクリーンショット

[cols="1,5a", options="header"]
|===
|設定項目|設定値
|Target|参照可能なエンティティ」を選択します。 +
対象外のエンティティを参照しようとした場合は権限エラーとなります。 +
1つも選択されていない場合は、Default Settingの`exclude mtp entities`設定により対象を決定します。
|DisRoot|`Target`指定されたエンティティのうち、エンティティの選択リストから除外したいエンティティ」を選択します。 +
他エンティティの参照先としてのみ検索を許可する場合に指定します。
|Custom|個別にEntity Custom Setting設定されている場合に「Y」が表示されます。
|===

個別にプロパティなどを絞り込みたい場合は、対象のエンティティをダブルクリックしてください。
右側にエンティティごとの設定項目が表示されます。

[[entitylisting_entitycustomsetting]]
==== Entity Custom Setting

[cols="1,5a", options="header"]
|===
|設定項目|設定値
|exclude inherited properties|選択可能なプロパティとして継承プロパティを除外します。 +
下のプロパティ選択部分で1件でも選択されている場合は、そちらが優先されます。
|handle inherited user property as name|エンティティの「作成者」「更新者」「ロックユーザー」を名前で扱います。
|display user name in privileged execution|`handle inherited user property as name`がチェックされている場合、ユーザー名を特権実行で取得します。
|show reference dialog for edit mode|エンティティの参照画面を開く際に編集可能モードで開くかを指定します。
|show reference dialog from name property|抽出項目として「name」プロパティを指定した際に、参照画面のリンクを表示するかを指定します。
|View Name Script|エンティティの参照画面を開く際のView名をGroovyTemplate書式を利用して指定します。 +
詳細は<<el_viewname, View Name Script>>を参照してください。
|file name format|ファイルダウンロード時のファイル名をGroovyTemplate書式を利用して指定します。 +
「Default Setting」とと同様です。
|Without Condition Reference|Entity権限における限定条件を適用せずに検索を実行する参照先プロパティ名を設定します。 +
特権実行する場合、または`Query interrupter class name`の設定がある場合はそちらが優先されます。
|Query interrupter class name|実際に検索が実行される直前に、実行するEQLをカスタマイスするためのクラスを指定します。 +
未指定の場合は「Default Setting」の設定が有効になります。 +
詳細は<<queryinterrupter, Query Interrupter>>を参照してください。
|property list|選択可能としたいプロパティをチェックしてください。
|===

[[el_viewname]]
==== View Name Script
エンティティの参照画面を開く際のView名をGroovyTemplate書式を利用して指定します。
値が設定されている場合、ボタンに「(*)」が表示されます。

利用可能なバインド変数は、編集ダイアログの「Notes」を参照してください。

.（例）文字列直接指定
[source,groovy]
----
opeView
----

.（例）GroovyTemplate指定
[source,groovy]
----
<%@import org.iplass.mtp.entity.Entity %>

<%
def viewName = "XXXXXXXXX";
%>

${viewName}
----

検索結果のリンク表示時には、表示対象データのOIDが「oid」としてバインドされています。
Filter条件としてReferenceを指定した場合の参照時はOIDはバインドされません。

=== 表示方法

==== メニューへの登録
条件設定画面を表示するにはメニューにActionMenuItemを登録します。

ActionMenuItemには雛型として`mdc/template/entitylisting/ViewEntityListingAction`というメニューアイテムがあります。
このActionMenuItemをコピーしてメニューアイテムを編集してください。

[cols="1,5a", options="header"]
|===
|項目|設定値
|Name|管理しやすいように設定してください。
|DisplayName|メニューの表示名になります。
|Execute Action|`mdc/entitylisting/view`を指定してください。
|Parameter|`defName=XXX&entityName=XXX`

defName::: 作成したEntityListingメタデータ名を指定します。
entityName::: 初期表示時に選択したいエンティティ名を指定します。 +
defNameには表示可能なエンティティを指定する必要があります。
|===

NOTE: EntityListingメタデータが1つでも登録されている場合は、雛形の`ViewEntityListingAction`から起動しようとするとエラーが発生します。
MetaDataを作成後は必ずパラメータに`defName`を指定してください。
