// NOTE:
// このファイルは prompt.adoc から include されています。
// prompt_setting_platform_*.adoc のタイトルは "====" から始めてください。
// タグの接頭辞として "prompt_setting_platform_" を設定してください。
[[prompt_setting_platform_aws]]
==== AWSプラットフォーム
AWSプラットフォームでは Amazon Bedrock, Amazon Bedrock AgentCore の以下のサービスを利用することができます。

.AWSで利用可能なプラットフォームタイプ
* <<prompt_setting_platform_aws_bedrock>>
** Amazon Bedrock サービスのモデルに対してリクエストを行います。
* <<prompt_setting_platform_aws_bedrock_agent>>
** AWS上に定義した Amazon Bedrock Agent に対してリクエストを行います。
* <<prompt_setting_platform_aws_bedrock_flow>>
** AWS上に定義した Amazon Bedrock Flow サービスに対してリクエストを行います。
* <<prompt_setting_platform_aws_bedrock_knowledge_base>>
** AWS上に定義した Amazon Bedrock Knowledge Base を利用したリクエストを行います。
* <<prompt_setting_platform_aws_bedrock_agent_core_harness>>
** AWS上に定義した Amazon Bedrock AgentCore Harness に対してリクエストを行います。
* <<prompt_setting_platform_aws_bedrock_agent_core_runtime_http>>
** AWS上に定義した Amazon Bedrock AgentCore Runtime(http) に対してリクエストを行います。


[[prompt_setting_platform_aws_bedrock]]
===== Bedrock
Bedrock Converse API を利用し、Amazon Bedrock サービスで利用可能なモデルに対してリクエストを行うことができます。 +
Converse API の詳細については、Amazon Bedrock のドキュメントを参照してください。

状態には対応していません。

設定項目は次の通りです。

[cols="1,3", options="header,autowidth"]
|===
|項目
|説明

|Model ID
|Amazon Bedrock サービスのモデルのIDを設定します。 +
設定するモデルのIDは、Converse API に対応しているモデルIDを設定してください。 +
Converse API に対応しているモデルIDの詳細については、Amazon Bedrock のドキュメントを参照してください。

|Guardrail - Guardrail ID
|AWS で設定した Amazon Bedrock のガードレールのIDを設定します。 +
ガードレールの設定については Amazon Bedrock のドキュメントを参照してください。

|Guardrail - Guardrail Version
|AWS で設定した Amazon Bedrock のガードレールのIDに対応するバージョンを設定します。 +
1 ～ のバージョン番号もしくは `DRAFT` を設定します。

|Inference Config - Max Tokens
|Bedrock 推論パラメータ maxTokens を設定します。数値を設定してください。

|Inference Config - Stop Sequences
|Bedrock 推論パラメータ stopSequences を設定します。カンマ区切りで複数設定可能です。 +
`END, STOP` のようにカンマ区切りで複数の停止シーケンスを設定できます。

|Inference Config - Temperature
|Bedrock 推論パラメータ temperature を設定します。0.0 から 1.0 の範囲の数値を設定してください。

|Inference Config - TopP
|Bedrock 推論パラメータ topP を設定します。0.0 から 1.0 の範囲の数値を設定してください。

|Structured Output Config - Schema Name
|構造化されたデータのスキーマの名前を設定します。 +
Structured Output Config は利用するモデルが対応している必要があります。対応するモデルは Amazon Bedrock のドキュメントを参照してください。

|Structured Output Config - Schema Description
|構造化されたデータのスキーマの説明を設定します。 +
Structured Output Config は利用するモデルが対応している必要があります。対応するモデルは Amazon Bedrock のドキュメントを参照してください。

|Structured Output Config - Json Schema
|AIリクエストを実行した際の応答を構造化されたデータとして受け取るための設定項目です。 +
構造化されたデータのスキーマを Json Schema 形式で設定します。 +
Structured Output Config は利用するモデルが対応している必要があります。対応するモデルは Amazon Bedrock のドキュメントを参照してください。

|Request Before Customize
|AIリクエストを実行する前に、リクエストの内容をカスタマイズするための設定項目です。 +
AdminConsole で設定できない内容を設定する場合に利用します。 +
Groovy Script 形式でカスタマイズ処理を実装します。

カスタマイズするリクエストインスタンスは、`software.amazon.awssdk.services.bedrockruntime.model.ConverseRequest.Builder` クラスのインスタンスになります。
|===

[[prompt_setting_platform_aws_bedrock_agent]]
===== Bedrock - Agent
Bedrock InvokeAgent API を利用し、Amazon Bedrock Agent で定義したエージェントに対してリクエストを行うことができます。 +
InvokeAgent API の詳細については、Amazon Bedrock のドキュメントを参照してください。

[WARNING]
====
Amazon Bedrock Agents は Amazon Bedrock Agents Classic と名称を変更し、メンテナンスモードとなっており、 +
2026年7月30日以降は新規に Agent を作成することができなくなっています。

Amazon Bedrock AgentCore の利用・移行を検討してください。
====

状態に対応しており、保持する値は以下の通りです。

.状態に保存する内容
* メモリID
* セッションID

設定項目は次の通りです。

[cols="1,3", options="header,autowidth"]
|===
|項目
|説明

|Agent ID
|Amazon Bedrock Agent で定義したエージェントのIDを設定します。

|Agent Alias ID
|Amazon Bedrock Agent で定義したエージェントのIDに対するエイリアスIDを設定します。

|Enable Trace
|Amazon Bedrock Agent の実行のトレースを有効にするかどうかを設定します。チェックすることでトレースを有効にすることができます。 +
トレースを有効にした場合、プログラムでトレースイベントをハンドリングして、エージェントの実行の詳細を取得することができます。

|Use Memory
|Amazon Bedrock Agent の実行でメモリ機能を利用するかどうかを設定します。チェックすることでメモリ機能を利用することができます。 +
メモリ機能を利用する場合、エージェント設定で「メモリ - セッション要約を有効にする」を有効にする必要があります。

|Request Before Customize
|AIリクエストを実行する前に、リクエストの内容をカスタマイズするための設定項目です。 +
AdminConsole で設定できない内容を設定する場合に利用します。 +
Groovy Script 形式でカスタマイズ処理を実装します。

カスタマイズするリクエストインスタンスは、`software.amazon.awssdk.services.bedrockagentruntime.model.InvokeAgentRequest.Builder` クラスのインスタンスになります。
|===


[[prompt_setting_platform_aws_bedrock_flow]]
===== Bedrock - Flow
Bedrock InvokeFlow API を利用し、Amazon Bedrock Flow で定義したフローに対してリクエストを行うことができます。 +
InvokeFlow API の詳細については、Amazon Bedrock のドキュメントを参照してください。

状態に対応しており、保持する値は以下の通りです。

.状態に保存する内容
* 実行ID
* フロー完了理由などのフローの実行に関する情報

設定項目は次の通りです。

[cols="1,3", options="header,autowidth"]
|===
|項目
|説明

|Flow ID
|Amazon Bedrock Flow で定義したフローのIDを設定します。

|Flow Alias ID
|Amazon Bedrock Flow で定義したフローのIDに対するエイリアスIDを設定します。

|Enable Trace
|Amazon Bedrock Flow の実行のトレースを有効にするかどうかを設定します。チェックすることでトレースを有効にすることができます。 +
トレースを有効にした場合、プログラムでトレースイベントをハンドリングして、フローの実行の詳細を取得することができます。

|Request Before Customize
|AIリクエストを実行する前に、リクエストの内容をカスタマイズするための設定項目です。 +
AdminConsole で設定できない内容を設定する場合に利用します。 +
Groovy Script 形式でカスタマイズ処理を実装します。

カスタマイズするリクエストインスタンスは、`software.amazon.awssdk.services.bedrockagentruntime.model.InvokeFlowRequest.Builder` クラスのインスタンスになります。
|===


[[prompt_setting_platform_aws_bedrock_knowledge_base]]
===== Bedrock - Knowledge Base
Bedrock RetrieveAndGenerate API を利用し、Amazon Bedrock Knowledge Base で定義したナレッジを利用したリクエストを行うことができます。 +
RetrieveAndGenerate API の詳細については、Amazon Bedrock のドキュメントを参照してください。

状態に対応しており、保持する値は以下の通りです。

.状態に保存する内容
* セッションID

設定項目は次の通りです。

[cols="1,3", options="header,autowidth"]
|===
|項目
|説明

|Model ID
|Amazon Bedrock サービスのモデルのIDを設定します。 +
設定するモデルのIDは、RetrieveAndGenerate API に対応しているモデルIDを設定してください。 +
RetrieveAndGenerate API に対応しているモデルIDの詳細については、Amazon Bedrock のドキュメントを参照してください。

|Knowledge Base ID
|Amazon Bedrock Knowledge Base で定義したナレッジベースIDを設定します。

|Guardrail - Guardrail ID
|AWS で設定した Amazon Bedrock のガードレールのIDを設定します。 +
ガードレールの設定については Amazon Bedrock のドキュメントを参照してください。

|Guardrail - Guardrail Version
|AWS で設定した Amazon Bedrock のガードレールのIDに対応するバージョンを設定します。 +
1 ～ のバージョン番号もしくは `DRAFT` を設定します。

|Inference Config - Max Tokens
|Bedrock 推論パラメータ maxTokens を設定します。数値を設定してください。

|Inference Config - Stop Sequences
|Bedrock 推論パラメータ stopSequences を設定します。カンマ区切りで複数設定可能です。 +

|Inference Config - Temperature
|Bedrock 推論パラメータ temperature を設定します。0.0 から 1.0 の範囲の数値を設定してください。

|Inference Config - TopP
|Bedrock 推論パラメータ topP を設定します。0.0 から 1.0 の範囲の数値を設定してください。

|Request Before Customize
|AIリクエストを実行する前に、リクエストの内容をカスタマイズするための設定項目です。 +
AdminConsole で設定できない内容を設定する場合に利用します。 +
Groovy Script 形式でカスタマイズ処理を実装します。

カスタマイズするリクエストインスタンスは、`software.amazon.awssdk.services.bedrockagentruntime.model.RetrieveAndGenerateRequest.Builder` クラスのインスタンスになります。
|===

[[prompt_setting_platform_aws_bedrock_agent_core_harness]]
===== Bedrock AgentCore - Harness
Bedrock AgentCore InvokeHarness API を利用し、Amazon Bedrock AgentCore に定義したハーネスを利用したリクエストを行うことができます。 +
InvokeHarness API の詳細については、Amazon Bedrock のドキュメントを参照してください。

状態に対応しており、保持する値は以下の通りです。

.状態に保存する内容
* ランタイムセッションID

設定項目は次の通りです。

[cols="1,3", options="header,autowidth"]
|===
|項目
|説明

|Harness ARN
|Amazon Bedrock AgentCore で定義したハーネスの ARN を設定します。

|エンドポイント Qualifier
|Amazon Bedrock AgentCore で定義したハーネスのエンドポイントを設定します。 +
未指定の場合はデフォルトのエンドポイントを利用します。

|ActorId を設定する
|ハーネスのメモリーオペレーションに影響する設定項目です。チェックすることで、InvokeHarness API のパラメータ ActorId を設定します。 +
ハーネスのメモリーが有効な場合に ActorId を設定することで、ハーネスに設定されたデフォルトの ActorId を指定した値で上書きできます。 +
リクエストに設定される ActorId は、テナント・ユーザーごとに決まった値を利用します。

|ActorId 編集スクリプト
|設定する ActorId をカスタマイズするための groovy script を設定します。戻り値として文字列を返却してください。 +
「ActorId を設定する」がチェックされている場合だけ有効になります。

|Request Before Customize
|AIリクエストを実行する前に、リクエストの内容をカスタマイズするための設定項目です。 +
AdminConsole で設定できない内容を設定する場合に利用します。 +
Groovy Script 形式でカスタマイズ処理を実装します。

カスタマイズするリクエストインスタンスは、`software.amazon.awssdk.services.bedrockagentcore.model.InvokeHarnessRequest.Builder` クラスのインスタンスになります。
|===


[[prompt_setting_platform_aws_bedrock_agent_core_runtime_http]]
===== Bedrock AgentCore - Runtime(http)
Bedrock InvokeAgentRuntime API を利用し、Amazon Bedrock AgentCore で定義したHTTPプロトコルに対応したランタイムを利用してリクエストを行うことができます。 +
InvokeAgentRuntime API の詳細については、Amazon Bedrock のドキュメントを参照してください。

状態に対応しており、保持する値は以下の通りです。

.状態に保存する内容
* ランタイムセッションID

設定項目は次の通りです。

[cols="1,3", options="header,autowidth"]
|===
|項目
|説明

|Agent Runtime ARN
|Amazon Bedrock AgentCore ランタイムのARNを設定します。

|エンドポイント Qualifier
|Amazon Bedrock AgentCore で定義したランタイムのエンドポイントを設定します。 +
未指定の場合はデフォルトのエンドポイントを利用します。

|ペイロード作成スクリプト
|ランタイムに送信するペイロードを作成するための groovy script を設定します。戻り値として文字列を返却してください。 +
ペイロードは JSON 形式で送信することを想定していますが、ランタイムの仕様に応じて任意の形式で作成してください。

|Platform 内部レスポンスクラス
|ランタイムからのレスポンスを受け取るためのクラスを設定します。 +
通常機能の受信方法に問題がある場合は、この設定を利用して独自のレスポンスクラスを設定することができます。 +
レスポンスクラスは、 `org.iplass.mtp.impl.ai.prompt.bedrock.awsv2.AbstractBedrockAgentCoreRuntimeHttpInnerResponse` を継承したクラスを設定してください。

|Request Before Customize
|AIリクエストを実行する前に、リクエストの内容をカスタマイズするための設定項目です。 +
AdminConsole で設定できない内容を設定する場合に利用します。 +
Groovy Script 形式でカスタマイズ処理を実装します。

カスタマイズするリクエストインスタンスは、`software.amazon.awssdk.services.bedrockagentcore.model.InvokeAgentRuntimeRequest.Builder` クラスのインスタンスになります。
|===
