// NOTE:
// このファイルは prompt.adoc から include されています。
// prompt_setting_platform_*.adoc のタイトルは "====" から始めてください。
// タグの接頭辞として "prompt_setting_platform_" を設定してください。
[[prompt_setting_platform_knownarrator]]
==== Know Narratorプラットフォーム
Know Narratorプラットフォームでは、Know Narrator API を利用し、Know Narrator に対してリクエストを行うことができます。 +
利用する<<service_provider>>には、Know Narrator 用のサービスプロバイダ設定を指定してください。

Know Narratorプラットフォームでは、以下のプラットフォームタイプを利用することができます。

.Know Narratorで利用可能なプラットフォームタイプ
* <<prompt_setting_platform_knownarrator_chat>>
** Know Narrator Chat API を利用し、チャット形式のリクエストを行います。
* <<prompt_setting_platform_knownarrator_search>>
** Know Narrator Search API を利用し、ナレッジ（データソース）を検索した上でリクエストを行います。


[[prompt_setting_platform_knownarrator_chat]]
===== Know Narrator Chat
Know Narrator Chat API を利用し、Know Narrator に対してチャット形式のリクエストを行うことができます。 +
Know Narrator Chat を利用する場合は、プラットフォームタイプを `KNOW_NARRATOR` に設定してください。 +
Know Narrator Chat API の詳細については、link:https://knownarratordocs-api.dentsusoken.com/[Know Narrator のドキュメント^]を参照してください。

状態に対応しており、保持する値は以下の通りです。

.状態に保存する内容
* 会話ID

会話IDを引き継ぐことで、前回の会話の内容を引き継いだ継続的な会話を行うことができます。 +
継続した会話を行う場合は、レスポンスの `next` メソッドを利用して、会話IDを引き継いだ次のリクエストを作成してください。

設定項目は次の通りです。

[cols="1,3", options="header,autowidth"]
|===
|項目
|説明

|Provider ID
|Know Narrator のAIプロバイダリソースIDを設定します。必須項目です。

|Model ID
|Know Narrator で利用するモデルのIDを設定します。必須項目です。

|Temperature
|サンプリング温度を設定します。0.0 から 2.0 の範囲の数値を設定してください。任意項目です。

|Request Before Customize
|AIリクエストを実行する前に、リクエストの内容をカスタマイズするための設定項目です。 +
AdminConsole で設定できない内容を設定する場合に利用します。 +
Groovy Script 形式でカスタマイズ処理を実装します。

カスタマイズするリクエストインスタンスは、`org.apache.hc.client5.http.entity.mime.MultipartEntityBuilder` クラスのインスタンスになります。
|===


[[prompt_setting_platform_knownarrator_search]]
===== Know Narrator Search
Know Narrator Search API を利用し、登録済みのナレッジ（データソース）を検索した上で回答を生成するリクエストを行うことができます。 +
Know Narrator Search を利用する場合は、プラットフォームタイプを `KNOW_NARRATOR_KNOWLEDGE_CHAT` に設定してください。 +
利用する<<service_provider>>には、Know Narrator 用のサービスプロバイダ設定を指定してください。 +
Know Narrator Search API の詳細については、link:https://knownarratordocs-api.dentsusoken.com/[Know Narrator のドキュメント^]を参照してください。

状態に対応しており、保持する値は以下の通りです。

.状態に保存する内容
* 会話ID

会話IDを引き継ぐことで、前回の会話の内容を引き継いだ継続的な会話を行うことができます。 +
継続した会話を行う場合は、レスポンスの `next` メソッドを利用して、会話IDを引き継いだ次のリクエストを作成してください。

設定項目は次の通りです。

[cols="1,3", options="header,autowidth"]
|===
|項目
|説明

|Deployment Name
|Know Narrator で利用するモデルのデプロイメント名を設定します。必須項目です。

|Search Mode
|ナレッジを検索する際の検索モードを設定します。`keyword`、`hybrid`、`vector`、`hybrid_with_hyde` から選択します。 +
デフォルトは `hybrid` です。任意項目です。

|Temperature
|サンプリング温度を設定します。0.0 から 2.0 の範囲の数値を設定してください。任意項目です。

|Top P
|核サンプリング（Top P）の値を設定します。0.0 から 1.0 の範囲の数値を設定してください。任意項目です。

|Reasoning Effort
|推論の深さを設定します。`low`、`medium`、`high` から選択します。任意項目です。

|Request Before Customize
|AIリクエストを実行する前に、リクエストの内容をカスタマイズするための設定項目です。 +
AdminConsole で設定できない内容を設定する場合に利用します。 +
Groovy Script 形式でカスタマイズ処理を実装します。

カスタマイズするリクエストインスタンスは、JSONリクエストボディを表す `java.util.Map<String, Object>` クラスのインスタンスになります。
|===

レスポンスからは、回答テキストに加えて、回答の根拠となった参照ドキュメントの一覧（参照ID、ファイル名、スコア）や、検索結果に関する警告情報を取得することができます。
