= チュートリアル（ワークフロー）
:_relative-root-path: ../../

iPLAssのワークフロー機能を利用し、さまざまな要件に対応するフローを作成可能です。
ここでは準備編、基本編、実践編に分け、ワークフローの作成方法を説明していきます。

* 準備編 +
ワークフローの概要およびiPLAssでのワークフローを簡単に説明していきます。
* 基本編 +
各イベントの動作および設定方法について、簡単なワークフローを作成しながら説明していきます。 +
* 実践編 +
基本編で説明した内容を利用し、より現実的なワークフローの作成を行います。

== 前提条件
本チュートリアルは以下を前提条件としています。
チュートリアルを進めるにあたり、以下のいずれかを実施し、Webアプリケーションが動作する環境を準備してください。

* <<../gettingstarted/index.adoc#Introduction, Install and Run>>
* <<../installguide/index.adoc#ConstructionEnvironment, Eclipse開発環境の構築>>
* <<../docker/index.adoc#DockerEnvironmentConstruction, Dockerで環境構築>>
* 本チュートリアルは、Enterprise Editionでのみ実施可能です。
+
オープンソース版の環境をEnterprise Editionにアップグレードする場合は、<<../../environment/index.adoc#UpgradeToEnterpriseEdition, Enterprise Editionへのアップグレード>>を参照してください。
+
Dockerの場合、Enterprise Edition版のDockerイメージを利用してください。
+
* User Admin(デフォルトの管理者ユーザー)でGEM画面を操作する場合は、「メニューの変更」から「DEFAULT」のメニューに切り替えて操作してください。本チュートリアルでは、メニュー等の権限設定については割愛しています。

include::preparation_ja.adoc[]

include::basic_ja.adoc[]

include::practice_ja.adoc[]


== 次のステップ
ワークフローについて、このチュートリアルで触れた内容が知りたい場合は、Developer Guideの<<../../developerguide/workflow/index.adoc#, Workflow>>を参照してください。

その他の機能の詳細を理解したい場合は、 <<../../developerguide/index.adoc#,Developer Guide>> を参照し、いろいろと定義を変更してみてください。
