= MDC(Material Design Components)
:_hreflang-path: developerguide/materialdesigncomponents/index.html
:_relative-root-path: ../../
:_menu-title-ee-only: true

MDC（Material Design Components）は、マテリアルデザインに準拠したエンティティの汎用データ操作画面群を提供するモジュールです。 +
MDCモジュールは、link:https://vuejs.org/[Vue.js^]、link:https://vuetifyjs.com/[Vuetify^]を使用して構築された、マテリアルデザインをベースとしたコンポーネント指向のアプリケーションです。レスポンシブデザインに対応しています。

== <<./setup/index.adoc#, 初期設定>>
MDCを利用する際に必要な初期設定の説明です。

== <<./entityview/index.adoc#, EntityView>>
エンティティの定義を元にデータを操作する検索画面、詳細・編集画面を自動生成します。
定義の設定を行うことで、画面毎に細かいカスタマイズができます。

== <<./topview/index.adoc#, TopView>>
MDCモジュールにおけるTop画面の設定です。
用意されたパーツや、独自のテンプレート等を配置し、自由にカスタマイズすることができます。
ロール毎に表示する内容を制御できます。

== <<./navigation/index.adoc#, Navigation>>
各種ナヴィゲーションを管理する設定です。EntityViewやAction等と紐づくメニューアイテムを定義するサイドメニュー（SideMenu）、言語選択やユーザー情報変更などのユーザーメニューを定義するアプリケーションバー（AppBar）から構成されます。
ロール毎に表示する内容を制御できます。

== <<./treegrid/index.adoc#, TreeGrid>>
参照プロパティを含めたエンティティの構造をツリーグリッド形式で表示できます。

== <<./calendar/index.adoc#, Calendar>>
MDCモジュールにおけるカレンダー画面の設定です。単一または複数のEntityデータをカレンダー形式で表示することができます。

== <<./mdcauth/index.adoc#, 権限制御>>
MDC機能に対する権限制御Utilityの提供や、EntityViewの管理設定によるView単位での参照制御をすることができます。

== link:../../storybook/index.html[コンポーネントカタログ^]
MDCで提供するコンポーネントの概要や振る舞いを説明するドキュメントです。サンプル集やオリジナルテンプレートの実装方法についても説明しています。

== link:../../typedoc/index.html[型・APIリファレンス^]
MDCで提供するユーティリティやTypeScriptの型を説明するドキュメントです。